### PR TITLE
Fix prepend website cache class with preview

### LINKED ISSUE #7332: FrankenPHP Preview cache exception
| Q | A
| --- | ---
| Sulu Version | 2.5.13
| PHP Version | 8.3.3
| DB Version | MariaDB 11.0.2
| Browser Version | Google Chrome Version 123.0.6312.58 (Official Build) (64-bit)

# Actual Behavior
I followed https://sulu.io/blog/running-sulu-with-frankenphp article, and created dual Kernel class. Locally when running on `dev` environment everyting works. But running `prod` environment the error is generated.
```
{"level":"error","ts":1711489705.64349,"msg":"PHP Fatal error:  Cannot declare class websiteWebspaceCollectionCache, because the name is already in use in /app/var/cache/preview/prod/sulu/websiteWebspaceCollectionCache.php on line 21","syslog_level":"err"}
```

# Expected Behavior

Error should not be generated.

# Steps to Reproduce

Running on [FrankenPHP](https://hub.docker.com/r/dunglas/frankenphp/tags) docker image with `prod` environemnt, if you clear cache and go to view published article. Then if you try to view same article in the admin preview you get the error and wise versa if after clearing cache first you open admin with preview, then navigating to article page will throw this error.

# Possible Solutions

Maybe this is from [FrankenPHP](https://frankenphp.dev/) also, how the cache is loaded into memory and generated, or not generated or differently generated per workers. :man_shrugging: 

Running same configuration with nginx + php there is no issues at all.

### PR DESCRIPTION
**Pull request by sauls**
| Q | A
| --- | ---
| Bug fix? | yes
| New feature? | no 
| BC breaks? | no 
| Deprecations? | no  
| Fixed tickets | fixes #7332
| Related issues/PRs | # 
| License | MIT
| Documentation PR | sulu/sulu-docs# 

#### What's in this PR?

Fix for https://github.com/sulu/sulu/issues/7332 , don't know if this is the right way. Additionally tried to run tests locally but had issues with db connection, did not looked deeper, did only unit test, but I guess functional test would make more sense. Additionally this bundle has dependency from core_bundle, so in tests somehow we need to put that, so I don't know if in monorepo cross dependency declaration is valid. @alexander-schranz

### CODE REVIEW

**Comment by alexander-schranz** [comment]
@sauls Thx for the pull request. Can you target the 2.4 branch and rebase the pull request to 2.4:

```bash
git checkout your-branch

git remote add sulu git@github.com:sulu/sulu.git
git fetch sulu
git rebase -i sulu/2.5 --onto sulu/2.4

git push --force
```

**Comment by sauls** [comment]
@alexander-schranz I guess I did it right.

File: src/Sulu/Bundle/PreviewBundle/Infrastructure/Symfony/DependencyInjection/Compiler/RegisterPreviewWebspaceClassPass.php [hunk 1]
```diff
@@ -0,0 +1,25 @@
+<?php
+
+namespace Sulu\Bundle\PreviewBundle\Infrastructure\Symfony\DependencyInjection\Compiler;
+
+use Symfony\Component\DependencyInjection\Compiler\CompilerPassInterface;
+use Symfony\Component\DependencyInjection\ContainerBuilder;
+
+class RegisterPreviewWebspaceClassPass implements CompilerPassInterface
```
Comment (alexander-schranz) [inline src/Sulu/Bundle/PreviewBundle/Infrastructure/Symfony/DependencyInjection/Compiler/RegisterPreviewWebspaceClassPass.php]: This should be internal:

```suggestion

/**
 * @internal
 */
class RegisterPreviewWebspaceClassPass implements CompilerPassInterface
```

the php cs header is also missing you can also add it via `composer php-cs-fix`

**Review by alexander-schranz — APPROVED** [review]

File: src/Sulu/Bundle/PreviewBundle/Infrastructure/Symfony/DependencyInjection/Compiler/RegisterPreviewWebspaceClassPass.php (hunk 1 above)
Comment (sauls) [reply src/Sulu/Bundle/PreviewBundle/Infrastructure/Symfony/DependencyInjection/Compiler/RegisterPreviewWebspaceClassPass.php]: added
