### PR TITLE
Fixed publish handling for internal and external links

### LINKED ISSUE #2735: Cannot publish internal / external link
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | 1.2.2
| Browser Version | Chrome latest

#### Actual Behavior

When I create an internal or external link, and try to publish it, sulu reports a success, but after refreshing the page I see that it's still in "Test".
If, however I publish the content first as a regular "Content", and then change the published content to an internal link, it works as expected.

#### Expected Behavior

When I create an internal or external link, I should be able to publish it.

#### Steps to Reproduce

Create a new "Default" content.
After saving, go to settings and change the Page Type to internal link.
Fill out the Link title and linked content fields, then proceed to save.
Try publishing the content.
Refresh the page: it should show that the content is still in "Test" mode.

### PR DESCRIPTION
**Pull request by danrot**
| Q | A
| --- | ---
| Bug fix? | yes
| New feature? | no
| BC breaks? | no
| Deprecations? | no
| Fixed tickets | fixes #2735
| Related issues/PRs | none
| License | MIT
| Documentation PR | none

#### What's in this PR?

This PR fixes the problems I have mentioned in [this comment](https://github.com/sulu/sulu/issues/2735#issuecomment-238807377).

### CODE REVIEW

File: src/Sulu/Bundle/ContentBundle/Resources/public/js/components/content/form/main.js [hunk 1]
```diff
@@ -411,16 +408,6 @@ define(['app-config', 'config', 'services/sulupreview/preview'], function(AppCon
             return url;
         },
 
-        showState: function(published) {
```
Comment (danrot) [inline src/Sulu/Bundle/ContentBundle/Resources/public/js/components/content/form/main.js]: This method handles the appaerance of the test or published icon in the toolbar, but was only implemented in the form. But it should have effect on all tabs, so I moved it.

**Comment by chirimoya** [comment]
ACK, waiting for tests
