### PR TITLE
Fixed property-value offset set

### LINKED ISSUE #3016: Warning in preview functionality
| Q | A
| --- | ---
| Bug? | perhaps
| New Feature? | unlikely
| Sulu Version | 1.3.0
| Browser Version | irrelevant

#### Actual Behavior

It gives a warning somewhere in the preview functionality (I'm seeing this in monitoring).

#### Expected Behavior

There is no warning

#### Steps to Reproduce

``` php
ron-macbook:sulu ron$ php -a
Interactive shell

php > include 'vendor/autoload.php';
php > $test = new Sulu\Component\Content\Document\Structure\PropertyValue('test', ['foo'=>'bar']);
php > $test['foo'] = 'bar';
PHP Warning:  array_merge(): Argument #1 is not an array in /Users/ron/Development/src/OS/sulu/src/Sulu/Component/Content/Document/Structure/PropertyValue.php on line 90

Warning: array_merge(): Argument #1 is not an array in /Users/ron/Development/src/OS/sulu/src/Sulu/Component/Content/Document/Structure/PropertyValue.php on line 90
```

#### Possible Solutions

I'm puzzled by the presence of ```array_merge``` but someone may need it to append items by setting them. If that's true, a simple test if ```$this->value[$offset]``` is an array (and initializing it to an empty array) would suffice. If the ```array_merge``` is a mistake to begin with (perhaps an incorrect way of assigning the value), it can be replace by a value assignment. 

By the way, this also disables any functionality to append new items to the value array:

``` php
php > $test['bar'] = 'bar';
PHP Notice:  Undefined index: bar in /Users/ron/Development/src/OS/sulu/src/Sulu/Component/Content/Document/Structure/PropertyValue.php on line 90

Notice: Undefined index: bar in /Users/ron/Development/src/OS/sulu/src/Sulu/Component/Content/Document/Structure/PropertyValue.php on line 90
PHP Warning:  array_merge(): Argument #1 is not an array in /Users/ron/Development/src/OS/sulu/src/Sulu/Component/Content/Document/Structure/PropertyValue.php on line 90

Warning: array_merge(): Argument #1 is not an array in /Users/ron/Development/src/OS/sulu/src/Sulu/Component/Content/Document/Structure/PropertyValue.php on line 90
```

Relevant line: https://github.com/sulu/sulu/blob/2e648cea065e1d146e580b83612b4c8729850938/src/Sulu/Component/Content/Document/Structure/PropertyValue.php#L90

### PR DESCRIPTION
**Pull request by wachterjohannes**
| Q | A
| --- | ---
| Bug fix? | yes
| New feature? | no
| BC breaks? | no
| Deprecations? | no
| Fixed tickets | fixes #3016
| Related issues/PRs | none
| License | MIT
| Documentation PR | none

#### What's in this PR?

This PR fixes offset-set for class `PropertyValue`

### CODE REVIEW

File: src/Sulu/Component/Content/Document/Structure/PropertyValue.php [hunk 1]
```diff
@@ -87,7 +87,7 @@ public function offsetSet($offset, $value)
             return;
         }
 
-        $this->value[$offset] = array_merge($this->value[$offset], $value);
+        $this->value[$offset] = $value;
```
Comment (danrot) [inline src/Sulu/Component/Content/Document/Structure/PropertyValue.php]: Looks reasonable to me. I am just wondering why it has been different in the first place.

Comment (wachterjohannes) [inline src/Sulu/Component/Content/Document/Structure/PropertyValue.php]: it is used for blocks in preview which also works with this solution.

Comment (RonRademaker) [inline src/Sulu/Component/Content/Document/Structure/PropertyValue.php]: lgtm

Comment (danrot) [inline src/Sulu/Component/Content/Document/Structure/PropertyValue.php]: @RonRademaker I am a bit afraid of this change... It's definitely not doing the same, and I am not sure if there is some case in which this would break something... Do you need that change already in the 1.4 release? Or would 1.5 be sufficient?

Comment (RonRademaker) [inline src/Sulu/Component/Content/Document/Structure/PropertyValue.php]: @nickvanderzwet I'm seeing this as errors in the monitoring of our project, do you know if the client is also experiencing problems as a result?

Comment (wachterjohannes) [inline src/Sulu/Component/Content/Document/Structure/PropertyValue.php]: this error happens in my opinion only in preview which could lead in a non functional preview . but shouldnt be "blocking" for the user

**Comment by danrot** [comment]
@wachterjohannes Can you maybe rebase that? Then we could try to merge it. Better now than in the last RC 😃
