### PR TITLE
Fix clearing address field values via UI

### LINKED ISSUE #8313: Can't clear values from organization address
| Q | A
| --- | ---
| Sulu Version | 2.6.14
| PHP Version | 8.3

# Actual Behavior

If you want to clear the latitude/longitude value from the organization address, this is not possible. After saving, the old value is still stored in the organization.

# Expected Behavior

When clearing an input field in the organization and saving it, the value should be updated to an empty value.

# Steps to Reproduce

- Open Organization admin
- Fill in some address-fields in the overlay like lat/lng
- Save & refresh
- Remove content from the input fields in the address like lat/lng
- Save & refresh
- The old values are still there

# Possible Solutions

In` AbstractContactManager::updateAddress()` there are multiple if clauses using `isset($entry[$fieldname])`.
As the frontend sends a `null` value instead of an empty string, if the field is empty. The isset check returns false in this this case and does not override the old value.
This could be solved in two ways:
- Frontend: send an empty string to the backend
- Backend: exchanging isset with array_key_exists

If you would like it to be solved via backend, I could do it.

### PR DESCRIPTION
**Pull request by MarkusHolstein**
| Q | A
| --- | ---
| Bug fix? | yes
| New feature? | no
| BC breaks? | no
| Deprecations? | no
| Fixed tickets | fixes #8313
| Related issues/PRs | #8313
| License | MIT

#### What's in this PR?

Allows to clear address data from organizations via Admin UI

#### Why?

When emtpying a pre existing value from an address, the new empty value was not persisted.

### CODE REVIEW

File: src/Sulu/Bundle/ContactBundle/Contact/AbstractContactManager.php [hunk 1]
```diff
@@ -1356,60 +1356,60 @@ protected function updateAddress(Address $address, $entry, &$isMain = null)
...
-        if (isset($entry['title'])) {
+        if (\array_key_exists('title', $entry)) {
             $address->setTitle($entry['title']);
         }
-        if (isset($entry['primaryAddress'])) {
+        if (\array_key_exists('primaryAddress', $entry)) {
             $isMain = $this->getBooleanValue($entry['primaryAddress']);
         } else {
             $isMain = false;
         }
```
Comment (mamazu) [inline src/Sulu/Bundle/ContactBundle/Contact/AbstractContactManager.php]:
```suggestion
        $isMain = $this->getBooleanValue($entry['primaryAddress'] ?? false);
```

**Comment by mamazu** [comment]
You can also fix most of the phpstan warnings by changing the doctype of `$entry` to array. (Will cause other warnings but less warnings)

File: src/Sulu/Bundle/ContactBundle/Contact/AbstractContactManager.php (hunk 1 above)
Comment (MarkusHolstein) [reply src/Sulu/Bundle/ContactBundle/Contact/AbstractContactManager.php]: Yes, I saw that, but I am always a little bit fearful, as to how far my refactorings of third party code should go. But I agree, this is far better. I changed that

**Comment by alexander-schranz** [comment]
Looks like I can not rebase this PR and apply the baseline changes. Does the PR have `allow maintainer edit` activated? Or did you restrict the whole perspective fork?

Can you apply this patch:

<details><summary>diff.patch</summary>

```
diff --git a/phpstan-baseline.neon b/phpstan-baseline.neon
index 870eb68dde..f0802f9d69 100644
--- a/phpstan-baseline.neon
+++ b/phpstan-baseline.neon
@@ -6240,96 +6240,6 @@ parameters:
 			count: 1
 			path: src/Sulu/Bundle/ContactBundle/Contact/AbstractContactManager.php
 
-		-
-			message: "#^Cannot access offset 'addition' on mixed\\.$#"
-			count: 1
-			path: src/Sulu/Bundle/ContactBundle/Contact/AbstractContactManager.php
-
-		-
-			message: "#^Cannot access offset 'addressType' on mixed\\.$#"
-			count: 2
-			path: src/Sulu/Bundle/ContactBundle/Contact/AbstractContactManager.php
-
-		-
-			message: "#^Cannot access offset 'billingAddress' on mixed\\.$#"
-			count: 1
-			path: src/Sulu/Bundle/ContactBundle/Contact/AbstractContactManager.php
-
-		-
-			message: "#^Cannot access offset 'city' on mixed\\.$#"
-			count: 1
-			path: src/Sulu/Bundle/ContactBundle/Contact/AbstractContactManager.php
-
-		-
-			message: "#^Cannot access offset 'countryCode' on mixed\\.$#"
-			count: 1
-			path: src/Sulu/Bundle/ContactBundle/Contact/AbstractContactManager.php
-
-		-
-			message: "#^Cannot access offset 'deliveryAddress' on mixed\\.$#"
-			count: 1
-			path: src/Sulu/Bundle/ContactBundle/Contact/AbstractContactManager.php
-
-		-
-			message: "#^Cannot access offset 'latitude' on mixed\\.$#"
-			count: 1
-			path: src/Sulu/Bundle/ContactBundle/Contact/AbstractContactManager.php
-
-		-
-			message: "#^Cannot access offset 'longitude' on mixed\\.$#"
-			count: 1
-			path: src/Sulu/Bundle/ContactBundle/Contact/AbstractContactManager.php
-
-		-
-			message: "#^Cannot access offset 'note' on mixed\\.$#"
-			count: 1
-			path: src/Sulu/Bundle/ContactBundle/Contact/AbstractContactManager.php
-
-		-
-			message: "#^Cannot access offset 'number' on mixed\\.$#"
-			count: 1
-			path: src/Sulu/Bundle/ContactBundle/Contact/AbstractContactManager.php
-
-		-
-			message: "#^Cannot access offset 'postboxCity' on mixed\\.$#"
-			count: 1
-			path: src/Sulu/Bundle/ContactBundle/Contact/AbstractContactManager.php
-
-		-
-			message: "#^Cannot access offset 'postboxNumber' on mixed\\.$#"
-			count: 1
-			path: src/Sulu/Bundle/ContactBundle/Contact/AbstractContactManager.php
-
-		-
-			message: "#^Cannot access offset 'postboxPostcode' on mixed\\.$#"
-			count: 1
-			path: src/Sulu/Bundle/ContactBundle/Contact/AbstractContactManager.php
-
-		-
-			message: "#^Cannot access offset 'primaryAddress' on mixed\\.$#"
-			count: 1
-			path: src/Sulu/Bundle/ContactBundle/Contact/AbstractContactManager.php
-
-		-
-			message: "#^Cannot access offset 'state' on mixed\\.$#"
-			count: 1
-			path: src/Sulu/Bundle/ContactBundle/Contact/AbstractContactManager.php
-
-		-
-			message: "#^Cannot access offset 'street' on mixed\\.$#"
-			count: 1
-			path: src/Sulu/Bundle/ContactBundle/Contact/AbstractContactManager.php
-
-		-
-			message: "#^Cannot access offset 'title' on mixed\\.$#"
-			count: 1
-			path: src/Sulu/Bundle/ContactBundle/Contact/AbstractContactManager.php
-
-		-
-			message: "#^Cannot access offset 'zip' on mixed\\.$#"
-			count: 1
-			path: src/Sulu/Bundle/ContactBundle/Contact/AbstractContactManager.php
-
 		-
 			message: "#^If condition is always true\\.$#"
 			count: 1
@@ -8610,6 +8520,11 @@ parameters:
 			count: 2
 			path: src/Sulu/Bundle/ContactBundle/Tests/Functional/Controller/AccountControllerTest.php
 
+		-
+			message: "#^Cannot access offset 'addresses' on mixed\\.$#"
+			count: 2
+			path: src/Sulu/Bundle/ContactBundle/Tests/Functional/Controller/AccountControllerTest.php
+
 		-
 			message: "#^Cannot access offset 'contact' on mixed\\.$#"
 			count: 1
@@ -8637,7 +8552,7 @@ parameters:
 
 		-
 			message: "#^Cannot access offset 0 on mixed\\.$#"
-			count: 6
+			count: 8
 			path: src/Sulu/Bundle/ContactBundle/Tests/Functional/Controller/AccountControllerTest.php
 
 		-
@@ -13225,11 +13140,6 @@ parameters:
 			count: 1
 			path: src/Sulu/Bundle/MediaBundle/Controller/MediaController.php
 
-		-
-			message: "#^Parameter \\#1 \\$id of method Sulu\\\\Bundle\\\\MediaBundle\\\\Entity\\\\CollectionRepositoryInterface\\:\\:findCollectionTypeById\\(\\) expects int, mixed given\\.$#"
-			count: 1
-			path: src/Sulu/Bundle/MediaBundle/Controller/MediaController.php
-
 		-
 			message: "#^Parameter \\#2 \\$fieldDescriptors of method Sulu\\\\Bundle\\\\MediaBundle\\\\Controller\\\\MediaController\\:\\:getListBuilder\\(\\) expects array\\<Sulu\\\\Component\\\\Rest\\\\ListBuilder\\\\FieldDescriptorInterface\\>, array\\<Sulu\\\\Component\\\\Rest\\\\ListBuilder\\\\FieldDescriptorInterface\\>\\|null given\\.$#"
 			count: 1
diff --git a/src/Sulu/Bundle/ContactBundle/Contact/AbstractContactManager.php b/src/Sulu/Bundle/ContactBundle/Contact/AbstractContactManager.php
index b40d369410..e81ebdebbe 100644
--- a/src/Sulu/Bundle/ContactBundle/Contact/AbstractContactManager.php
+++ b/src/Sulu/Bundle/ContactBundle/Contact/AbstractContactManager.php
@@ -1337,7 +1337,7 @@ abstract class AbstractContactManager implements ContactManagerInterface
      * Updates the given address.
      *
      * @param Address $address The phone object to update
-     * @param array $entry The entry with the new data
+     * @param array<string, mixed> $entry The entry with the new data
      * @param bool $isMain returns if address should be set to main
      *
      * @return bool True if successful, otherwise false

```


</details>

**Review by alexander-schranz — APPROVED** [review]
