### PR TITLE
Fix application crash if autocomplete query is not a valid regular expression

### LINKED ISSUE #5441: Supplying * asterix into tag selection UI fails with blank screen
| Q | A
| --- | ---
| Sulu Version | 2.1.0
| Browser Version | Firefox 68.2

# Actual Behavior
supplying `*` into `tag_selection` UI fails with blank screen

browser console output:
```
SyntaxError: "nothing to repeat"
    <anonymous> Suggestion.js:28
    value AutoCompletePopover.js:116
    value AutoCompletePopover.js:114
    value Suggestion.js:82
```

### PR DESCRIPTION
**Pull request by niklasnatter**
| Q | A
| --- | ---
| Bug fix? | yes
| New feature? | no
| BC breaks? | no
| Fixed tickets | fixes #5441
| License | MIT

#### What's in this PR?

This pull request adjusts the `Suggestion` component that is used by the `AutoComplete` components to be able to handle a query that is not a valid regular expression.

#### Why?

At the moment, the `Suggestion` component throws an error that crashes the administration interface, if the user enters a query that is not a valid regular expression like `*`. See #5441

### CODE REVIEW

File: src/Sulu/Bundle/AdminBundle/Resources/js/components/AutoCompletePopover/Suggestion.js [hunk 1]
```diff
@@ -24,21 +24,23 @@ export default class Suggestion extends React.PureComponent<Props> {
...
+        let matcher;
+        try {
+            // try to match all highlighted parts using case insensitive regular expression
+            matcher = new RegExp(this.props.query, 'gi');
+        } catch (e) {
+            // fallback to highlight first exact match if given query is an invalid regular expression like "*"
+            matcher = this.props.query;
+        }
+
+        const highlightedText = text.replace(matcher, '<strong>$&</strong>');
```
Comment (niklasnatter) [inline src/Sulu/Bundle/AdminBundle/Resources/js/components/AutoCompletePopover/Suggestion.js]: unfortunately, we cannot easily use `replaceAll` here because it is not supported before `Node 15`:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/replaceAll

Comment (niklasnatter) [reply src/Sulu/Bundle/AdminBundle/Resources/js/components/AutoCompletePopover/Suggestion.js]: `replace` will highlight all matches if the query is a valid regular expression. if it is not a valid regular expression, only the first exact match will be highlighted. 

i think this should be okay, because the second case happens very rarely (it is the same case that crashed the application until now).

Comment (alexander-schranz) [reply src/Sulu/Bundle/AdminBundle/Resources/js/components/AutoCompletePopover/Suggestion.js]: can we have different babel settings for tests? or import the core-js polyfill only in the tests? https://github.com/zloirock/core-js ?

Comment (niklasnatter) [reply src/Sulu/Bundle/AdminBundle/Resources/js/components/AutoCompletePopover/Suggestion.js]: not sure about babel, but i think we could import the polyfill inside of the `testSetup.config.js` 🙂 
but as far as i see, `core-js` is not declared anywhere in our dependencies. i think i would need to add it?

Comment (alexander-schranz) [reply src/Sulu/Bundle/AdminBundle/Resources/js/components/AutoCompletePopover/Suggestion.js]: We could add it as test dependency if we did not yet need it anywhere. But I'm also then fine to keep it with this solution if all works and testa are green.

Comment (niklasnatter) [reply src/Sulu/Bundle/AdminBundle/Resources/js/components/AutoCompletePopover/Suggestion.js]: maybe we could set another babel configuration using the jest `transform` option:
https://jestjs.io/docs/configuration#transform-objectstring-pathtotransformer--pathtotransformer-object

will have another looks at this when i find the time

Comment (niklasnatter) [reply src/Sulu/Bundle/AdminBundle/Resources/js/components/AutoCompletePopover/Suggestion.js]: it looks like there is a bug in babel and babel does not transpile `String.replaceAll()` at all at the moment:
https://github.com/babel/babel/issues/13701

because of this, we cannot solve this by using a different babel config for tests 😕

File: package.json [hunk 2]
```diff
@@ -106,20 +106,6 @@
             "enzyme-to-json/serializer"
         ],
         "clearMocks": true,
-        "transform": {
```
Comment (niklasnatter) [inline package.json:108]: i figured that this is not needed anymore while testing https://github.com/sulu/sulu/pull/6231#discussion_r710073550 🙂

File: src/Sulu/Bundle/AdminBundle/Resources/js/components/AutoCompletePopover/Suggestion.js (hunk 1 above)
Comment (alexander-schranz) [reply src/Sulu/Bundle/AdminBundle/Resources/js/components/AutoCompletePopover/Suggestion.js]: I think currently babel is not correctly configured as I think we should use `usage` in the usebuiltins babel configuration.
https://babeljs.io/docs/en/babel-preset-env#usebuiltins-usage

Comment (niklasnatter) [reply src/Sulu/Bundle/AdminBundle/Resources/js/components/AutoCompletePopover/Suggestion.js]: thats right! i created a separate pull request for this: https://github.com/sulu/sulu/pull/6241

Comment (nnatter) [reply src/Sulu/Bundle/AdminBundle/Resources/js/components/AutoCompletePopover/Suggestion.js:40]: thats right! i created a separate pull request for this: https://github.com/sulu/sulu/pull/6241

Comment (niklasnatter) [reply src/Sulu/Bundle/AdminBundle/Resources/js/components/AutoCompletePopover/Suggestion.js]: i finally managed to change this to `replaceAll` 🥳

**Review by alexander-schranz — APPROVED** [review]
