### PR TITLE
Invalidate System collections cache in warmUp

### LINKED ISSUE #5245: System media collections are not created when cache is not cleared manually
| Q | A
| --- | ---
| Sulu Version | 2.0.6
| Browser Version | Chrome last 

# Actual Behavior

Hi, i have a strange issue. In a fresh install, System media collections are not created, all media is empty. Then if i try to upload an image in a organization it fails becase it trying to upload the image in collection "6" that not exists. 
It's strange because I recently saw that they were created correctly when trying to upload an image 

# Expected Behavior

System collections must be created when install and maybe protected.

# Steps to Reproduce

Clear db, execute install and inspect media. Later try to add an image to a organization

### PR DESCRIPTION
**Pull request by plozmun**
| Q | A
| --- | ---
| Bug fix? | yes
| New feature? | no
| BC breaks? | no
| Deprecations? | no
| Fixed tickets | fixes  #5245 
| Related issues/PRs | -
| License | MIT
| Documentation PR | -

#### What's in this PR?

Invalidate media cache file on warmup.

I have changed test to use PHPUnit without `prophesize`. I think it's more clear . WDT?

#### BC Breaks/Deprecations

No BC Breaks

### CODE REVIEW

**Comment by alexander-schranz** [comment]
I don't think this will fix #5245 as the cache is never warmup in sulu:build command. As said there. There should be an own SuluBuilder class which does clear this cache.

**Comment by plozmun** [comment]
The SystemCollectionBuilder is who execute warmUp , here: https://github.com/sulu/sulu/blob/e816ec1651c11cffa627d9e27284d10367d3907f/src/Sulu/Component/Media/SystemCollections/SystemCollectionBuilder.php#L53

**Comment by plozmun** [comment]
I have checked and it remove the file in sulu:build command :)

**Comment by alexander-schranz** [comment]
Ok there seems to be an exist a builder. But the `if fresh` is a little bit strange think it should be always invalidated the cache on warmUp then.

File: src/Sulu/Component/Media/Tests/Unit/SystemCollections/SystemCollectionManagerTest.php [hunk 1]
```diff
@@ -371,17 +383,33 @@ public function testWarmUpFresh($config, $existingCollections, $notExistingColle
         $collectionManager = $this->getCollectionManager($existingCollections, $notExistingCollections, false);
 
         $entityManager = $this->prophesize(EntityManagerInterface::class);
-        $cache = $this->prophesize(CacheInterface::class);
-        $cache->isFresh()->shouldBeCalled()->willReturn(true);
-        $cache->write($data)->shouldNotBeCalled();
-        $cache->read()->shouldBeCalled()->willReturn($data);
+        $cache = $this->createMock(CacheInterface::class);
```
Comment (alexander-schranz) [inline src/Sulu/Component/Media/Tests/Unit/SystemCollections/SystemCollectionManagerTest.php:386]: please use `prophesize` to mock the the cache

File: src/Sulu/Component/Media/Tests/Unit/SystemCollections/SystemCollectionManagerTest.php [hunk 2]
```diff
@@ -345,17 +345,29 @@ public function testWarmUpNotFresh($config, $existingCollections, $notExistingCo
         $collectionManager = $this->getCollectionManager($existingCollections, $notExistingCollections);
 
         $entityManager = $this->prophesize(EntityManagerInterface::class);
-        $cache = $this->prophesize(CacheInterface::class);
-        $cache->isFresh()->shouldBeCalled()->willReturn(false);
-        $cache->write($data)->shouldBeCalled();
-        $cache->read()->shouldBeCalled()->willReturn($data);
+        $cache = $this->createMock(CacheInterface::class);
```
Comment (alexander-schranz) [inline src/Sulu/Component/Media/Tests/Unit/SystemCollections/SystemCollectionManagerTest.php:348]: use `prophesize` to mock the cache we should be consistent

**Comment by plozmun** [comment]
> Ok there seems to be an exist a builder. But the `if fresh` is a little bit strange think it should be always invalidated the cache on warmUp then.

Is the behavior of DataCache , isFresh only check if file exists before remove otherwise it launch a IOException

File: src/Sulu/Component/Media/Tests/Unit/SystemCollections/SystemCollectionManagerTest.php (hunk 2 above)
Comment (plozmun) [reply src/Sulu/Component/Media/Tests/Unit/SystemCollections/SystemCollectionManagerTest.php:348]: Ok, I will change but why use prophesize when is not necessary ?

Comment (alexander-schranz) [reply src/Sulu/Component/Media/Tests/Unit/SystemCollections/SystemCollectionManagerTest.php:348]: To be consistent in the code.

**Comment by nnatter** [comment]
> Is the behavior of DataCache , isFresh only check if file exists before remove otherwise it launch a IOException

This is a strange behaviour, isnt it? 🙈 Maybe we should add the same check as in the `read()` method? At least I would add a comment why the `isFresh()` call is needed - I wondered about that too 🙂

**Comment by plozmun** [comment]
> > Is the behavior of DataCache , isFresh only check if file exists before remove otherwise it launch a IOException
> 
> This is a strange behaviour, isnt it? 🙈 Maybe we should add the same check as in the `read()` method? At least I would add a comment why the `isFresh()` call is needed - I wondered about that too 🙂

Sorry, my bad, Exception is not launched. I will remove the isFresh check

File: src/Sulu/Component/Media/SystemCollections/SystemCollectionManager.php [hunk 3]
```diff
@@ -76,6 +76,9 @@ public function __construct(
 
     public function warmUp()
     {
+        if ($this->cache->isFresh()) {
```
Comment (danrot) [inline src/Sulu/Component/Media/SystemCollections/SystemCollectionManager.php:79]: This reads very strange... If the cache is still fresh, there is actually no point of invalidating it, isn't it? But I have seen that the `isFresh` call just checks for the existence of the file... Since it reads so strange I would either simply always call `$this->cache->invalidate()`. If it causes any problems when the file is not existing, I would handle that in the `invalidate` method (just do nothing then). I think that would be a reasonable behavior, since the end result would be the same.

**Comment by plozmun** [comment]
Hi! I have updated PR like suggestions. I left only one test because now the file is always deleted.
IMHO I think DataCache must be replaced by cache.app or removed completely and let the responsability to the CollectionManager

**Comment by danrot** [comment]
Seems like travis thinks you are abusing our build :see_no_evil: 
Screenshot from 2020-04-22 19-51-26
 Tried to amend the latest commit, let's see if it works then.

**Comment by danrot** [comment]
@plozmun Have you never logged in into travis ci? If not, can you try do so? According to [this article in their community that might help](https://travis-ci.community/t/some-pr-are-not-analyzed-with-message-abuse-detected/1191)

**Comment by plozmun** [comment]
> @plozmun Have you never logged in into travis ci? If not, can you try do so? According to [this article in their community that might help](https://travis-ci.community/t/some-pr-are-not-analyzed-with-message-abuse-detected/1191)

Nope, I just logged in

**Comment by plozmun** [comment]
Captura de pantalla 2020-04-22 a las 20 06 29
:scream: :scream: :scream:

**Comment by alexander-schranz** [comment]
@plozmun can you try to contact them?

**Comment by plozmun** [comment]
The warning disappeared when I resynced with github. I hope it doesn't happen again 🤞

**Comment by alexander-schranz** [comment]
@plozmun can you try to repush to se if travis is now triggered correctly:

```
git commit --amend --date="now"
git push yourremote bugfix/warmup-cache-fresh --force
```

**Comment by plozmun** [comment]
Done!

**Comment by danrot** [comment]
It didn't seem to work and now travis is under maintenance... I'll just run the tests locally and merge it. Hopefully it does not break anything, but appveyor seems to work.

**Comment by plozmun** [comment]
Now it works again, but i can's see the build in my dashboard. Is abuse detected again? If so, let me the URL o ID to write a email to support . Thanks

**Comment by danrot** [comment]
Screenshot from 2020-04-23 08-57-26
Looks like it... I guess they won't change that opinion about you in that PR anymore :see_no_evil: Let's hope it works in the next one.

**Comment by plozmun** [comment]
Ok, i will write to travis support because I'm afraid it will happen again. My last two PR in sulu repository had the same problem with travis :(

**Comment by danrot** [comment]
Yeah, but now you are registered there, so maybe that really helps. But contacting them just to be sure might not be the worst idea :slightly_smiling_face:

**Comment by danrot** [comment]
@plozmun Thank you for your contribution! Hopefully tests will also succeed on travis now :see_no_evil:

**Comment by plozmun** [comment]
Thanks to you @danrot
