### PR TITLE
Fix media types configuration

### LINKED ISSUE #4343: [MediaBundle] format manager types configuration cannot be changed
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | <= 1.6.24, dev-develop
| Browser Version | All

#### Actual Behavior

Sulu crashes when trying to configure types under format_manager.

#### Expected Behavior

Sulu does not crash when configuring types for the format manager

#### Steps to Reproduce

Configure your types:

```
sulu_media:
    format_manager:
        types:
            -
                type: image
                mimeTypes:
                    - 'image/jpg'
```

#### Possible Solutions

Prototype scalar in Configuration.php should be changed to arrayPrototype.

### PR DESCRIPTION
**Pull request by markdehaan**
| Q | A
| --- | ---
| Bug fix? | yes
| New feature? | no
| BC breaks? | no
| Deprecations? | no
| Fixed tickets | fixes #4343
| License | MIT

#### What's in this PR?

Changed configuration tree builder in order to stop Sulu from crashing.

### CODE REVIEW

File: src/Sulu/Bundle/MediaBundle/DependencyInjection/Configuration.php [hunk 1]
```diff
@@ -118,7 +118,14 @@ public function getConfigTreeBuilder()
                         ])
                     ->end()
                     ->arrayNode('types')
-                        ->prototype('scalar')->end()->defaultValue([
+                        ->prototype('array')
+                            ->children()
+                                ->enumNode('type')->values(['document', 'image', 'video', 'audio'])->isRequired()->end()
```
Comment (alexander-schranz) [inline src/Sulu/Bundle/MediaBundle/DependencyInjection/Configuration.php]: This would dissallow that somebody adds a new type would not change this in a hotfix release

**Comment by alexander-schranz** [comment]
@markdehaan Thank you for your pull request! Can I ask you which mimetypes you want to change in your application and why, just if its maybe something which is interesting for 2.0 to be changed.

File: src/Sulu/Bundle/MediaBundle/DependencyInjection/Configuration.php (hunk 1 above)
Comment (markdehaan) [reply src/Sulu/Bundle/MediaBundle/DependencyInjection/Configuration.php]: Yes I agree, I made an update so it is possible now to add new types.

**Comment by markdehaan** [comment]
@alexander-schranz We were just experimenting with the config when we encountered this bug. For the moment there is no explicit need to change the mime types.

**Comment by alexander-schranz** [comment]
@markdehaan can you rebase (update) your branch with the latest changes from master, then PrettyCI should not longer fail.

**Comment by alexander-schranz** [comment]
@markdehaan and can you add a line to the CHANGELOG.md

**Comment by alexander-schranz** [comment]
@markdehaan sorry bothering you again. Can you create a new `* dev-master*  section in the changelog we had a release yesterday.

**Comment by markdehaan** [comment]
@alexander-schranz "continuous-integration/styleci/pr" is waiting for status to be reported since friday...

**Comment by alexander-schranz** [comment]
@markdehaan can be ignored aslong prettyci is green.
@danrot from my site its ok do you want to have also a look at it?

**Comment by danrot** [comment]
@markdehaan Thank you! :slightly_smiling_face:
