### PR TITLE
Fix category resource loader to return category api object

### LINKED ISSUE #8524: Category name in excerpt
| Q | A |
| --- | --- |
| Sulu Version | 3.0.2 |
| PHP Version | 8.3 |
| DB Version | MySQL 8 |
| Browser Version | Chrome 142 |

## Actual Behavior

In **Sulu 3.0**, categories linked to a page or an article no longer expose a simple `name` property in Twig templates.

In **Sulu 2.6**, categories could be rendered like this:

```twig
{% for category in extension.excerpt.categories %}
    <span>{{ category.name }}</span>
{% endfor %}
```
In Sulu 3.0, this no longer works.
Instead, it is now necessary to manually resolve the translation:
```twig
{% for category in extension.excerpt.categories %}
    <span>{{ category.findTranslationByLocale(app.request.locale).translation }}</span>
{% endfor %}
```
This represents a breaking change compared to Sulu 2.6 and makes template code more complex.

# Expected Behavior

Categories should expose a locale-aware name property (or equivalent) in Twig, similar to Sulu 2.6.

# Expected behavior:

- category.name should return the translated category name for the current locale
- Template code should not require manual calls to findTranslationByLocale(...)
- Backward compatibility with Sulu 2.6 templates should be preserved if possible

### PR DESCRIPTION
**Pull request by alexander-schranz**
| Q | A
| --- | ---
| Bug fix? | no
| New feature? | no 
| BC breaks? | no 
| Deprecations? | no 
| Fixed tickets | fixes https://github.com/sulu/sulu/issues/8524
| Related issues/PRs | # 
| License | MIT
| Documentation PR | sulu/sulu-docs# 

#### What's in this PR?

Fix category resource loader to return category api object.

#### Why?

See https://github.com/sulu/sulu/issues/8524

### CODE REVIEW

File: src/Sulu/Bundle/CategoryBundle/Tests/Unit/Infrastructure/Sulu/Content/ResourceLoader/CategoryResourceLoaderTest.php [hunk 1]
```diff
@@ -67,6 +74,11 @@ private static function createCategory(int $id): Category
         static::setPrivateProperty($category, 'id', $id);
         $category->setKey('category-' . $id);
 
+        $categoryTranslation = new CategoryTranslation();
+        $categoryTranslation->setCategory($category);
+        $categoryTranslation->setLocale('en');
```
Comment (alexander-schranz) [inline src/Sulu/Bundle/CategoryBundle/Tests/Unit/Infrastructure/Sulu/Content/ResourceLoader/CategoryResourceLoaderTest.php:79]: To check the locale I need a translation else null is returned: https://github.com/sulu/sulu/blob/c44ba96dc4dcd38d61f59647f54a2e1e55e42a43/src/Sulu/Bundle/CategoryBundle/Api/Category.php#L152

**Review by Prokyonn — APPROVED** [review]
