### PR TITLE
fixed uncatchable exception when use sulu_media_resolve twig extension

### LINKED ISSUE #2881: MediaNotFoundException in resolveMediaFunction twig function
| Q | A |
| --- | --- |
| Bug? | yes |
| New Feature? | no |
| Sulu Version | 1.3.0 |
#### Actual Behavior

When you request a none exist media with `sulu_resolve_media` an exception is thrown.
#### Expected Behavior

The MediaNotFoundException should be catched by the twig extension.
#### Steps to Reproduce

``` twig
{% set media = sulu_resolve_media(null, 'de') %}
```
#### Possible Solutions

Catch the `MediaNotFoundException` in `MediaTwigExtension`.

### PR DESCRIPTION
**Pull request by alexander-schranz**
| Q | A |
| --- | --- |
| Bug fix? | yes |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Fixed tickets | fixes #2881 |
| License | MIT |
#### What's in this PR?

Fixed #2881 call of sulu_media_resolve with not exist media.
#### Why?

You are not able to catch exceptions in twig.
#### Example Usage

{% set media = sulu_media_resolve(null, 'de') %}

### CODE REVIEW

**Comment by wachterjohannes** [comment]
@danrot you should decide when the PR should be merged for `1.4`.

File: src/Sulu/Bundle/MediaBundle/Twig/MediaTwigExtension.php [hunk 1]
```diff
@@ -50,15 +51,23 @@ public function getFunctions()
...
+        }
+
         if (is_object($media)) {
             return $this->resolveMediaObject($media, $locale);
         }
 
-        return $this->mediaManager->getById($media, $locale);
+        try {
+            return $this->mediaManager->getById($media, $locale);
+        } catch (MediaNotFoundException $e) {
```
Comment (danrot) [inline src/Sulu/Bundle/MediaBundle/Twig/MediaTwigExtension.php]: Isn't that also happening for the `resolveMediasFunction`?

Comment (alexander-schranz) [inline src/Sulu/Bundle/MediaBundle/Twig/MediaTwigExtension.php]: no multiple medias use the getByIds function which does not throw an exception when a media not exist. the not existing media is just ignored.

**Comment by alexander-schranz** [comment]
@danrot rebased
