### PR TITLE
Fix block settings in xliff export / import

### LINKED ISSUE #7951: Page XLIFF translations export without block settings
| Q | A
| --- | ---
| Sulu Version | 2.6.8
| PHP Version | 8.3
| DB Version | Maria DB 10.9
| Browser Version | Chrome 136

# Actual Behavior

With current translation export via `bin/console sulu:webspaces:export` `bin/console sulu:snippet:export` or `bin/console sulu:article:export` the export have no block settings information. After the page is translated and the translation is imported again, the block settings are missing and e.g. not published blocks are published.

# Expected Behavior

Block settings are available on export and are written on import

### PR DESCRIPTION
**Pull request by draconivis**
| Q | A
| --- | ---
| Bug fix? | yes
| New feature? | no
| BC breaks? | no
| Deprecations? | no
| Fixed tickets | fixes #7951
| Related issues/PRs | #7951
| License | MIT
| Documentation PR | -

#### What's in this PR?

add the block settings to an export and handle them in import.

#### Why?

#7951

#### Example Usage

Assuming you have a webspace with multiple localizations and a page template with blocks configured:
- Add a block to a page and set it to 'hidden'
- Create an export with `bin/adminconsole sulu:webspaces:export`
- Reimport the data
- The blocks should have the same settings.

### CODE REVIEW

File: src/Sulu/Component/Content/Types/BlockContentType.php [hunk 1]
```diff
@@ -240,18 +240,20 @@ private function doWrite(
...
-                    $i,
-                    $node,
-                    $userId,
-                    $webspaceKey,
-                    $languageCode,
-                    $segmentKey,
-                    $isImport
-                );
+                if (\is_array($blockSettings = $blockPropertyType->getSettings())) {
+                    $this->writeProperty(
```
Comment (alexander-schranz) [inline src/Sulu/Component/Content/Types/BlockContentType.php]: We should not assign variables inside the if statement:

```suggestion
                $blockSettings = $blockPropertyType->getSettings();
                if (\is_array($blockSettings)) {
                    $this->writeProperty(
```

**Review by alexander-schranz — CHANGES_REQUESTED** [review]

**Review by alexander-schranz — APPROVED** [review]
