### PR TITLE
Smart content in snippet

### LINKED ISSUE #2939: smart_content property in a snippet is not working
| Q | A |
| --- | --- |
| Bug? | yes |
| New Feature? | no |
| Sulu version | 1.3.0 |
#### Actual Behavior

When trying to add a new snippet from the template, clicking on the smart_content button,
window is opening, but when trying to open the data source, nothing happens and the following error is showing in the console :
`{code: 0, message: "Call to a member function getKey() on null",…}
code
:
0
errors
:
[{message: "Call to a member function getKey() on null", code: 0,…}]
message
:
"Call to a member function getKey() on null"`

### PR DESCRIPTION
**Pull request by trickreich**
| Q | A
| --- | ---
| Bug fix? | yes
| New feature? | no
| BC breaks? | no
| Deprecations? | no
| Fixed tickets | fixes #2939 
| Related issues/PRs | --
| License | MIT
| Documentation PR | --

#### What's in this PR?

Fixed not working smart content in snippet bundle.
Init the smart content manager correctly.

### CODE REVIEW

File: src/Sulu/Bundle/SnippetBundle/Resources/public/js/components/snippet/form/details/main.js [hunk 1]
```diff
@@ -157,6 +158,8 @@ define(['app-config'], function(AppConfig) {
                     this.initSortableBlock();
                     this.bindFormEvents();
 
+                    this.sandbox.emit('sulu.content.initialized', data);
```
Comment (trickreich) [inline src/Sulu/Bundle/SnippetBundle/Resources/public/js/components/snippet/form/details/main.js]: This event is only used by the SmartContentManager

Comment (danrot) [inline src/Sulu/Bundle/SnippetBundle/Resources/public/js/components/snippet/form/details/main.js]: Then it actually has the wrong name... But lets keep it like that for the sake of consistency.
