### PR TITLE
Avoid setting id properties on block values

### LINKED ISSUE #5185: Remove __id property from request sent using the blocks field type
| Q | A
| --- | ---
| Sulu Version | Sulu 2.0.4
| Browser Version | Google Chrome 80.0.3987.149

# Actual Behavior

How does Sulu behave at the moment? 

Odd behaviour when moving a block to the top, a new block gets created which can not be interacted(aside from moving it, then blocks start disappearing), I uploaded a video for clarification

# Expected Behavior

What is the behavior you expect?

I expect the block to get moved to the top without a new block appearing

# Steps to Reproduce

project-blocks.xml

```
<properties xmlns="http://schemas.sulu.io/template/template"
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xmlns:xi="http://www.w3.org/2001/XInclude"
            xsi:schemaLocation="http://schemas.sulu.io/template/template http://schemas.sulu.io/template/template-1.0.xsd">
    <block name="blocks" default-type="text" minOccurs="0">
        <meta>
            <title lang="en">Content</title>
        </meta>

        <types>
            <xi:include href="project-blocks/skill.xml"
                        xpointer="xmlns(sulu=http://schemas.sulu.io/template/template)xpointer(/sulu:properties/sulu:block/sulu:types/sulu:type)"/>

            <xi:include href="project-blocks/award.xml"
                        xpointer="xmlns(sulu=http://schemas.sulu.io/template/template)xpointer(/sulu:properties/sulu:block/sulu:types/sulu:type)"/>

            <xi:include href="project-blocks/job.xml"
                        xpointer="xmlns(sulu=http://schemas.sulu.io/template/template)xpointer(/sulu:properties/sulu:block/sulu:types/sulu:type)"/>

            <xi:include href="project-blocks/quote.xml"
                        xpointer="xmlns(sulu=http://schemas.sulu.io/template/template)xpointer(/sulu:properties/sulu:block/sulu:types/sulu:type)"/>

            <xi:include href="project-blocks/news.xml"
                        xpointer="xmlns(sulu=http://schemas.sulu.io/template/template)xpointer(/sulu:properties/sulu:block/sulu:types/sulu:type)"/>

        </types>
    </block>
</properties>
```

job.xml

```
<properties xmlns="http://schemas.sulu.io/template/template"
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:schemaLocation="http://schemas.sulu.io/template/template http://schemas.sulu.io/template/template-1.0.xsd">
    <block name="project-blocks" default-type="job">
        <types>
            <type name="job">
                <meta>
                    <title>app.job</title>
                </meta>

                <properties>
                    <property name="id" type="single_job_selection">
                        <meta>
                            <title>app.job</title>
                        </meta>
                    </property>
                </properties>
            </type>
        </types>
    </block>
</properties>

```

skill.xml
```

<properties xmlns="http://schemas.sulu.io/template/template"
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:schemaLocation="http://schemas.sulu.io/template/template http://schemas.sulu.io/template/template-1.0.xsd">
    <block name="project-blocks" default-type="skill">
        <types>
            <type name="skill">
                <meta>
                    <title>app.skill</title>
                </meta>

                <properties>
                    <property name="id" type="single_skill_selection">
                        <meta>
                            <title>app.projectSkill</title>
                        </meta>
                    </property>
                </properties>
            </type>
        </types>
    </block>
</properties>

```

I can post the other 3 xml files if needed

I am not quite sure if this a bug, or if I misconfigured something?

block-bug

### PR DESCRIPTION
**Pull request by danrot**
| Q | A
| --- | ---
| Bug fix? | yes
| New feature? | no
| BC breaks? | no
| Deprecations? | no
| Fixed tickets | fixes #5185 
| Related issues/PRs | ---
| License | MIT
| Documentation PR | ---

#### What's in this PR?

This PR avoids sending the internal `__id` from the blocks to the server. This sometimes introduced some problems, see e.g. #5185.
#### BC Breaks/Deprecations

Describe BC breaks/deprecations here. (remove this section if not needed)

#### To Do

- [x] Create a documentation PR
- [x] Add breaking changes to UPGRADE.md
- [x] Remove the `__id` property completely by removing the `SortableBlockList` component and integrate it into the `BlockCollection`

### CODE REVIEW

File: src/Sulu/Bundle/AdminBundle/Resources/js/components/BlockCollection/BlockCollection.js [hunk 1]
```diff
@@ -40,15 +41,20 @@ class BlockCollection extends React.Component<Props> {
...
-        const {expandedBlocks} = this;
+        const {expandedBlocks, generatedBlockIds} = this;
 
         if (!value) {
             return;
         }
 
         expandedBlocks.push(...new Array(value.length - expandedBlocks.length).fill(false));
+        generatedBlockIds.push(
+            ...new Array(value.length - generatedBlockIds.length).fill(false).map(() => ++BlockCollection.idCounter)
```
Comment (nnatter) [inline src/Sulu/Bundle/AdminBundle/Resources/js/components/BlockCollection/BlockCollection.js:52]: is the `.fill(false)` needed here?

File: src/Sulu/Bundle/AdminBundle/Resources/js/components/BlockCollection/SortableBlockList.js [hunk 2]
```diff
@@ -66,7 +67,7 @@ class SortableBlockList extends React.Component<Props> {
                         activeType={block.type}
                         expanded={!disabled && expandedBlocks[index]}
                         index={index}
-                        key={block.__id}
+                        key={generatedBlockIds[index]}
```
Comment (nnatter) [inline src/Sulu/Bundle/AdminBundle/Resources/js/components/BlockCollection/SortableBlockList.js:70]: i am curious - does this have any other effect than improved performance?

File: src/Sulu/Bundle/AdminBundle/Resources/js/components/BlockCollection/BlockCollection.js (hunk 1 above)
Comment (danrot) [reply src/Sulu/Bundle/AdminBundle/Resources/js/components/BlockCollection/BlockCollection.js:52]: Yes, `map` seems to skip entries if they are empty:

Screenshot from 2020-04-17 13-33-34

File: src/Sulu/Bundle/AdminBundle/Resources/js/components/BlockCollection/SortableBlockList.js (hunk 2 above)
Comment (danrot) [reply src/Sulu/Bundle/AdminBundle/Resources/js/components/BlockCollection/SortableBlockList.js:70]: Not even sure if it has better performance :see_no_evil: But yes, it has another impact. This way the generated ID, which is only necessary because we need a `key` for react, was previously sent to the server. And if the API stored this ID somehow on the serverside and returned it when loading the entity, it lead to the weird behavior described in #5185 (adding a new block when some of the blocks were reordered).

Comment (nnatter) [reply src/Sulu/Bundle/AdminBundle/Resources/js/components/BlockCollection/SortableBlockList.js:70]: yeah i know about the weird behaviour 🙂 i mean using a generated id for the`key` prop instead of just using the index of the array element?

File: src/Sulu/Bundle/AdminBundle/Resources/js/components/BlockCollection/BlockCollection.js (hunk 1 above)
Comment (nnatter) [reply src/Sulu/Bundle/AdminBundle/Resources/js/components/BlockCollection/BlockCollection.js:52]: okay this is interesting 🙂

File: src/Sulu/Bundle/AdminBundle/Resources/js/components/BlockCollection/BlockCollection.js [hunk 3]
```diff
@@ -40,15 +41,20 @@ class BlockCollection extends React.Component<Props> {
...
+        );
         if (minOccurs && value.length < minOccurs) {
             expandedBlocks.push(...new Array(minOccurs - value.length).fill(true));
+            generatedBlockIds.push(...new Array(minOccurs - value.length).map(() => ++BlockCollection.idCounter));
```
Comment (nnatter) [inline src/Sulu/Bundle/AdminBundle/Resources/js/components/BlockCollection/BlockCollection.js:56]: i guess you need to add a `.fill(false)` here too then?

File: src/Sulu/Bundle/AdminBundle/Resources/js/components/BlockCollection/SortableBlockList.js (hunk 2 above)
Comment (danrot) [reply src/Sulu/Bundle/AdminBundle/Resources/js/components/BlockCollection/SortableBlockList.js:70]: If you could use the `index` of the current element, then the `key` property in react would not make any sense at all :wink: 

If you use the `index` in that case sorting the elements does not work correctly.

File: src/Sulu/Bundle/AdminBundle/Resources/js/components/BlockCollection/BlockCollection.js (hunk 3 above)
Comment (danrot) [reply src/Sulu/Bundle/AdminBundle/Resources/js/components/BlockCollection/BlockCollection.js:56]: Right, going to add it.
