### PR TITLE
fixed resource locator adaption for pages with ghost-ancestors

### LINKED ISSUE #2709: publishing page produces exception when accessing unpublished child-page
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | dev-develop (01-08-2016)

#### Actual Behavior

1. Create an unpublished page _parent_
2. Create an unpublished page _child_ as child of the page _parent_
3. Publish the page _parent_

-> Accessing the page **/parent/child** in leads to an internal server error:

#### Expected Behavior

Accessing the page **/parent/child** should respond with "404 Not Found", as the child page is not published.

### PR DESCRIPTION
**Pull request by nnatter**
| Q | A
| --- | ---
| Bug fix? | yes
| New feature? | no
| BC breaks? | RlpStrategyInterface: generate-method changed, generateForUuid-method removed
| Deprecations? | no
| Fixed tickets | fixes #2709 
| Related issues/PRs | -
| License | MIT
| Documentation PR | -

#### What's in this PR?

This PR fixes various bugs which occured when changing the resource locator of a page with children.

The `adaptResourceLocators()`-method uses the `generate(`)-method of the `resource-locator-strategy` for adapting child resource locators now to improve consistency.

Also childs of unpublished pages and ghost pages are adapted now correct. Before this PR, the adapting-recursion stopped at ghost pages.

Route-nodes are only created, if a page is published now. Otherwise only the resource-locator of the document is changed to improve consistency in the frontend. This lead to internal server-errors, because route nodes were generated for unpublished pages.

The `generate()`-method of the `ResourceLocatorStrategyInterface` got adapted to use the parentUuid instead of the parentPath. 
This was neccessary to avoid duplicated code, because the parentPath must be extracted from the first published ancestor of a document to prevent unpublished resource segments.

This PR also contains rewritten unit-tests for the `TreeStrategy`-class with full method coverage and one additional functional test.

#### BC Breaks/Deprecations

The `generate` method of the `RlpStrategyInterface` uses `parentUuid` instead of `parentPath` now.

The signature changed from
`public function generate($title, $parentPath, $webspaceKey, $languageCode, $segmentKey = null);`
to
`public function generate($title, $parentUuid, $webspaceKey, $languageCode, $segmentKey = null);`

Also the `generateForUuid` method of the `RlpStrategyInterface` got removed.

### CODE REVIEW

File: src/Sulu/Bundle/DocumentManagerBundle/Bridge/DocumentInspector.php [hunk 1]
```diff
@@ -130,6 +131,23 @@ public function getMetadata($document)
...
 
     /**
+     * Returns the first ancestor-or-self of the given document which is published and therefore has an
+     * assigned resource locator. If all ancestor documents are unpublished, the root document is returned.
+     *
+     * @param object    $document
+     *
+     * @return object
+     */
+    public function getPublishedAncestorOrSelf($document)
```
Comment (danrot) [inline src/Sulu/Bundle/DocumentManagerBundle/Bridge/DocumentInspector.php]: I think I wouldn't add such a specific method to the `DocumentInspector`... Isn't there a better was to do this? E.g. moving the logic of finding the correct document to generate the route in the `RlpStrategy`?

**Comment by danrot** [comment]
To the number 2. in your PR description: Didn't we say that it should stay the way it were? Have you adapted that now?

**Comment by danrot** [comment]
Changelog missing

File: src/Sulu/Bundle/ContentBundle/Repository/ResourceLocatorRepository.php [hunk 2]
```diff
@@ -71,7 +75,8 @@ public function generate($parts, $parentUuid, $uuid, $webspaceKey, $languageCode
 
         if ($parentUuid !== null) {
             $parentDocument = $this->documentManager->find($parentUuid, $languageCode, ['load_ghost_content' => false]);
-            $parentPath = $this->rlpStrategy->loadByContent($this->getPublishedAncestorOrSelf($parentDocument));
+            $publishedAncestorDocument = $this->documentInspector->getPublishedAncestorOrSelf($parentDocument);
+            $parentPath = $this->rlpStrategy->loadByContent($publishedAncestorDocument);
             $result = $this->rlpStrategy->generate($title, $parentPath, $webspaceKey, $languageCode, $segmentKey);
```
Comment (danrot) [inline src/Sulu/Bundle/ContentBundle/Repository/ResourceLocatorRepository.php]: You could pass here the `$parentUuid` instead of the `$parentPath`,  and do the `DocumentManager::find` in the `generate` method.

File: src/Sulu/Bundle/DocumentManagerBundle/Tests/Unit/Bridge/DocumentInspectorTest.php [hunk 3]
```diff
@@ -157,6 +159,40 @@ public function testGetStructure()
...
+        $parent->getParent()->willReturn($grandParent->reveal());
+
+        $document = $this->prophesize(PageDocument::class);
+        $document->getPublished()->willReturn(false);
+        $document->getParent()->willReturn($parent->reveal());
+
+        $result = $this->documentInspector->getPublishedAncestorOrSelf($document->reveal());
+        $this->assertSame($grandParent->reveal(), $result);
+    }
+
```
Comment (danrot) [inline src/Sulu/Bundle/DocumentManagerBundle/Tests/Unit/Bridge/DocumentInspectorTest.php]: These lines should probably be removed now 😃

File: src/Sulu/Component/Content/Document/Subscriber/ResourceSegmentSubscriber.php [hunk 4]
```diff
@@ -98,7 +98,7 @@ public static function getSubscribedEvents()
             Events::HYDRATE => ['handleHydrate', -200],
             Events::MOVE => ['updateMovedDocument', -128],
             Events::COPY => ['updateCopiedDocument', -128],
-            Events::PUBLISH => 'handlePersistRoute',
+            Events::PUBLISH => ['handlePersistRoute', -128],
```
Comment (danrot) [inline src/Sulu/Component/Content/Document/Subscriber/ResourceSegmentSubscriber.php]: Why was this necessary?

File: src/Sulu/Component/Content/Types/Rlp/Strategy/RlpStrategy.php [hunk 5]
```diff
@@ -227,7 +258,8 @@ private function adaptResourceLocators(ResourceSegmentBehavior $document, $userI
 
             // build new resource segment based on parent changes
             $rlpParts = explode('/', $rlp);
-            $newRlp = $document->getResourceSegment() . '/' . $rlpParts[count($rlpParts) - 1];
+            $publishedAncestorDocument = $this->documentInspector->getPublishedAncestorOrSelf($document);
```
Comment (danrot) [inline src/Sulu/Component/Content/Types/Rlp/Strategy/RlpStrategy.php]: This method should not exist on the `DocumentManager` anymore.

File: src/Sulu/Component/Content/Document/Subscriber/ResourceSegmentSubscriber.php (hunk 4 above)
Comment (nnatter) [inline src/Sulu/Component/Content/Document/Subscriber/ResourceSegmentSubscriber.php]: because if a page gets published, the workflow-stage must be updated before the route is saved and therefore the children of the page get adapted.
otherwise, if the page was unpublished before, the children will ignore the resource locator of the parent because the parent lstates he is unpublished at that moment.

**Comment by danrot** [comment]
@nnatter Tests are failing

**Comment by nnatter** [comment]
@danrot: A lot of tests are failing, because `documentManager->find()` does not find the correct documents when calling with the resource-locator of the document.
Is it possible, that the documentManager cannot be used with resource-locators?

For example when trying to get the document for the resource-locator "/", the documentManager returns an UnknownDocument instead of the home-document.

**Comment by danrot** [comment]
@nnatter The `DocumentManager` can only load by UUID or path, and by path I mean the PHPCR path (e.g. `/cmf/sulu_io/contents` for the home document).

File: src/Sulu/Bundle/ContentBundle/Repository/ResourceLocatorRepository.php [hunk 6]
```diff
@@ -69,15 +55,10 @@ public function generate($parts, $parentUuid, $uuid, $webspaceKey, $languageCode
         $structure = $this->structureManager->getStructure($templateKey);
         $title = $this->implodeRlpParts($structure, $parts);
 
-        if ($parentUuid !== null) {
-            $parentDocument = $this->documentManager->find($parentUuid, $languageCode, ['load_ghost_content' => false]);
-            $parentPath = $this->rlpStrategy->loadByContent($this->getPublishedAncestorOrSelf($parentDocument));
-            $result = $this->rlpStrategy->generate($title, $parentPath, $webspaceKey, $languageCode, $segmentKey);
-        } elseif ($uuid !== null) {
+        if ($uuid !== null) {
```
Comment (danrot) [inline src/Sulu/Bundle/ContentBundle/Repository/ResourceLocatorRepository.php]: Why do we still need the `$parentUuid` and the `$uuid`? The page we are generating the URL for never has an own UUID, so I don't really get why we need two UUIDs...

File: src/Sulu/Component/Content/Document/Subscriber/ResourceSegmentSubscriber.php [hunk 7]
```diff
@@ -335,22 +328,22 @@ private function updateRoute($document, $generateRoutes)
...
+        $parentUuid,
         $webspaceKey,
         $locale
     ) {
         $childPart = $this->rlpStrategy->getChildPart($node->getPropertyValue($resourceSegmentPropertyName));
 
         $node->setProperty(
             $resourceSegmentPropertyName,
-            $this->rlpStrategy->generate($childPart, $parentPart, $webspaceKey, $locale)
+            $this->rlpStrategy->generate($childPart, $parentUuid, $webspaceKey, $locale)
```
Comment (danrot) [inline src/Sulu/Component/Content/Document/Subscriber/ResourceSegmentSubscriber.php]: This call doesn't match the method's signature. That's probably why it is so confusing fore me. Also see the comment https://github.com/sulu/sulu/pull/2706/files#r73859768.

File: src/Sulu/Component/Content/Types/Rlp/Strategy/RlpStrategy.php [hunk 8]
```diff
@@ -184,61 +221,42 @@ private function adaptResourceLocators(ResourceSegmentBehavior $document, $userI
         $webspaceKey = $this->documentInspector->getWebspace($document);
         $languageCode = $this->documentInspector->getLocale($document);
 
-        foreach ($document->getChildren() as $childDocument) {
-            $childNode = $this->documentInspector->getNode($childDocument);
-
-            // determine structure
-            $templatePropertyName = $this->nodeHelper->getTranslatedPropertyName('template', $languageCode);
+        $node = $this->documentInspector->getNode($document);
+        $node->getSession()->save();
```
Comment (danrot) [inline src/Sulu/Component/Content/Types/Rlp/Strategy/RlpStrategy.php]: This save wasn't there before, was it?

File: src/Sulu/Component/Content/Types/Rlp/Strategy/RlpStrategy.php [hunk 9]
```diff
@@ -184,61 +221,42 @@ private function adaptResourceLocators(ResourceSegmentBehavior $document, $userI
...
 
-            if (!$childNode->hasProperty($templatePropertyName)) {
+        foreach ($document->getChildren() as $childDocument) {
+            // skip documents without assigned resource segment
+            if (!$childDocument instanceof ResourceSegmentBehavior
+                || !$currentResourceLocator = $childDocument->getResourceSegment()) {
```
Comment (danrot) [inline src/Sulu/Component/Content/Types/Rlp/Strategy/RlpStrategy.php]: I wouldn't do the assignment for `$currentResourceLocator` in the if, that's quite hard to read. I think I would prefer the `adaptResourceLocators` call twice with the continue.

File: src/Sulu/Component/Content/Types/Rlp/Strategy/RlpStrategy.php [hunk 10]
```diff
@@ -184,61 +221,42 @@ private function adaptResourceLocators(ResourceSegmentBehavior $document, $userI
...
-
-            // determine structure
-            $templatePropertyName = $this->nodeHelper->getTranslatedPropertyName('template', $languageCode);
+        $node = $this->documentInspector->getNode($document);
+        $node->getSession()->save();
 
-            if (!$childNode->hasProperty($templatePropertyName)) {
+        foreach ($document->getChildren() as $childDocument) {
+            // skip documents without assigned resource segment
+            if (!$childDocument instanceof ResourceSegmentBehavior
```
Comment (danrot) [inline src/Sulu/Component/Content/Types/Rlp/Strategy/RlpStrategy.php]: Is this check needed at all? It wasn't there before, and it's the reason this if is so complicated.

File: src/Sulu/Component/Content/Types/Rlp/Strategy/RlpStrategy.php [hunk 11]
```diff
@@ -184,61 +221,42 @@ private function adaptResourceLocators(ResourceSegmentBehavior $document, $userI
...
+                || !$currentResourceLocator = $childDocument->getResourceSegment()) {
+                $this->adaptResourceLocators($childDocument, $userId);
                 continue;
             }
 
+            // build new resource segment based on parent changes
+            $parentUuid = $this->documentInspector->getUuid($document);
+            $childPart = $this->getChildPart($currentResourceLocator);
+            $newResourceLocator = $this->generate($childPart, $parentUuid, $webspaceKey, $languageCode);
```
Comment (danrot) [inline src/Sulu/Component/Content/Types/Rlp/Strategy/RlpStrategy.php]: I think the URL should not be generated? This means that the last part of the URL is not reused, right?

File: src/Sulu/Component/Content/Types/Rlp/Strategy/RlpStrategy.php [hunk 12]
```diff
@@ -184,61 +221,42 @@ private function adaptResourceLocators(ResourceSegmentBehavior $document, $userI
...
-                    $rlpPart,
-                    $parentRlp,
-                    $webspaceKey,
-                    $languageCode
-                );
-            }
-
-            // build new resource segment based on parent changes
-            $rlpParts = explode('/', $rlp);
-            $newRlp = $document->getResourceSegment() . '/' . $rlpParts[count($rlpParts) - 1];
```
Comment (danrot) [inline src/Sulu/Component/Content/Types/Rlp/Strategy/RlpStrategy.php]: That's the important part missing now, also see https://github.com/sulu/sulu/pull/2706/files#r73861675

File: src/Sulu/Bundle/ContentBundle/Serializer/Subscriber/ParentSubscriber.php [hunk 13]
```diff
@@ -0,0 +1,66 @@
...
+class ParentSubscriber implements EventSubscriberInterface
+{
+    /**
+     * @var DocumentInspector
+     */
+    private $documentInspector;
+
+    public function __construct(DocumentInspector $documentInspector)
+    {
+        $this->documentInspector = $documentInspector;
```
Comment (danrot) [inline src/Sulu/Bundle/ContentBundle/Serializer/Subscriber/ParentSubscriber.php]: Where do you need the `DocumentInspector` in this class?

File: src/Sulu/Component/Content/Types/Rlp/Strategy/RlpStrategy.php [hunk 14]
```diff
@@ -92,11 +101,20 @@ public function getName()
...
-    public function generate($title, $parentPath, $webspaceKey, $languageCode, $segmentKey = null)
+    public function generate($title, $parentUuid, $webspaceKey, $languageCode, $segmentKey = null)
     {
         // title should not have a slash
         $title = str_replace('/', '-', $title);
 
+        if ($parentUuid !== null) {
+            $parentDocument = $this->documentManager->find($parentUuid, $languageCode, ['load_ghost_content' => false]);
+            // using loadByContentUuid because loadByContent returns the wrong language for shadow-pages
+            $pathParentUuid = $this->documentInspector->getUuid($this->getPublishedAncestorOrSelf($parentDocument));
```
Comment (danrot) [inline src/Sulu/Component/Content/Types/Rlp/Strategy/RlpStrategy.php]: Why not `resolvedParentUuid`? I guess you are just doing this because the given `parentUuid` might lead to a page which is not published yet. Would add that as a comment, and rename the variable, since it has absolutely nothing to do with a path.
