### PR TITLE
fixed wrong parsing of webspace from path

### LINKED ISSUE #3008: content list is empty although there should be something in there.
| Q | A |
| --- | --- |
| Bug? | yes |
| New Feature? | no |
| Sulu Version | 1.3.0 |
| Browser Version | Chrome 54.0 |
| PHP | 7.0.11 |
#### Actual Behavior

Created pages are not shown in the content list.
bildschirmfoto 2016-10-29 um 00 34 49
but there are some
bildschirmfoto 2016-10-29 um 00 34 58

bildschirmfoto 2016-10-29 um 00 43 32
#### Expected Behavior

Created pages should be shown in the list.
#### Steps to Reproduce
- I just have a basic setup. (https://github.com/digitaleinitiativen/vorarlberg.digital) which is a copy of a sulu standard project.
- I clone the repository.
- I run `composer install`
- I run `bin/adminconsole sulu:build dev`
- I login
- I create a Default page
- For a short time it shows the page in the content overview.
- Then it disappears.
- The API call /admin/api/nodes/8caa6324-dc2d-47f3-940a-52c552030a2e?webspace=vorarlberg-digital&language=de&fields=title,order,published&exclude-ghosts=false&exclude-shadows=false&&tree=true returns an empty list.
- /admin/api/nodes/8caa6324-dc2d-47f3-940a-52c552030a2e?webspace=vorarlberg-digital&language=de&fields=title,order,published&exclude-ghosts=false&exclude-shadows=false& returns something.
#### Possible Solutions

I don't know.

### PR DESCRIPTION
**Pull request by danrot**
| Q | A
| --- | ---
| Bug fix? | yes
| New feature? | no
| BC breaks? | no
| Deprecations? | no
| Fixed tickets | fixes #3008, fixes sulu-standard#536
| Related issues/PRs | none
| License | MIT
| Documentation PR | none

#### What's in this PR?

This PR changes the Regex for returning the webspace from a path. Previously it only recognized the regex group `\w*` as webspace, which e.g. didn't include `-`.

### CODE REVIEW

File: src/Sulu/Component/Util/SuluNodeHelper.php [hunk 1]
```diff
@@ -164,7 +164,7 @@ public function hasSuluNodeType($node, $suluNodeTypes)
      */
     public function extractWebspaceFromPath($path)
     {
-        $match = preg_match('/^\/' . $this->getPath('base') . '\/(\w*)\/.*$/', $path, $matches);
+        $match = preg_match('/^\/' . $this->getPath('base') . '\/([^\/]*)\/.*$/', $path, $matches);
```
Comment (chirimoya) [inline src/Sulu/Component/Util/SuluNodeHelper.php]: whitespace support?

Comment (danrot) [inline src/Sulu/Component/Util/SuluNodeHelper.php]: Ok, looks like PHPCR somehow allows whitespaces in node names, but Sulu is not working correctly then, there are quite some requests failing.

But I think this is the wrong place to restrict that. I would prefer to leave the regex here like this, because I think it is not necessary that this component knows about it. The regex like this is the safest option.

Instead I would add  a validation for the webspace key in the XSD or the `XmlFileLoader` loading the XML. Otherwise the system would allow the "invalid" key to pass, and this method would not fail, but return wrong data.
