### PR TITLE
Fixed loading tree (with uuid) without webspace

### LINKED ISSUE #2954: Single Internal Link does not work in snippets
| Q | A |
| --- | --- |
| Bug? | yes |
| New Feature? | no |
| Sulu Version | 883dd4999d11134fb900f5e86b4a93bd21f51d4b |
| Browser Version | --- |
#### Actual Behavior

The `single_internal_link` content type does not work correctly if used in a snippet template.

It works as long there was no selection for the `single_internal_link`, because if you click on the blue button to assign a link a request to `admin/api/nodes?tree=true&language=en&webspace-node=true` is sent.

But if a page was already assigned it tries to load the path to this page, and sending a request like `admin/api/nodes?id=3970a897-cbff-4048-9810-5331838f20b5&tree=true&language=en&webspace-node=true`. The problem here is that it tries to load the UUID and append only the webspace the page is located in.

This happens because it looks like nobody thought about using the `single_internal_link` content type, which means that a `webspace` parameter is mandatory.
#### Expected Behavior

The `single_internal_link` overlay should be working as expected.
#### Steps to Reproduce

Use the following snippet definition:

``` xml
<?xml version="1.0" ?>

<template xmlns="http://schemas.sulu.io/template/template"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="http://schemas.sulu.io/template/template http://schemas.sulu.io/template/template-1.0.xsd">

    <key>default</key>

    <meta>
        <title lang="de">Standard</title>
        <title lang="en">Default</title>
    </meta>

    <properties>
        <property name="title" type="text_line" mandatory="true">
            <meta>
                <title lang="de">Titel</title>
                <title lang="en">Title</title>
            </meta>

            <tag name="sulu.node.name"/>
        </property>

        <property name="single_internal_link" type="single_internal_link">
            <meta>
                <title lang="de">Verlinkung</title>
                <title lang="en">Link</title>
            </meta>
        </property>
    </properties>
</template>
```
1. Create a new snippet of that type
2. Assign a page to the single internal link
3. Save the snippet
4. Reload and try to assign a new snippet
#### Possible Solutions

The `webspace` parameter should not be mandatory, and instead of a boolean flag `webspace-node` we should have the `webspace-nodes` parameter as in the other actions. This way we could could include all webspaces on the top level again, load the entire path, and merge these two arrays together.

The `webspace-node` property has not too many references: https://github.com/sulu/sulu/search?utf8=%E2%9C%93&q=webspace-node

The other possibility is to build something similar in a more complicated way to keep BC.

### PR DESCRIPTION
**Pull request by wachterjohannes**
| Q | A
| --- | ---
| Bug fix? | yes
| New feature? | no
| BC breaks? | no
| Deprecations? | no
| Fixed tickets | fixes #2954
| Related issues/PRs | none
| License | MIT
| Documentation PR | none

#### What's in this PR?

This PR fixes the ckeditor-link component in snippets. When selecting a page the overlay will crash because no webspaceKey was provided (because of snippets has no webspace)

### CODE REVIEW

**Comment by wachterjohannes** [comment]
i will test this also with single_internal_link

File: src/Sulu/Bundle/ContentBundle/Resources/public/js/components/single-internal-link/main.js [hunk 1]
```diff
@@ -185,46 +184,27 @@ define([], function() {
...
-                            showOptions: false,
-                            responsive: false,
-                            sortable: false,
-                            skin: 'fixed-height-small',
-                            disableIds: this.options.disabledIds,
-                            markable: true,
-                            singleMarkable: true
+                            instanceNamePrefix: '',
+                            showStatus: true,
+                            selectCallback: function(id) {
```
Comment (danrot) [inline src/Sulu/Bundle/ContentBundle/Resources/public/js/components/single-internal-link/main.js]: There is not a single id passed here, is it? Naming would be a bit confusing then.

File: src/Sulu/Bundle/ContentBundle/Resources/public/js/components/single-internal-link/main.js [hunk 2]
```diff
@@ -185,46 +184,27 @@ define([], function() {
...
                     {
-                        name: 'column-navigation@husky',
+                        name: 'content-datasource@sulucontent',
                         options: {
                             el: getId.call(this, 'columnNavigation'),
                             selected: this.data,
-                            url: url,
+                            selectedUrl: this.options.selectedUrl,
+                            rootUrl: this.options.rootUrl,
+                            resultKey: 'nodes',
```
Comment (danrot) [inline src/Sulu/Bundle/ContentBundle/Resources/public/js/components/single-internal-link/main.js]: Not available via options anymore?

File: src/Sulu/Bundle/ContentBundle/Resources/public/js/components/single-internal-link/main.js [hunk 3]
```diff
@@ -185,46 +184,27 @@ define([], function() {
         /**
          * initialize column navigation
          */
-        overlayOkCallback = function () {
```
Comment (danrot) [inline src/Sulu/Bundle/ContentBundle/Resources/public/js/components/single-internal-link/main.js]: You are actually not allowed to remove that code. We've worked quite some time to make the overlay consistent, and that included that also a click on the ok button is necessary on this overlay.

**Comment by danrot** [comment]
There are also some references to the `webspace-node` parameter left, couldn't you get rid of all of them? (i.e. https://github.com/wachterjohannes/sulu/blob/cedd8bbe1442613e71d010eaa4a4e305defd8f8b/src/Sulu/Bundle/ContentBundle/Controller/NodeController.php#L301 and https://github.com/wachterjohannes/sulu/blob/cedd8bbe1442613e71d010eaa4a4e305defd8f8b/src/Sulu/Bundle/ContentBundle/Repository/NodeRepository.php#L596)

**Comment by wachterjohannes** [comment]
@danrot i haven't touched this apis. i have used the api with `fields` parameter which alles the `webspace-nodes=all` parameter

File: src/Sulu/Bundle/ContentBundle/Resources/public/js/components/single-internal-link/main.js (hunk 1 above)
Comment (wachterjohannes) [inline src/Sulu/Bundle/ContentBundle/Resources/public/js/components/single-internal-link/main.js]: i am using the `content-datasource` here which gives me a single id when clicking on it.

File: src/Sulu/Bundle/ContentBundle/Resources/public/js/components/single-internal-link/main.js (hunk 2 above)
Comment (wachterjohannes) [inline src/Sulu/Bundle/ContentBundle/Resources/public/js/components/single-internal-link/main.js]: hmm https://github.com/massiveart/husky/blob/develop/husky_components/column-navigation/main.js#L709 here it will be used ...

File: src/Sulu/Bundle/ContentBundle/Resources/public/js/components/single-internal-link/main.js (hunk 3 above)
Comment (wachterjohannes) [inline src/Sulu/Bundle/ContentBundle/Resources/public/js/components/single-internal-link/main.js]: but it is quite strange when you select a single item and have to click on "OK"? @berndhep what do you think?

Comment (danrot) [inline src/Sulu/Bundle/ContentBundle/Resources/public/js/components/single-internal-link/main.js]: We have talked about this for some time, and this is the most consistent solution. And even if we would change it, it shouldn't be done in this PR.

File: src/Sulu/Bundle/ContentBundle/Resources/public/js/components/single-internal-link/main.js (hunk 2 above)
Comment (danrot) [inline src/Sulu/Bundle/ContentBundle/Resources/public/js/components/single-internal-link/main.js]: I mean previously there was a line like `resultKey: this.options.resultKey`, and now you are hardcoding the value.

File: src/Sulu/Bundle/ContentBundle/Resources/public/js/components/single-internal-link/main.js (hunk 1 above)
Comment (danrot) [inline src/Sulu/Bundle/ContentBundle/Resources/public/js/components/single-internal-link/main.js]: Ok, was confused by the `setData` call afterwards... But I think this should disappear anyway because of https://github.com/sulu/sulu/pull/3052/files#r91024733

**Comment by danrot** [comment]
Yeah, and as a result all the API calls with `webspace-node` are gone now. And we agreed in the [issue discussion](https://github.com/sulu/sulu/issues/2954#issuecomment-251118704) that the BC break in the API is ok, so I would also remove all of these parameters now. Otherwise we only have dead code lying around.

**Comment by wachterjohannes** [comment]
@danrot fixed overlay and removed the `webspace-node` parameter from api
