### PR TITLE
Remove url validation

### LINKED ISSUE #5681: Browser crashes on input of faulty, complex URL in URL Field within backend
| Q | A
| --- | ---
| Sulu Version | 2.1.5
| Browser Version | Chrome 87.0.4280.88 / Firefox 83.0

# Actual Behavior

When you enter a complex, faulty URL (e.g. `https://secret-secret-secret-secret-secret.secret-secret.com/de/publicservicedetail?q=elterngeld beantragen&id=8969217&organisationid=208445263` (the space character between "elterngeld" and "beantragen" being the fault)) in an URL input field within the backend, your browser crashes.

# Expected Behavior

no browser crashes

# Steps to Reproduce

- Log into the backend
- Have an URL input field
- Enter a faulty, complex URL (e.g. `https://secret-secret-secret-secret-secret.secret-secret.com/de/publicservicedetail?q=elterngeld beantragen&id=8969217&organisationid=208445263`)

# Possible Solutions

You can quick check the the behaviour here https://regexr.com/5hisv
Since this seems to be no sulu-specific bug, but a browser issue, I see only 2 options:
- optimize/simplify the Regex to work around the faulty JavaScript RegEx implementation
- Fix the JavaScript RegEx implementation

### PR DESCRIPTION
**Pull request by luca-rath**
| Q | A
| --- | ---
| Bug fix? | yes
| New feature? | no
| BC breaks? | no
| Deprecations? | no
| Fixed tickets | fixes #5681
| Related issues/PRs | -
| License | MIT
| Documentation PR | -

#### What's in this PR?

Remove url validation

### CODE REVIEW

File: src/Sulu/Bundle/AdminBundle/Resources/js/components/Url/Url.js [hunk 1]
```diff
@@ -20,15 +20,13 @@ type Props = {|
     value: ?string,
 |};
 
-// eslint-disable-next-line max-len
-const URL_REGEX = /^(?:(?:https?|ftps?):\/\/)(?:\S+(?::\S*)?@)?(?:(?!127(?:\.\d{1,3}){3})(?:[1-9]\d?|1\d\d|2[01]\d|22[0-3])(?:\.(?:1?\d{1,2}|2[0-4]\d|25[0-5])){2}(?:\.(?:[1-9]\d?|1\d\d|2[0-4]\d|25[0-4]))|(?:(?:[a-z\u00a1-\uffff0-9]+-?)*[a-z\u00a1-\uffff0-9]+)(?:\.(?:[a-z\u00a1-\uffff0-9]+-?)*[a-z\u00a1-\uffff0-9]+)*(?:\.(?:[a-z\u00a1-\uffff]{2,})))(?::\d{2,})?(?:\/[^\s]*)?$/iu;
-const URL_PROTOCOLS = ['http://', 'https://', 'ftp://', 'ftps://'];
+const URL_PROTOCOLS = ['http://', 'https://', 'ftp://', 'ftps://', 'mailto:', 'tel:'];
```
Comment (alexander-schranz) [inline src/Sulu/Bundle/AdminBundle/Resources/js/components/Url/Url.js]: maybe just call `PROTOCOLS` now or `DEFAULT_PROTOCOLS`?

**Review by alexander-schranz — CHANGES_REQUESTED** [review]
I would go with `DEFAULT_PROTOCOLS` instead of `URL_PROTOCOLS` because there could also be other protocols.

File: src/Sulu/Bundle/AdminBundle/Resources/js/components/Url/Url.js (hunk 1 above)
Comment (luca-rath) [reply src/Sulu/Bundle/AdminBundle/Resources/js/components/Url/Url.js]:
```suggestion
const DEFAULT_PROTOCOLS = ['http://', 'https://', 'ftp://', 'ftps://', 'mailto:', 'tel:'];
```

File: src/Sulu/Bundle/AdminBundle/Resources/js/components/Url/Url.js [hunk 2]
```diff
@@ -20,15 +20,13 @@ type Props = {|
...
 
 @observer
 class Url extends React.Component<Props> {
     static defaultProps = {
         disabled: false,
-        protocols: [...URL_PROTOCOLS, 'mailto:', 'tel:'],
+        protocols: URL_PROTOCOLS,
```
Comment (luca-rath) [inline src/Sulu/Bundle/AdminBundle/Resources/js/components/Url/Url.js]:
```suggestion
        protocols: DEFAULT_PROTOCOLS,
```

**Review by alexander-schranz — APPROVED** [review]

File: src/Sulu/Bundle/AdminBundle/Resources/js/components/Url/tests/Url.test.js [hunk 3]
```diff
@@ -140,7 +140,7 @@ test('Call onChange callback when path was changed but not blurred', () => {
     expect(changeSpy).toBeCalledWith('https://sulu.at');
 });
 
-test('Call onChange callback with undefined when path was changed to invalid url but not blurred', () => {
+test('Call onChange callback when path was changed to invalid url but not blurred', () => {
```
Comment (alexander-schranz) [inline src/Sulu/Bundle/AdminBundle/Resources/js/components/Url/tests/Url.test.js:143]: does this test make any sense as the url is I think from our case of view valid, or do I missunderstand and there is still a validation done?

File: src/Sulu/Bundle/AdminBundle/Resources/js/components/Url/tests/Url.test.js [hunk 4]
```diff
@@ -149,10 +149,10 @@ test('Call onChange callback with undefined when path was changed to invalid url
         },
     });
 
-    expect(changeSpy).toBeCalledWith(undefined);
+    expect(changeSpy).toBeCalledWith('https://sulu.a');
 });
 
-test('Call onChange callback with undefined if URL is not valid but leave the current value', () => {
+test('Call onChange callback if url is not valid but leave the current value', () => {
```
Comment (alexander-schranz) [inline src/Sulu/Bundle/AdminBundle/Resources/js/components/Url/tests/Url.test.js:155]: does this test make any sense as the url is I think from our case of view valid, or do I missunderstand and there is still a validation done?

File: src/Sulu/Bundle/AdminBundle/Resources/js/components/Url/tests/Url.test.js (hunk 3 above)
Comment (luca-rath) [reply src/Sulu/Bundle/AdminBundle/Resources/js/components/Url/tests/Url.test.js:143]: I just want to test, that the onChange callback is now be called with the actual url instead of `undefined` like it was before.

File: src/Sulu/Bundle/AdminBundle/Resources/js/components/Url/tests/Url.test.js (hunk 4 above)
Comment (luca-rath) [reply src/Sulu/Bundle/AdminBundle/Resources/js/components/Url/tests/Url.test.js:155]: I just want to test, that the onChange callback is now be called with the actual url instead of `undefined` like it was before.

**Review by niklasnatter — APPROVED** [review]
