### PR TITLE
fixed find-get-all of contact-repository

### LINKED ISSUE #2151: Warnings/Errors in findGetAll() of the contact repository
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | 1.1.10

Using ```findGetAll()``` (which is by the way a strange name, isn't it?) of ```Sulu\Bundle\ContactBundle\Entity\ContactRepository``` leads to a warning and to an error:

**Warning:**
The parameters of ```findGetAll()``` should be
```
public function findGetAll($limit = null, $offset = null, $sorting = [], $where = [])
```
instead of
```
public function findGetAll($limit = null, $offset = null, $sorting = null, $where = [])
```
as ```$sorting``` is expected to be an array in ```addSorting()```.

**Error:**
The join on account on line 276 leads to an error:
```[Semantical Error] line 0, col 303 near 'account LEFT': Error: Class Sulu\Bundle\ContactBundle\Entity\Contact has no association named account```

### PR DESCRIPTION
**Pull request by nnatter**
| Q | A
| --- | ---
| Bug fix? | yes
| New feature? | no
| BC breaks? | no
| Deprecations? | no
| Fixed tickets | fixes #2151 
| Related issues/PRs | -
| License | MIT
| Documentation PR | -

#### What's in this PR?

This PR fixes the warning and error which occured when using the `findGetAll()`-method of the `ContactRepository`-class by adjusting the signature of the method and selecting the correct joint-table.

Also tests for the `findGetAll()`-method are added.

### CODE REVIEW

**Comment by nnatter** [comment]
@danrot

File: src/Sulu/Bundle/ContactBundle/Entity/ContactRepository.php [hunk 1]
```diff
@@ -255,7 +255,8 @@ public function findGetAll($limit = null, $offset = null, $sorting = null, $wher
             ->leftJoin('u.faxes', 'faxes')
             ->leftJoin('u.contactAddresses', 'contactAddresses')
             ->leftJoin('contactAddresses.address', 'addresses')
-            ->leftJoin('u.account', 'account')
```
Comment (danrot) [inline src/Sulu/Bundle/ContactBundle/Entity/ContactRepository.php]: Didn't that work? Or why did you have to change this?

File: src/Sulu/Bundle/ContactBundle/Tests/Functional/Entity/ContactRepositoryTest.php [hunk 2]
```diff
@@ -510,11 +510,11 @@ public function findByIdsProvider()
...
-     * @dataProvider findByIdsProvider
-     *
-     * @param array $ids
-     * @param array $expected
-     */
+ * @dataProvider findByIdsProvider
+ *
+ * @param array $ids
+ * @param array $expected
+ */
```
Comment (danrot) [inline src/Sulu/Bundle/ContactBundle/Tests/Functional/Entity/ContactRepositoryTest.php]: Wrong indentation

File: src/Sulu/Bundle/ContactBundle/Entity/ContactRepository.php (hunk 1 above)
Comment (nnatter) [inline src/Sulu/Bundle/ContactBundle/Entity/ContactRepository.php]: @danrot: Yes, the line lead to the following error:
`[Semantical Error] line 0, col 303 near 'account LEFT': Error: Class Sulu\Bundle\ContactBundle\Entity\Contact has no association named account`

**Comment by danrot** [comment]
Looks good, will merge if tests are passing.
