### PR TITLE
Correct extension stripping

### LINKED ISSUE #3755: Using json by default (without url extension) results in 404 for articles
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | 1.6.14 

#### Actual Behavior

When using json as request format by default, without using .json extensions, the RouteProvider cuts off the last character of the url.

#### Expected Behavior

The RouteProvider should check if the extension exists, or only remove the actual extension.

#### Steps to Reproduce
When you set the request format in your project:

``` php
$request->setRequestFormat('json');
```
And visit a URL that should be routed by the RouteProvider, the page is not found.

### PR DESCRIPTION
**Pull request by jaapromijn**
The removal of the extension of formats should only take place when
the format is present as extension in the url. (#3755)

| Q | A
| --- | ---
| Bug fix? | yes
| New feature? | no
| BC breaks? | no
| Deprecations? | no
| Fixed tickets | fixes #3755
| Related issues/PRs | #3755
| License | MIT
| Documentation PR | sulu/sulu-docs#prnum

#### Why?

When using json as request format by default, without using .json extensions, the RouteProvider cut off the last character of the url, resulting in a 404.
In this PR, the stripping of the extension is only attempted if the format extension is present.

### CODE REVIEW

File: src/Sulu/Bundle/RouteBundle/Tests/Unit/Routing/RouteProviderTest.php [hunk 1]
```diff
@@ -354,4 +354,33 @@ public function testGetRouteCollectionForRequestEndingDot()
 
         $this->assertCount(0, $collection);
     }
+
+    public function testGetRouteCollectionForRequestWithoutFormatExtension()
+    {
+        $request = $this->prophesize(Request::class);
+        $request->getPathInfo()->willReturn('/de/test');
```
Comment (wachterjohannes) [inline src/Sulu/Bundle/RouteBundle/Tests/Unit/Routing/RouteProviderTest.php]: i think the reuqest will return `/de/test.json` in a real-world example? didn't it?

Comment (jaapromijn) [reply src/Sulu/Bundle/RouteBundle/Tests/Unit/Routing/RouteProviderTest.php]: The use case is actually requesting a JSON page without using the `.json` extension. 
The requested url for example is:
```
https://www.example.com/en/articles/foo-bar
```
And in my own request analyser the request format is set to json:
```
 $request->setRequestFormat('json');
```
So the path info should not return a path with a `.json` extension in this case? What you describe is already [covered in another test](https://github.com/jaapromijn/sulu/blob/146c7d27b5ddb9923088cbfda7a248d0a5fc2de2/src/Sulu/Bundle/RouteBundle/Tests/Unit/Routing/RouteProviderTest.php#L153), I think.

Comment (wachterjohannes) [reply src/Sulu/Bundle/RouteBundle/Tests/Unit/Routing/RouteProviderTest.php]: correct :) haven't recognized this - this PR is good! thanks for contribution

Comment (jaapromijn) [reply src/Sulu/Bundle/RouteBundle/Tests/Unit/Routing/RouteProviderTest.php]: 👍
