### PR TITLE
Fix purge search index on build

### LINKED ISSUE #4068: Sulu build with destroy does not purge search index
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | 1.6.20, 2.0.0-alpha1

#### Actual Behavior

Sulu build with destroy does not purge search index

#### Expected Behavior

`bin/console sulu:build dev --destroy` Should also purge the massive search indexes.

#### Steps to Reproduce

A page still exist in the index after running: `bin/console sulu:build dev --destroy`

#### Possible Solutions

Run also:

```
bin/adminconsole massive:search:purge --all --force
bin/websiteconsole massive:search:purge --all --force
```

We should target 2.5 branch for this.

### PR DESCRIPTION
**Pull request by draconivis**
| Q | A
| --- | ---
| Bug fix? | yes
| New feature? | no
| BC breaks? | no
| Deprecations? | no
| Fixed tickets | fixes #4068
| Related issues/PRs | -
| License | MIT
| Documentation PR | -

#### What's in this PR?

Adds an `InitBuilder` that purges the search indexes, if `sulu:build dev` is called with the `--destroy` flag

#### Why?

because of #4068 

#### Example Usage

```sh
bin/adminconsole sulu:build dev --destroy
```

#### To Do

- [ ] Create a documentation PR
- [ ] Add breaking changes to UPGRADE.md

### CODE REVIEW

**Review by alexander-schranz — APPROVED** [review]

**Comment by alexander-schranz** [comment]
@draconivis please check the linting errors.

File: src/Sulu/Bundle/SearchBundle/Build/InitBuilder.php [hunk 1]
```diff
@@ -31,7 +29,7 @@ public function getName(): string
     /**
      * Return the dependencies for this builder.
      *
-     * @return array
+     * @return array{}
```
Comment (alexander-schranz) [inline src/Sulu/Bundle/SearchBundle/Build/InitBuilder.php]:
```suggestion
     * @return array<string>
```

Comment (alexander-schranz) [reply src/Sulu/Bundle/SearchBundle/Build/InitBuilder.php]: best would be add this to:

https://github.com/massiveart/MassiveBuildBundle/blob/a62a69809e1d2b2267b1ae48bd35e994aae697e5/Build/BuilderInterface.php#L31

Comment (draconivis) [reply src/Sulu/Bundle/SearchBundle/Build/InitBuilder.php]: created a PR on the MassiveBuildBundle: https://github.com/massiveart/MassiveBuildBundle/pull/33

For now, i guess I'll just add the phpdoc? or should we update the build bundle?

**Review by alexander-schranz — APPROVED** [review]

File: src/Sulu/Bundle/SearchBundle/Build/InitBuilder.php (hunk 1 above)
Comment (alexander-schranz) [reply src/Sulu/Bundle/SearchBundle/Build/InitBuilder.php]: tagged it and updated the baseline
