### PR TITLE
Fix reference command for unpublished articles

### LINKED ISSUE #680: New sulu:reference:refresh command fails on unpublished articles
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| SuluArticleBundle Version | 2.6.0
| Sulu Version | 2.6.2
#### Actual Behavior

Running the new sulu:reference:refresh command fails when there are unpublished articles.

```bash
bin/websiteconsole sulu:reference:refresh

Refresh snippets
----------------

    2 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓]

Refresh pages
-------------

   16 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓]

Refresh articles
----------------

    2 [▓░░░░░░░░░░░░░░░░░░░░░░░░░░░]
In StructureManager.php line 69:

  Sulu\Component\Content\Compat\StructureManager::wrapStructure(): Argument #2 ($structure) must be of type Sulu\Component\Content\Metadata\StructureMetadata, null given, called
   in ../sulu-demo/vendor/sulu/sulu/src/Sulu/Component/Content/Compat/StructureManager.php on line 54

sulu:reference:refresh [<resource-key>]
```

#### Expected Behavior

Does not fail.

#### Steps to Reproduce

- Clone https://github.com/sulu/sulu-demo and follow the setup steps
- Upgrade to Sulu 2.6.2 and SuluArticleBundle 2.6.0 following the upgrade steps

Run
```bash
bin/adminconsole sulu:reference:refresh
bin/websiteconsole sulu:reference:refresh
```
It should work fine.

Now follow these steps:
- Create new article, then save and publish - above commands still work fine
- Now set the article to unpublished - above commands will fail (website context) with the error message as described before

#### Possible Solutions

- Should unpublished articles even be included in the refresh? If not, a check should be added.
- If yes, what should be done, because it looks some data is missing. I dumped the document and it doesn't even have a title.

### PR DESCRIPTION
**Pull request by Prokyonn**
| Q | A
| --- | ---
| Bug fix? |yes
| New feature? | no 
| BC breaks? | no
| Deprecations? | no 
| Fixed tickets | fixes https://github.com/sulu/SuluArticleBundle/issues/680
| Related issues/PRs | # 
| License | MIT
| Documentation PR | sulu/sulu-docs# 

#### What's in this PR?

see https://github.com/sulu/SuluArticleBundle/issues/680

#### To Do

- [ ] Create a documentation PR
- [ ] Add breaking changes to UPGRADE.md

### CODE REVIEW

**Review by alexander-schranz — APPROVED** [review]

File: src/Sulu/Bundle/DocumentManagerBundle/Reference/Provider/AbstractDocumentReferenceProvider.php [hunk 1]
```diff
@@ -75,6 +75,13 @@ public function updateReferences($document, string $locale, string $context): vo
         );
 
         $structure = $document->getStructure();
+
+        if ($document->getStructureType() === null) {
+            // if there is no structureType we cannot update the references
+            // this happens for pages/articles that were published once but have been unpublished
+            return;
+        }
```
Comment (alexander-schranz) [inline src/Sulu/Bundle/DocumentManagerBundle/Reference/Provider/AbstractDocumentReferenceProvider.php]: @Prokyonn possible to catch this in a functional test?

Comment (alexander-schranz) [reply src/Sulu/Bundle/DocumentManagerBundle/Reference/Provider/AbstractDocumentReferenceProvider.php]: Do we not need to still call `$referenceCollector->persistReferences();` to remove old references eventually, which may where not yet removed?

Comment (Prokyonn) [reply src/Sulu/Bundle/DocumentManagerBundle/Reference/Provider/AbstractDocumentReferenceProvider.php]: I'll have to check this

Comment (Prokyonn) [reply src/Sulu/Bundle/DocumentManagerBundle/Reference/Provider/AbstractDocumentReferenceProvider.php]: We do not need to remove them manually, when a page is unpublished they are removed automatically due to the `DocumentReferenceSubscriber` and when the refresh command is run, they are removed anyway because of the older timestamp see https://github.com/sulu/sulu/blob/2.6/src/Sulu/Bundle/ReferenceBundle/UserInterface/Command/RefreshCommand.php#L84-L88

File: src/Sulu/Bundle/PageBundle/Tests/Functional/Reference/Provider/PageReferenceProviderTest.php [hunk 2]
```diff
@@ -0,0 +1,125 @@
...
+        $this->documentManager->publish($page, 'en');
+        $this->documentManager->flush();
+
+        $this->documentManager->unpublish($page, 'en');
+        $this->documentManager->flush();
+        $this->documentManager->clear();
+
+        /** @var PageDocument $page */
+        $page = $this->documentManager->find($page->getUuid(), 'en');
+        $page->setStructureType(null);
```
Comment (Prokyonn) [inline src/Sulu/Bundle/PageBundle/Tests/Functional/Reference/Provider/PageReferenceProviderTest.php]: @alexander-schranz we have to set it here to `null` forcefully, otherwise I'm not sure how I can manage to get the `page` from the `website` context in a test 🤔

Comment (alexander-schranz) [reply src/Sulu/Bundle/PageBundle/Tests/Functional/Reference/Provider/PageReferenceProviderTest.php]: @Prokyonn theoretical you can boot the website kernel after you shutdown the admin kernel:

```php
        static::ensureKernelShutdown();
        $websiteKernel = static::bootKernel(['sulu.context' => SuluKernel::CONTEXT_WEBSITE]);
```

Comment (Prokyonn) [reply src/Sulu/Bundle/PageBundle/Tests/Functional/Reference/Provider/PageReferenceProviderTest.php]: Yep that worked, thank you 👍
