### PR TITLE
bugfix for firefox preview

### LINKED ISSUE #2446: Firefox: Preview is loaded twice, loader does not disappear
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | 587a07e3848e2bfa2ee09ea378517737d8cc9508
| Browser Version | Firefox 46.0.1

#### Actual Behavior

Preview is loaded twice and browser tab loader does not stop loading.

sulu-preview-twice

#### Expected Behavior

Preview should only be loaded once and browser tab loader should stop loading.

#### Steps to Reproduce

Load any page in the Sulu admin area.

### PR DESCRIPTION
**Pull request by marcelmoosbrugger**
| Q | A
| --- | ---
| Bug fix? | yes
| New feature? | no
| BC breaks? | no
| Deprecations? | no
| Fixed tickets | fixes #2446
| Related issues/PRs | none
| License | MIT
| Documentation PR | none

#### What's in this PR?

closing of the document after writing to it in the preview; clearing of the preview before again setting new content.

### CODE REVIEW

File: src/Sulu/Bundle/PreviewBundle/Resources/public/js/components/preview/main.js [hunk 1]
```diff
@@ -181,15 +181,16 @@ define([
         /**
          * Set content of preview document.
          *
-         * @param {String} html
+         * @param {String} htmlFile The html file including doctype etc.
          */
-        setContent: function(html) {
-            var document = this.getPreviewDocument();
+        setContent: function(htmlFile) {
+            var previewDoc = this.getPreviewDocument();
```
Comment (wachterjohannes) [inline src/Sulu/Bundle/PreviewBundle/Resources/public/js/components/preview/main.js]: don't use abbreviations `previewDocument`
