### PR TITLE
Fix refresh resource locator button

### LINKED ISSUE #5603: Refresh url button adds `-1` suffix to url if parts haven't changed
| Q | A
| --- | ---
| Sulu Version | 2.2.1
| Browser Version | Brave latest

# Actual Behavior

Bildschirmvideo-aufnehmen-2020-10-30-um-12 07 18

# Expected Behavior

If the refreshed url would be the same as the current url, a `-1` suffix should not be added to the url

# Steps to Reproduce

What are the steps to reproduce this bug? Please add code examples,
screenshots or links to GitHub repositories that reproduce the problem.

# Possible Solutions

Always send `id` (if available) as property of `parts` to the `ResourceLocatorController::postAction`, then the `ResourceLocatorStrategy` can check, if the found url belongs to the current page

### PR DESCRIPTION
**Pull request by luca-rath**
| Q | A
| --- | ---
| Bug fix? | yes
| New feature? | no
| BC breaks? | no
| Deprecations? | no
| Fixed tickets | fixes #5603
| Related issues/PRs | #issuenum
| License | MIT
| Documentation PR | sulu/sulu-docs#prnum

#### What's in this PR?

This pr changes the behaviour of the resource locator generation to consider, if a generated resource locator already exists for the exact same page

### CODE REVIEW

File: src/Sulu/Component/Content/Types/ResourceLocator/Mapper/ResourceLocatorMapperInterface.php [hunk 1]
```diff
@@ -104,7 +104,7 @@ public function unique($path, $webspaceKey, $languageCode, $segmentKey = null);
      *
      * @return string
      */
-    public function getUniquePath($path, $webspaceKey, $languageCode, $segmentKey = null);
+    public function getUniquePath($path, $webspaceKey, $languageCode, $segmentKey = null, $uuid = null);
```
Comment (alexander-schranz) [inline src/Sulu/Component/Content/Types/ResourceLocator/Mapper/ResourceLocatorMapperInterface.php:107]: Would not change this Interface

File: src/Sulu/Component/Content/Types/ResourceLocator/Strategy/ResourceLocatorStrategyInterface.php [hunk 2]
```diff
@@ -43,7 +43,7 @@ public function getChildPart($resourceSegment);
      *
      * @return string whole path
      */
-    public function generate($title, $parentUuid, $webspaceKey, $languageCode, $segmentKey = null);
+    public function generate($title, $parentUuid, $webspaceKey, $languageCode, $segmentKey = null, $uuid = null);
```
Comment (alexander-schranz) [inline src/Sulu/Component/Content/Types/ResourceLocator/Strategy/ResourceLocatorStrategyInterface.php:46]: Would not change this Interface

File: src/Sulu/Component/Content/Types/ResourceLocator/Mapper/PhpcrMapper.php [hunk 3]
```diff
@@ -290,11 +290,11 @@ public function unique($path, $webspaceKey, $languageCode, $segmentKey = null)
         return $this->isUnique($routes, $path);
     }
 
-    public function getUniquePath($path, $webspaceKey, $languageCode, $segmentKey = null)
+    public function getUniquePath($path, $webspaceKey, $languageCode, $segmentKey = null, $uuid = null)
     {
```
Comment (alexander-schranz) [inline src/Sulu/Component/Content/Types/ResourceLocator/Mapper/PhpcrMapper.php:294]: Instead of adding new parameter this should use something like here and throw a deprecation message:

https://github.com/sulu/sulu/blob/ddf5a0842807aa649c97bccf8245fe6e621d81cb/src/Sulu/Bundle/MediaBundle/Media/ImageConverter/MediaImageExtractor.php#L50-L61

File: src/Sulu/Component/Content/Types/ResourceLocator/Strategy/ResourceLocatorStrategy.php [hunk 4]
```diff
@@ -90,7 +90,7 @@ public function __construct(
         $this->resourceLocatorGenerator = $resourceLocatorGenerator;
     }
 
-    public function generate($title, $parentUuid, $webspaceKey, $languageCode, $segmentKey = null)
+    public function generate($title, $parentUuid, $webspaceKey, $languageCode, $segmentKey = null, $uuid = null)
```
Comment (alexander-schranz) [inline src/Sulu/Component/Content/Types/ResourceLocator/Strategy/ResourceLocatorStrategy.php:93]: Same as above should use something like here for BC promise: https://github.com/sulu/sulu/blob/ddf5a0842807aa649c97bccf8245fe6e621d81cb/src/Sulu/Bundle/MediaBundle/Media/ImageConverter/MediaImageExtractor.php#L50-L61

**Review by alexander-schranz — CHANGES_REQUESTED** [review]
For BC we should use the same as here:

https://github.com/sulu/sulu/blob/ddf5a0842807aa649c97bccf8245fe6e621d81cb/src/Sulu/Bundle/MediaBundle/Media/ImageConverter/MediaImageExtractor.php#L50-L61

**Comment by nnatter** [comment]
Have not looked at the code. Just a reminder to test https://github.com/sulu/sulu/issues/5363 when somebody reviews this 🙂

**Comment by luca-rath** [comment]
> Have not looked at the code. Just a reminder to test #5363 when somebody reviews this 🙂

this pr doesn't fix that issue. It would still append the url with `-1` if the generated url would result in a history url ... I didn't include it here, because I think that's a completely different issue.

**Review by nnatter — APPROVED** [review]
