### PR TITLE
Fix api if structure-type was removed or is not valid

### LINKED ISSUE #2101: Removed pages template should not crash content system
When you delete a xml template and a page still use this template you can not access the content area anymore.

> @danrot  The best solution would be to mark the page as broken in the content tree somehow.

We should also keep in mind that it could be broken only in one language.

### PR DESCRIPTION
**Pull request by wachterjohannes**
| Q | A
| --- | ---
| Bug fix? | yes
| New feature? | no
| BC breaks? | no
| Deprecations? | no
| Fixed tickets | fixes #2101
| Related issues/PRs | replaces #2139 , https://github.com/massiveart/husky/pull/758
| License | MIT
| Documentation PR | none

#### What's in this PR?

This PR introduces possibility that the structure of pages is null. This will lead into a stroke out title in column view and overlay that asks which template should be used for the page.

#### Why?

Currently if a structure definition file is missing, the admin interface will crash when showing the navigation tree.

This may happen during development, or possibly also when deploying to production where PHPCR nodes exist referring to broken templates.

#### TODO

- [x] Testcases
- [x] UI
- [x] Transaltions (fr, nl)

### CODE REVIEW

**Comment by wachterjohannes** [comment]
nl:

```
* Please contact system your administrator. = Bitte kontaktieren Sie ihren System-Administrator. > Neem contact op met de systeembeheerder
* Template name = Template Name > Templatenaam
```

File: src/Sulu/Component/Content/Repository/Content.php [hunk 1]
```diff
@@ -214,6 +228,48 @@ public function getNodeType()
...
+    {
+        return $this->template;
+    }
+
+    /**
+     * Set broken-template flag.
+     *
+     * @return $this
+     */
+    public function setBrokenTemplate()
```
Comment (danrot) [inline src/Sulu/Component/Content/Repository/Content.php]: Since the other setters in this class also take arguments I would do the same for this one.

File: src/Sulu/Component/Content/Repository/ContentRepository.php [hunk 2]
```diff
@@ -637,13 +637,17 @@ private function resolveContent(
             $this->resolvePath($row, $webspaceKey),
             $row->getValue('state'),
             $row->getValue('nodeType'),
-            $this->resolveHasChildren($row),
+            $this->resolveHasChildren($row), $this->resolveProperty($row, 'template', $locale, $shadowBase),
```
Comment (danrot) [inline src/Sulu/Component/Content/Repository/ContentRepository.php]: Put that into an own line.

File: src/Sulu/Component/Content/Repository/ContentRepository.php [hunk 3]
```diff
@@ -717,18 +721,24 @@ public function resolveInternalLinkContent(
...
-        return new Content(
+        $content = new Content(
             $locale,
             $webspaceKey,
             $row->getValue('uuid'),
             $this->resolvePath($row, $webspaceKey),
             $row->getValue('state'),
             $row->getValue('nodeType'),
-            $this->resolveHasChildren($row),
+            $this->resolveHasChildren($row), $this->resolveProperty($row, 'template', $locale),
```
Comment (danrot) [inline src/Sulu/Component/Content/Repository/ContentRepository.php]: Put that into an own line.

File: src/Sulu/Component/Content/Repository/ContentRepository.php [hunk 4]
```diff
@@ -717,18 +721,24 @@ public function resolveInternalLinkContent(
...
             $data,
             $this->resolvePermissions($row, $user),
             $type
         );
+
+        if (!$content->getTemplate() || !$this->structureManager->getStructure($content->getTemplate())) {
```
Comment (danrot) [inline src/Sulu/Component/Content/Repository/ContentRepository.php]: Looks like duplicated code, maybe put that into a private method?

**Comment by wachterjohannes** [comment]
@danrot fixed

File: src/Sulu/Bundle/ContentBundle/Resources/public/js/components/content/column/main.js [hunk 5]
```diff
@@ -45,18 +47,31 @@ define([
 
         ACTION_ICON_VIEW = 'fa-eye',
 
+        ACTION_ICON_INFO = 'fa-info',
+
+
+        brokenPageDialogTranslations = {
```
Comment (danrot) [inline src/Sulu/Bundle/ContentBundle/Resources/public/js/components/content/column/main.js]: Wouldn't it be a better idea to just name this `translations`? Then it would be consistent with the other components. And I am wondering why you are not using the hook you've developed some time ago.

Comment (wachterjohannes) [inline src/Sulu/Bundle/ContentBundle/Resources/public/js/components/content/column/main.js]: because its not used completelly in this file but your right i should use it anyway

**Comment by danrot** [comment]
I get the following error when opening the column navigation:

```
Error loading component: content/column@sulucontent TypeError: Cannot read property 'sandbox' of undefined
```

**Comment by wachterjohannes** [comment]
@danrot fixed with a rebase in husky
