### PR TITLE
Validate required fields in form blocks

### LINKED ISSUE #4629: Form mandatory validation should work within block
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | 2.0
| Browser Version | -

#### Actual Behavior

Form mandatory validation doesn't work within a block element.

#### Expected Behavior

Form validation should also work within a block element. The validation does work if the mandatory property is located in a normal form outside the block.

#### Steps to Reproduce

Add a block which contains at least one mandatory property and save the form afterwards in the browser.

```
<block name="receivers" default-type="to">
    <types>
        <type name="to">
            <properties>
                <property name="email" type="email" colspan="6" mandatory="true"/>     
            </properties>
        </type>
    </types>
</block>
```

### PR DESCRIPTION
**Pull request by danrot**
| Q | A
| --- | ---
| Bug fix? | yes
| New feature? | no
| BC breaks? | no
| Deprecations? | no
| Fixed tickets | fixes #4629
| Related issues/PRs | ---
| License | MIT
| Documentation PR | ---

#### What's in this PR?

This PR considers the block content type when generating the JSON schema for a form.

#### Why?

Because this way the validation for required fields will also work in blocks.

#### Example Usage

~~~xml
        <block name="blocks" default-type="text" minOccurs="0">
            <meta>
                <title lang="de">Text</title>
                <title lang="en">Text</title>
            </meta>
            <types>
                <type name="text">
                    <meta>
                        <title lang="de">Text</title>
                        <title lang="en">Text</title>
                    </meta>
                    <properties>
                        <property name="title" type="text_line" mandatory="true">
                            <meta>
                                <title lang="de">Title</title>
                                <title lang="en">Title</title>
                            </meta>
                        </property>
                        <property name="editor" type="text_editor" mandatory="true">
                            <meta>
                                <title lang="de">Article</title>
                                <title lang="en">Article</title>
                            </meta>
                        </property>
                    </properties>
                </type>
                <type name="image">
                    <meta>
                        <title lang="de">Text</title>
                        <title lang="en">Text</title>
                    </meta>
                    <properties>
                        <property name="title" type="text_line" mandatory="true">
                            <meta>
                                <title lang="de">Title</title>
                                <title lang="en">Title</title>
                            </meta>
                        </property>
                        <property name="image" type="media_selection" mandatory="true">
                            <meta>
                                <title lang="de">Image</title>
                                <title lang="en">Image</title>
                            </meta>
                        </property>
                    </properties>
                </type>
            </types>
        </block>
~~~

#### BC Breaks/Deprecations

To discuss

### CODE REVIEW

File: src/Sulu/Bundle/AdminBundle/Metadata/SchemaMetadata/PropertyMetadata.php [hunk 1]
```diff
@@ -11,49 +11,35 @@
 
 namespace Sulu\Bundle\AdminBundle\Metadata\SchemaMetadata;
 
-class PropertyMetadata
+class PropertyMetadata extends AbstractPropertyMetadata
```
Comment (danrot) [inline src/Sulu/Bundle/AdminBundle/Metadata/SchemaMetadata/PropertyMetadata.php]: @sulu/core-team If I would do that one again, I would probably name it `ConstMetadata`. Initially I thought having one `PropertyMetadata` will be enough, but then we might end up with a huge constructor when adding more stuff to validate. I've already had the `properties` from the `ArrayMetadata` added here as well, but I decided to split these two.

Question is if we should rename this class (I would suggest so), and if we introduce a BC layer (Creating a new class called `ConstMetadata` extending from this one, and deprected the `PropertyMetadata` class).

I would go for the deprecation, and if we do that, I would first get rid of all deprecations that currently have no alternative (if there is no alternative it should not be a deprecation) and configure our [ŧests to fail if we use some of our own deprecated code](https://symfony.com/doc/current/components/phpunit_bridge.html#internal-deprecations).

File: src/Sulu/Bundle/AdminBundle/FormMetadata/FormMetadataMapper.php [hunk 2]
```diff
@@ -203,6 +206,24 @@ private function mapSchemaProperties(array $itemsMetadata): array
...
+                }
+
+                return new ArrayMetadata(
+                    $itemMetadata->getName(),
+                    $itemMetadata->isRequired(),
+                    new SchemaMetadata([], $blockTypeSchemas)
+                );
+            }
+
             if (!$itemMetadata->isRequired()) {
```
Comment (nnatter) [inline src/Sulu/Bundle/AdminBundle/FormMetadata/FormMetadataMapper.php]: does it still make sense to return here? 🤔

File: src/Sulu/Bundle/AdminBundle/Metadata/SchemaMetadata/ConstMetadata.php [hunk 3]
```diff
@@ -0,0 +1,41 @@
...
+ */
+
+namespace Sulu\Bundle\AdminBundle\Metadata\SchemaMetadata;
+
+class ConstMetadata extends PropertyMetadata
+{
+    /**
+     * @var string|number|null
+     */
+    private $value;
```
Comment (nnatter) [inline src/Sulu/Bundle/AdminBundle/Metadata/SchemaMetadata/ConstMetadata.php]: does it make sense that this is nullable?

File: src/Sulu/Bundle/AdminBundle/Metadata/SchemaMetadata/PropertyMetadata.php [hunk 4]
```diff
@@ -47,13 +41,6 @@ public function isMandatory(): bool
...
     {
-        if (null === $this->value) {
-            return null;
-        }
-
-        return [
-            'name' => $this->name,
-            'const' => $this->value,
-        ];
+        return null;
```
Comment (nnatter) [inline src/Sulu/Bundle/AdminBundle/Metadata/SchemaMetadata/PropertyMetadata.php]: okay i dont know how this works tbh. but does this still have an effect if we return null here?

File: src/Sulu/Bundle/AdminBundle/Metadata/SchemaMetadata/ConstMetadata.php [hunk 5]
```diff
@@ -0,0 +1,41 @@
...
+ * This source file is subject to the MIT license that is bundled
+ * with this source code in the file LICENSE.
+ */
+
+namespace Sulu\Bundle\AdminBundle\Metadata\SchemaMetadata;
+
+class ConstMetadata extends PropertyMetadata
+{
+    /**
+     * @var string|number|null
```
Comment (alexander-schranz) [inline src/Sulu/Bundle/AdminBundle/Metadata/SchemaMetadata/ConstMetadata.php]: number?

File: src/Sulu/Bundle/AdminBundle/FormMetadata/FormMetadataMapper.php (hunk 2 above)
Comment (danrot) [reply src/Sulu/Bundle/AdminBundle/FormMetadata/FormMetadataMapper.php]: No, I think that is not necessary anymore :slightly_smiling_face:

File: src/Sulu/Bundle/AdminBundle/Metadata/SchemaMetadata/ConstMetadata.php (hunk 3 above)
Comment (danrot) [reply src/Sulu/Bundle/AdminBundle/Metadata/SchemaMetadata/ConstMetadata.php]: At first I thought you were right, but when thinking about it again I would leave it like this, but also return a schema if `null` is a returned. This way we could also say that a value has to be `null` (who knows if we need that one day?)

File: src/Sulu/Bundle/AdminBundle/Metadata/SchemaMetadata/PropertyMetadata.php (hunk 4 above)
Comment (danrot) [reply src/Sulu/Bundle/AdminBundle/Metadata/SchemaMetadata/PropertyMetadata.php]: The thing with JSON Schema is that if a field is required or not is not returned by the field itself, but by the schema it belongs to. We make use of this in the [`SchemaMetadata`](https://github.com/sulu/sulu/blob/d5d841b/src/Sulu/Bundle/AdminBundle/Metadata/SchemaMetadata/SchemaMetadata.php#L47)

File: src/Sulu/Bundle/AdminBundle/Metadata/SchemaMetadata/ConstMetadata.php (hunk 5 above)
Comment (danrot) [reply src/Sulu/Bundle/AdminBundle/Metadata/SchemaMetadata/ConstMetadata.php]: What do you want to say by that? A field in a form can return about anything, so we should at least cover these two (I don't imagine right now that people are using this in combination with objects as well).

File: src/Sulu/Bundle/AdminBundle/Metadata/SchemaMetadata/ConstMetadata.php (hunk 3 above)
Comment (danrot) [reply src/Sulu/Bundle/AdminBundle/Metadata/SchemaMetadata/ConstMetadata.php]: Although what I've just described is not working because if I remove the null check in the `toJsonSchema` method of this class, then all the assigned properties say that `null` is their constant value, and the validation fails for a lot :see_no_evil: I would leave it like it is at the moment.

Comment (nnatter) [reply src/Sulu/Bundle/AdminBundle/Metadata/SchemaMetadata/ConstMetadata.php]: yeah returning a schema in the case of `null` it makes sense 🙂

File: src/Sulu/Bundle/AdminBundle/Metadata/SchemaMetadata/PropertyMetadata.php (hunk 4 above)
Comment (nnatter) [reply src/Sulu/Bundle/AdminBundle/Metadata/SchemaMetadata/PropertyMetadata.php]: 👍

File: src/Sulu/Bundle/AdminBundle/Metadata/SchemaMetadata/ConstMetadata.php (hunk 5 above)
Comment (alexander-schranz) [reply src/Sulu/Bundle/AdminBundle/Metadata/SchemaMetadata/ConstMetadata.php]: Number does not exist as type in PHP. https://docs.phpdoc.org/guides/types.html
PHP only know about int|float
