### PR TITLE
Fixed smart-content out of range

### LINKED ISSUE #3388: Component/SmartContent pagination issues
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | 1.5.3
| Browser Version | -

#### Actual Behavior

https://github.com/sulu/sulu/blob/develop/src/Sulu/Component/SmartContent/ContentType.php#L383-L392

`IF $page < 1 OR $page > PHP_INT_MAX` :

vendor/doctrine/dbal/lib/Doctrine/DBAL/Platforms/AbstractPlatform.php at line 3318
```php
 if ($offset < 0) {
    throw new DBALException("LIMIT argument offset=$offset is not valid");
}
```
#### Expected Behavior

work without errors

#### Steps to Reproduce

compose page using the doc: http://docs.sulu.io/en/latest/reference/content-types/smart_content.html
and set p=0 or p=99999999999999999999 in HTTP request

#### Possible Solutions

check $page value has in allowed range [1, PHP_INT_MAX] (or simply $page > 0)

### PR DESCRIPTION
**Pull request by wachterjohannes**
| Q | A
| --- | ---
| Bug fix? | yes
| New feature? | no
| BC breaks? | no
| Deprecations? | no
| Fixed tickets | fixes #3388
| Related issues/PRs | none
| License | MIT
| Documentation PR | none

#### What's in this PR?

This PR fixes a bug when passing invalid values for current page over request to smart-content.

#### Why?

If you pass `$page < 1 || $page > PHP_INT_MAX` to smart-content doctrine throws exception later on.

### CODE REVIEW

File: src/Sulu/Component/SmartContent/ContentType.php [hunk 1]
```diff
@@ -382,13 +382,18 @@ private function getProvider(PropertyInterface $property)
...
-        if ($this->requestStack->getCurrentRequest() !== null) {
-            $page = $this->requestStack->getCurrentRequest()->get($pageParameter, 1);
-        } else {
-            $page = 1;
+        if ($this->requestStack->getCurrentRequest() === null) {
+            return 1;
+        }
+
+        $page = $this->requestStack->getCurrentRequest()->get($pageParameter, 1);
+        if ($page < 1) {
```
Comment (wachterjohannes) [inline src/Sulu/Component/SmartContent/ContentType.php]: another way would be to throw an exception in these cases. but then we would have 500 on the website.

Comment (danrot) [inline src/Sulu/Component/SmartContent/ContentType.php]: Or it could be translated to a 400? Wouldn't that be a better solution? Maybe we should also ask Jens about this. / @chirimoya

Comment (wachterjohannes) [inline src/Sulu/Component/SmartContent/ContentType.php]: do you think this error-avoiding solution isnt a good idea?

Comment (chirimoya) [inline src/Sulu/Component/SmartContent/ContentType.php]: I think a 404 error would be the correct solution. Else you display "wrong" content on a "invalid" url and this could lead to duplicate content.

Comment (danrot) [inline src/Sulu/Component/SmartContent/ContentType.php]: I start to think that avoiding (or better say ignoring) errors is more often a bad than a good idea 🙈

**Comment by wachterjohannes** [comment]
@danrot fixed

File: src/Sulu/Bundle/ContentBundle/DependencyInjection/SuluContentExtension.php [hunk 2]
```diff
@@ -85,7 +87,8 @@ public function prepend(ContainerBuilder $container)
                 [
                     'exception' => [
                         'codes' => [
-                            'Sulu\Component\Content\Exception\ResourceLocatorAlreadyExistsException' => 409,
+                            ResourceLocatorAlreadyExistsException::class => 409,
+                            PageOutOfBoundsException::class => 409,
```
Comment (danrot) [inline src/Sulu/Bundle/ContentBundle/DependencyInjection/SuluContentExtension.php]: Haven't we said that should be a 404?

File: src/Sulu/Component/SmartContent/ContentType.php [hunk 3]
```diff
@@ -379,16 +380,21 @@ private function getProvider(PropertyInterface $property)
...
-        if ($this->requestStack->getCurrentRequest() !== null) {
-            $page = $this->requestStack->getCurrentRequest()->get($pageParameter, 1);
-        } else {
-            $page = 1;
+        if ($this->requestStack->getCurrentRequest() === null) {
+            return 1;
+        }
+
+        $page = $this->requestStack->getCurrentRequest()->get($pageParameter, 1);
+        if ($page < 1 || $page > PHP_INT_MAX) {
```
Comment (danrot) [inline src/Sulu/Component/SmartContent/ContentType.php]: Do you know how many real pages there are? I think there should already be a 404 if page 3 was requested although only 2 pages exist.

File: src/Sulu/Bundle/ContentBundle/DependencyInjection/SuluContentExtension.php (hunk 2 above)
Comment (wachterjohannes) [inline src/Sulu/Bundle/ContentBundle/DependencyInjection/SuluContentExtension.php]: oh (: copy paste error!

File: src/Sulu/Component/SmartContent/ContentType.php (hunk 3 above)
Comment (wachterjohannes) [inline src/Sulu/Component/SmartContent/ContentType.php]: no we dont know without additional query (and loading all the documents). this is also the reason why we only provide a `hasNextPage` flag.

**Comment by wachterjohannes** [comment]
@danrot fixed

File: src/Sulu/Component/SmartContent/ContentType.php (hunk 3 above)
Comment (danrot) [inline src/Sulu/Component/SmartContent/ContentType.php]: Hm... but we could throw the same exception where the items are loaded, in case `$page > 0 && count($pages) < 1`?

Comment (wachterjohannes) [inline src/Sulu/Component/SmartContent/ContentType.php]: that would be a BC break in my opinion - because if someone uses the smart-content without checking for `hasNextPage` it would throw an exception now. @chirimoya what do you think?

Comment (danrot) [inline src/Sulu/Component/SmartContent/ContentType.php]: I think it's better to have a 404 page instead of duplicated content 🙈

**Comment by wachterjohannes** [comment]
@danrot fixed
