### PR TITLE
make redirects for all routes to circumvent double slash problem

### LINKED ISSUE #2562: RequestAnalyzer error on wrong url
| Q | A |
| --- | --- |
| Bug? | yes |
| New Feature? | no |
| Sulu Version | 1.2 |
#### Actual Behavior

if you go add two dashes on the url after the domain on a non-existent url in PROD: http://www.something.com//fr/asdasd

You get the following error:
www_asdsadasda_con__fr_asasdda

### LINKED ISSUE #3020: Redirect for trailing slash goes always to default language
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | Specific version or SHA of a commit
| Browser Version | Browser name and version

#### Actual Behavior

When you have a webspace with `de` and `en` as language, `en` being the default language, the redirects with the trailing slash will always go to the default language. So if you go to `example.org/de/test/` it will redirect to `example.org/en/test`.

#### Expected Behavior

`example.org/de/test/` should redirect to `example.org/de/test`.

#### Steps to Reproduce

1. Create a page with the url `de/test`
2. Surf to `de/test/`
3. You get redirected to `en/test``

### PR DESCRIPTION
**Pull request by danrot**
| Q | A
| --- | ---
| Bug fix? | yes
| New feature? | no
| BC breaks? | no
| Deprecations? | no
| Fixed tickets | fixes #2562, fixes #3020 
| Related issues/PRs | none
| License | MIT
| Documentation PR | none

#### What's in this PR?

This PR changes the redirect to match all routes. This is necessary because of [Symfony trims routes](https://github.com/sulu/sulu/issues/2562#issuecomment-259144408).

#### BC Breaks/Deprecations

The route returned when a redirect is happening changed to a more general format. Hopefully other applications haven't been relying on that exact return value.

### CODE REVIEW

File: src/Sulu/Bundle/WebsiteBundle/Routing/ContentRouteProvider.php [hunk 1]
```diff
@@ -306,11 +304,16 @@ protected function getRedirectWebSpaceRoute(Request $request)
...
-            $request->getPathInfo(), [
+            '/{wildcard}',
+            [
                 '_controller' => 'SuluWebsiteBundle:Redirect:redirectWebspace',
                 'url' => $this->requestAnalyzer->getPortalUrl(),
                 'redirect' => $redirect,
+            ],
+            [
+                'wildcard' => '.*',
             ]
```
Comment (danrot) [inline src/Sulu/Bundle/WebsiteBundle/Routing/ContentRouteProvider.php]: @wachterjohannes What do you think about that? The only solution I found to the problem explained in https://github.com/sulu/sulu/issues/2562#issuecomment-259144408
