### PR TITLE
Fix filtering of snippets when choosing snippet areas

### LINKED ISSUE #5311: Default snippet selection overlay ignores snippet type
| Q | A
| --- | ---
| Sulu Version | 2.0.7

# Actual Behavior

When I want to select the default snippet for a specific type/area, the overlay contains all snippets regardless of their type. When I select a snippet of the wrong type, the administration interface crashes.

current behaviour

# Expected Behavior

The overlay should only contain snippets that are allowed for the type/area.

### PR DESCRIPTION
**Pull request by danrot**
| Q | A
| --- | ---
| Bug fix? | yes
| New feature? | no
| BC breaks? | no
| Deprecations? | no
| Fixed tickets | fixes #5311 
| Related issues/PRs | ---
| License | MIT
| Documentation PR | ---

#### What's in this PR?

This PR fixes the name of the query parameter used for filtering snippet areas.

### CODE REVIEW

**Comment by danrot** [comment]
@nnatter There was another flaky test, that only failed if the entire test suite was ran, not only the tests of the SnippetBundle :see_no_evil: Now it should be working, you can already have a look at it :slightly_smiling_face:

File: src/Sulu/Bundle/TestBundle/Testing/TestUserProvider.php [hunk 1]
```diff
@@ -87,14 +87,16 @@ public function getUser()
...
             $user = $this->userRepository->createNew();
-            $this->setCredentials($user);
-            $user->setLocale('en');
             $user->setContact($contact);
             $this->entityManager->persist($user);
-        } else {
-            $this->setCredentials($user);
         }
 
+        $user->setUsername(self::TEST_USER_USERNAME);
```
Comment (nnatter) [inline src/Sulu/Bundle/TestBundle/Testing/TestUserProvider.php:94]: no sure if you commited this on purpose?

Comment (danrot) [reply src/Sulu/Bundle/TestBundle/Testing/TestUserProvider.php:94]: I did, this is the fix for [this error](https://travis-ci.org/github/sulu/sulu/jobs/694915779#L1757).

It especially is about the `setLocale` below. One of the tests of the SecurityBundle sets the locale to another language, and it will stay like that for all tests afterwards. For this reason the tests were failing if all tests are executed, but not if only the SnippetBundle tests were executed.

File: src/Sulu/Bundle/TestBundle/Testing/TestUserProvider.php [hunk 2]
```diff
@@ -163,9 +165,5 @@ public function supportsClass($class)
      */
     private function setCredentials(UserInterface $user)
```
Comment (danrot) [inline src/Sulu/Bundle/TestBundle/Testing/TestUserProvider.php:166]: But then I should also delete this function completely :see_no_evil: Already on it!
