### PR TITLE
Fix indexing of single_media_selection

### LINKED ISSUE #5320: Image search field not working for single_media_selection
| Q | A
| --- | ---
| Sulu Version | 2.1.0-RC1

# Actual Behavior

How does Sulu behave at the moment? 
`bin/websiteconsole massive:search:reinde`
image

# Expected Behavior

Use the id of the `single_media_selections` instead of the ids.

# Steps to Reproduce

Add `<tag name="sulu.search.field" role="image" index="false" />` to a `single_media_selection` and run `bin/websiteconsole massive:search:reinde`

### PR DESCRIPTION
**Pull request by danrot**
| Q | A
| --- | ---
| Bug fix? | yes
| New feature? | no
| BC breaks? | no
| Deprecations? | no
| Fixed tickets | fixes #5320 
| Related issues/PRs | ---
| License | MIT
| Documentation PR | ---

#### What's in this PR?

This PR fixes the search indexing of `single_media_selection` fields on pages.

### CODE REVIEW

File: src/Sulu/Bundle/MediaBundle/Search/Subscriber/StructureMediaSearchSubscriber.php [hunk 1]
```diff
@@ -118,14 +118,13 @@ private function getImageUrl($data, $locale)
             $medias = $data->getData('de');
         // old ones an array ...
         } else {
-            if (!isset($data['ids'])) {
-                throw new \RuntimeException(
-                    \sprintf('Was expecting media value to contain array key "ids", got: "%s"', \print_r($data, true))
-                );
+            $ids = $data['ids'] ?? $data['id'] ?? null;
```
Comment (alexander-schranz) [inline src/Sulu/Bundle/MediaBundle/Search/Subscriber/StructureMediaSearchSubscriber.php:121]: Will `$data['id']` not return an int and so !is_array will always fail?

Comment (danrot) [reply src/Sulu/Bundle/MediaBundle/Search/Subscriber/StructureMediaSearchSubscriber.php:121]: Just realized that as well :sweat_smile: Already working on it

**Comment by danrot** [comment]
@alexander-schranz Now it should be OK :slightly_smiling_face: Wanna have a look?
