### PR TITLE
Fixing pubic flysystem urls

### LINKED ISSUE #7957: Flysystem S3 redirect (Sulu 3)
| Q | A
| --- | ---
| Sulu Version | Sulu 3 alpha 2
| PHP Version | 8.3
| DB Version | MariaDB 10.9
| Browser Version | Chrome 136

# Actual Behavior

Opening a version of a file which is hosted on S3 throws an error "The file does not exist".

# Possible Solution
I think there is a missing redirection to the `public_url` that is defined in `flysystem.yaml`

### PR DESCRIPTION
**Pull request by mamazu**
| Q | A
| --- | ---
| Bug fix? | yes
| New feature? | no
| BC breaks? | no
| Deprecations? | no
| Fixed tickets | fixes #7957 
| Related issues/PRs | -
| License | MIT
| Documentation PR | -

#### What's in this PR?
Adding the call to the public url for remote services.

#### Why?
Otherwise generating the public url will no longer work.

Thanks to @hual7 for helping with S3 credentials.

### CODE REVIEW

**Review by alexander-schranz — APPROVED** [review]

File: src/Sulu/Bundle/MediaBundle/Media/Storage/FlysystemStorage.php [hunk 1]
```diff
@@ -171,7 +171,7 @@ private function createDirectories(array $storageOptions): void
     public function getPath(array $storageOptions): string
     {
         if (null === $this->rootPath) {
-            return $this->getFilePath($storageOptions);
+            return $this->filesystem->publicUrl($this->getFilePath($storageOptions));
```
Comment (alexander-schranz) [inline src/Sulu/Bundle/MediaBundle/Media/Storage/FlysystemStorage.php:175]: Local adapter need to return sti the path See 2.6

Comment (mamazu) [reply src/Sulu/Bundle/MediaBundle/Media/Storage/FlysystemStorage.php:175]: Okay there are now three cases: remote, local, local with root path.

**Review by alexander-schranz — APPROVED** [review]
