### PR TITLE
Fix articles_page_tree provider to support includeSubFolders filter

### LINKED ISSUE #8699: Sulu 3: Smart content provider articles_page_tree does not return results from subpages
| Q | A
| --- | ---
| Sulu Version | 3.0.4
| PHP Version | 8.4.16
| DB Version | mariadb-10.7.6
| Browser Version | Chrome 146

# Actual Behavior

The smart content provider articles_page_tree is not returning any results when articles are associated to subpages of the page containing the smart content property, even when the “Include sub folders” toggle is enabled.
Currently, the provider only returns articles that are directly associated with the page where the smart content is used. Articles placed in child pages are ignored, which makes the “Include sub folders” option appear non‑functional.

# Expected Behavior

When “Include sub folders” is enabled, the provider should retrieve articles associated with the current page and all of its descendant pages.

# Steps to Reproduce

1. Create a page with a smart content property using the articles_page_tree provider.
2. Enable “Include sub folders.”
3. Create an article with an URL of type 'page_tree_route' and set its parents page to a subpage of the page containing the smart content.
4. View the page.

Image
Image
Image
Image

### PR DESCRIPTION
**Pull request by Amoifr**
| Q | A
| --- | ---
| Bug fix? | yes
| New feature? | no
| BC breaks? | no
| Deprecations? | no
| Fixed tickets | fixes #8699
| Related issues/PRs | 
| License | MIT
| Documentation PR | 

#### What's in this PR?

This PR adds support for the `includeSubFolders` filter in the `articles_page_tree` SmartContent provider.

**Changes:**
- Modified `PageTreeArticleSmartContentProvider::addInternalFilters()` to handle the `includeSubFolders` filter
- When `includeSubFolders` is `false`: only articles directly linked to the datasource page are returned (existing behavior)
- When `includeSubFolders` is `true`: articles linked to the datasource page **and all its descendant pages** are returned using the nested set model (`lft`/`rgt`)

**Tests added:**
- Created child pages (`blog_tech`, `blog_tech_ai`) with their associated articles
- `testFindFlatByWithIncludeSubFoldersDisabled()` - verifies only direct articles are returned
- `testFindFlatByWithIncludeSubFoldersEnabled()` - verifies articles from all descendant pages are included
- `testFindFlatByWithIncludeSubFoldersFromChildPage()` - verifies nested hierarchy works correctly
- `testCountByWithIncludeSubFoldersEnabled/Disabled()` - verifies count respects the filter

#### Why?

The `articles_page_tree` SmartContent provider was not respecting the "Include sub folders" toggle in the admin UI. When enabled, articles associated with subpages of the selected datasource page were not being returned, making the toggle appear non-functional.

#### Example Usage

```twig
{# In a template with smart_content using articles_page_tree provider #}
{# When "Include sub folders" is enabled, articles from /blog, /blog/tech, /blog/tech/ai will all be returned #}
{% for article in content.articles %}
    <h2>{{ article.title }}</h2>
{% endfor %}
```

#### To Do

- [ ] ~Create a documentation PR~ (no documentation changes needed)
- [x] ~Add breaking changes to UPGRADE.md~ (no breaking changes)

### CODE REVIEW

File: packages/article/src/Infrastructure/Sulu/Content/PageTreeArticleSmartContentProvider.php [hunk 1]
```diff
@@ -84,8 +86,29 @@ protected function addInternalFilters(QueryBuilder $queryBuilder, array $filters
         $queryBuilder->setParameter('routeLocale', $locale);
 
         $queryBuilder->join('articleRoute.parentRoute', 'parentRoute');
-        $queryBuilder->andWhere('parentRoute.resourceId = :dataSource');
-        $queryBuilder->setParameter('dataSource', $dataSource);
+
+        if (!$includeSubFolders) {
+            // Only match articles whose parent route points directly to the dataSource page
```
Comment (Prokyonn) [inline packages/article/src/Infrastructure/Sulu/Content/PageTreeArticleSmartContentProvider.php]:
```suggestion
```

File: packages/article/src/Infrastructure/Sulu/Content/PageTreeArticleSmartContentProvider.php [hunk 2]
```diff
@@ -84,8 +86,29 @@ protected function addInternalFilters(QueryBuilder $queryBuilder, array $filters
...
+            $queryBuilder->andWhere('parentRoute.resourceId = :dataSource');
+            $queryBuilder->setParameter('dataSource', $dataSource);
+        } else {
+            // Match articles whose parent route points to the dataSource page or any of its descendants
+            // Using the nested set model (lft/rgt) of Page to efficiently query descendants
```
Comment (Prokyonn) [inline packages/article/src/Infrastructure/Sulu/Content/PageTreeArticleSmartContentProvider.php]:
```suggestion
```

**Comment by Prokyonn** [comment]
Looks good, thank you for this contribution @Amoifr !

I think we can remove those two comments as they are self-explanatory :)

**Review by Prokyonn — APPROVED** [review]
