### PR TITLE
Using Website-Kernel to render preview

### LINKED ISSUE #2041: Preview errors on embedded esi with requestanalyzer service
When a service which is used in an esi use the requestanalyzer the preview return an error.
On the website it works fine.

requestanalyzererror

Easiest way to reproduce the bug create an esi controller action with the services and call it in a twig template

```php
public function embedAction() {
        $requestAnalyzer = $this->get('sulu_core.webspace.request_analyzer');
        $this->get('sulu_website.resolver.request_analyzer')->resolve($requestAnalyzer);

       return new Response('ESI');
}
```

```twig
{{ render_esi(controller('ClientWebsiteBundle:Test:embed')) }}
```

Sulu v1.1

### PR DESCRIPTION
**Pull request by wachterjohannes**
| Q | A
| --- | ---
| Bug fix? | no
| New feature? | no
| BC breaks? | no
| Deprecations? | no
| Fixed tickets | fixes #2041
| Related issues/PRs | https://github.com/sulu/sulu-standard/pull/710
| License | MIT
| Documentation PR | none

#### What's in this PR?

This PR introduces the usage of the website-kernel to render the preview.

#### Why?

This would solve a lot of problems (:

### CODE REVIEW

File: src/Sulu/Bundle/PreviewBundle/Preview/Renderer/WebsiteKernelFactory.php [hunk 1]
```diff
@@ -0,0 +1,34 @@
...
+     * {@inheritdoc}
+     */
+    public function create($environment)
+    {
+        $kernel = new \WebsiteKernel($environment, $environment === 'dev');
+        $kernel->boot();
+        $container = $kernel->getContainer();
+
+        if ($container->has('profiler')) {
+            $container->get('profiler')->disable();
```
Comment (wachterjohannes) [inline src/Sulu/Bundle/PreviewBundle/Preview/Renderer/WebsiteKernelFactory.php]: this is necessary because the profiler don't work in the preview and throws exceptions because another kernel is used to profile than the append of the javascript code.

**Comment by danrot** [comment]
Shouldn't we be able to remove some bundles in sulu-standard?

File: src/Sulu/Bundle/PreviewBundle/Preview/Renderer/KernelFactoryInterface.php [hunk 2]
```diff
@@ -0,0 +1,29 @@
...
+
+use Symfony\Component\HttpKernel\KernelInterface;
+
+/**
+ * Creates new Kernels foreach preview request.
+ */
+interface KernelFactoryInterface
+{
+    /**
+     * Create new kernel for a single preview master-request.
```
Comment (danrot) [inline src/Sulu/Bundle/PreviewBundle/Preview/Renderer/KernelFactoryInterface.php]: Didn't we say we want to implement this as a service? Because it is probably faster in websocket mode?

Comment (wachterjohannes) [inline src/Sulu/Bundle/PreviewBundle/Preview/Renderer/KernelFactoryInterface.php]: there are several problems and i would go with this solution and try to improve later. it should be easy to change the behavior of the factory later.

**Comment by wachterjohannes** [comment]
@danrot we have to cleanup the kernels before 1.3 anyway but yes we could at least remove the `ClientWebsiteBundle` form `AbstractKernel`

**Comment by danrot** [comment]
@wachterjohannes Would you mind doing that now? Then it would be easier to test, and we won't forget it. Would also match the PR, since these bundles are probably only included because of the preview.

**Comment by wachterjohannes** [comment]
@danrot done
