### PR TITLE
Fix link field type / content tpye problems title not displayed

### LINKED ISSUE #6525: Link element // No title displayed in admin preview.
| Q | A
| --- | ---
| Sulu Version | 2.4.1
| PHP Version | 8.1
| DB Version | MariaDB 10.7.3
| Browser Version | all

# Actual Behavior

Given an element of content type "link" is used without any parameters or the parameter "enable_title" is set to false. 
When an editor selects a target of type "page" no title is displayed in the element's preview.

link

# Expected Behavior

Since this makes it hard for editors to see that a target is set, the target page's title should be displayed in the element's preview.

# Steps to Reproduce

1. Insert a content element with the following configuration to your page.

```

<property name="internal_link" type="link">
    <meta>
        <title lang="en">Link</title>
    </meta>
</property>
```

or

```
<property name="internal_link" type="link" >
    <meta>
       <title lang="en">Link</title>
    </meta>
    <params>
        <param name="enable_title" value="false"/>
    </params>
</property>
```

2. Select any internal page as the link target

# Possible Solutions

see expected behavior.

### PR DESCRIPTION
**Pull request by wachterjohannes**
| Q | A
| --- | ---
| Bug fix? |  yes
| New feature? | no 
| BC breaks? | no 
| Deprecations? | no  
| Fixed tickets | fixes #6525 
| Related issues/PRs | #6528 
| License | MIT
| Documentation PR | sulu/sulu-docs# 

#### What's in this PR?

Fix link problems title not displayed.

#### Why?

The title should always be displayed also when no alternative title is used.

### CODE REVIEW

File: src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/fields/Link.js [hunk 1]
```diff
@@ -28,6 +28,9 @@ export default class Link extends React.Component<FieldTypeProps<LinkValue>> {
                 types: {
                     value: unvalidatedTypes,
                 } = {},
+                excluded_types: {
+                    value: unvalidatedExcludedTypes,
+                } = {},
```
Comment (alexander-schranz) [inline src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/fields/Link.js]: Looks like a new feature which should be documented. Personally I would prefer that this is splitted into feature targetting 2.5 and bugfix targetting 2.4.

File: src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/fields/Link.js [hunk 2]
```diff
@@ -74,6 +100,7 @@ export default class Link extends React.Component<FieldTypeProps<LinkValue>> {
                 enableAnchor={enableAnchor}
                 enableTarget={enableTarget}
                 enableTitle={enableTitle}
+                excludedTypes={excludedProviderTypes}
```
Comment (alexander-schranz) [inline src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/fields/Link.js]: Feels a little bit strange having both types and excludedTypes but I understand that LinkContainer has the registry and so is the only place to filter them out. So its fine for me.

File: src/Sulu/Bundle/AdminBundle/Resources/js/containers/Link/Link.js [hunk 3]
```diff
@@ -39,6 +42,60 @@ class Link extends Component<Props> {
...
+        this.load(this.props.value);
+    }
+
+    componentDidUpdate(prevProps: Props) {
+        if (prevProps.value !== this.props.value) {
+            this.load(this.props.value);
+        }
+    }
+
+    @action load = (value) => {
```
Comment (alexander-schranz) [inline src/Sulu/Bundle/AdminBundle/Resources/js/containers/Link/Link.js]: This is a bugfix which should target the `2.4` branch. Would also like that @niklasnatter have a look at this.

File: src/Sulu/Bundle/AdminBundle/Resources/js/containers/Link/Link.js [hunk 4]
```diff
@@ -161,13 +220,26 @@ class Link extends Component<Props> {
...
                         <div className={itemClass} onClick={disabled || this.handleTitleClick} role="button">
-                            {title}
+                            {this.displayPropertiesLoading && '…'}
+                            {!this.displayPropertiesLoading && value && (
+                                <div className={linkStyles.columnList}>
+                                    {displayProperties.map((displayProperty) => (
+                                        <span
+                                            className={linkStyles.itemColumn}
+                                            key={displayProperty}
+                                            style={{width: 100 / displayProperties.length + '%'}}
```
Comment (alexander-schranz) [inline src/Sulu/Bundle/AdminBundle/Resources/js/containers/Link/Link.js]: Why this inline styling? Also calculation by string length doesn't work with our font as it is not a monofont.

File: src/Sulu/Bundle/AdminBundle/Resources/js/containers/Link/tests/Link.test.js [hunk 5]
```diff
@@ -1,12 +1,17 @@
 // @flow
 import React from 'react';
-import {render, shallow} from 'enzyme';
+import {mount, render, shallow} from 'enzyme';
 import {observable} from 'mobx';
+import {ResourceRequester} from 'sulu-admin-bundle/services';
```
Comment (alexander-schranz) [inline src/Sulu/Bundle/AdminBundle/Resources/js/containers/Link/tests/Link.test.js]: you are in sulu-admin-bundle so you should use relative path to services

**Review by alexander-schranz — CHANGES_REQUESTED** [review]
@niklasnatter can you have a look at the `load` handling? That should fix #6528 / #6525

File: src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/fields/Link.js [hunk 6]
```diff
@@ -56,6 +59,29 @@ export default class Link extends React.Component<FieldTypeProps<LinkValue>> {
             });
         }
 
+        let excludedProviderTypes = [];
+
+        if (unvalidatedExcludedTypes) {
+            if (!isArrayLike(unvalidatedExcludedTypes)) {
+                throw new Error('The "schemes" schema option must be an array!');
```
Comment (niklasnatter) [inline src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/fields/Link.js]: `schemes` is misleading

File: src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/fields/Link.js [hunk 7]
```diff
@@ -56,6 +59,29 @@ export default class Link extends React.Component<FieldTypeProps<LinkValue>> {
...
+            }
+            // $FlowFixMe: flow does not recognize that isArrayLike(value) means that value is an array
+            const types: Array<any> | IObservableArray<any> = unvalidatedExcludedTypes;
+
+            if (types.length === 0) {
+                throw new Error('The "schemes" schema option must contain some values!');
```
Comment (niklasnatter) [inline src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/fields/Link.js]: `schemes` is misleading

File: src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/fields/Link.js [hunk 8]
```diff
@@ -56,6 +59,29 @@ export default class Link extends React.Component<FieldTypeProps<LinkValue>> {
...
+            }
+
+            excludedProviderTypes = types.map((type) => {
+                if (typeof type.name !== 'string') {
+                    throw new Error(
+                        'Every type in the "types" schemaOption must contain a string as name'
```
Comment (niklasnatter) [inline src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/fields/Link.js]: `types` is misleading

File: src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/fields/Link.js (hunk 6 above)
Comment (niklasnatter) [reply src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/fields/Link.js]:
```suggestion
                throw new Error('The "excluded_types" schema option must be an array!');
```

File: src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/fields/Link.js (hunk 7 above)
Comment (niklasnatter) [reply src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/fields/Link.js]:
```suggestion
                throw new Error('The "excluded_types" schema option must contain some values!');
```

File: src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/fields/Link.js [hunk 9]
```diff
@@ -56,6 +59,29 @@ export default class Link extends React.Component<FieldTypeProps<LinkValue>> {
...
         }
 
+        let excludedProviderTypes = [];
+
+        if (unvalidatedExcludedTypes) {
+            if (!isArrayLike(unvalidatedExcludedTypes)) {
+                throw new Error('The "schemes" schema option must be an array!');
+            }
+            // $FlowFixMe: flow does not recognize that isArrayLike(value) means that value is an array
+            const types: Array<any> | IObservableArray<any> = unvalidatedExcludedTypes;
```
Comment (niklasnatter) [inline src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/fields/Link.js]:
```suggestion
            const excludedTypes: Array<any> | IObservableArray<any> = unvalidatedExcludedTypes;
```

File: src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/fields/Link.js [hunk 10]
```diff
@@ -56,6 +59,29 @@ export default class Link extends React.Component<FieldTypeProps<LinkValue>> {
...
+
+            if (types.length === 0) {
```
Comment (niklasnatter) [inline src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/fields/Link.js]:
```suggestion
            if (excludedTypes.length === 0) {
```

File: src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/fields/Link.js [hunk 11]
```diff
@@ -56,6 +59,29 @@ export default class Link extends React.Component<FieldTypeProps<LinkValue>> {
...
+                throw new Error('The "schemes" schema option must contain some values!');
+            }
+
+            excludedProviderTypes = types.map((type) => {
```
Comment (niklasnatter) [inline src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/fields/Link.js]:
```suggestion
            excludedProviderTypes = excludedTypes.map((type) => {
```

File: src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/fields/Link.js (hunk 8 above)
Comment (niklasnatter) [reply src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/fields/Link.js]:
```suggestion
                        'Every type in the "excluded_types" schemaOption must contain a string as name'
```

File: src/Sulu/Bundle/AdminBundle/Resources/js/containers/Link/Link.js [hunk 12]
```diff
@@ -39,6 +42,60 @@ class Link extends Component<Props> {
...
+            this.load(this.props.value);
+        }
+    }
+
+    @action load = (value) => {
+        if (undefined === value) {
+            this.displayProperties = {};
+        }
+
+        const options = linkTypeRegistry.getOptions(value.provider);
```
Comment (niklasnatter) [inline src/Sulu/Bundle/AdminBundle/Resources/js/containers/Link/Link.js:70]: i think this does not work for medias at the moment. we need to set the options here:
https://github.com/sulu/sulu/blob/2.5/src/Sulu/Bundle/MediaBundle/Resources/js/index.js#L70

File: src/Sulu/Bundle/AdminBundle/Resources/js/containers/Link/Link.js [hunk 13]
```diff
@@ -39,6 +42,60 @@ class Link extends Component<Props> {
...
+    @observable displayPropertiesLoading: boolean = false;
+
+    constructor(props: Props) {
+        super(props);
+
+        this.load(this.props.value);
+    }
+
+    componentDidUpdate(prevProps: Props) {
+        if (prevProps.value !== this.props.value) {
```
Comment (niklasnatter) [inline src/Sulu/Bundle/AdminBundle/Resources/js/containers/Link/Link.js]: this will compare object references. we should use the `fast-deep-equals` package like in other components:
https://github.com/sulu/sulu/blob/2.5/src/Sulu/Bundle/LocationBundle/Resources/js/containers/Location/Location.js#L53

File: src/Sulu/Bundle/AdminBundle/Resources/js/containers/Link/Link.js [hunk 14]
```diff
@@ -161,13 +220,26 @@ class Link extends Component<Props> {
...
                             {allowedTypes.map((key) => (
-                                <SingleSelect.Option key={key} value={key}>{key}</SingleSelect.Option>
+                                <SingleSelect.Option key={key} value={key}>{linkTypeRegistry.getTitle(key)}</SingleSelect.Option>
                             ))}
                         </SingleSelect>
                     </div>
                     <div className={linkStyles.itemContainer}>
                         <div className={itemClass} onClick={disabled || this.handleTitleClick} role="button">
-                            {title}
+                            {this.displayPropertiesLoading && '…'}
```
Comment (niklasnatter) [inline src/Sulu/Bundle/AdminBundle/Resources/js/containers/Link/Link.js]: can we display a loader too like we do for other `single_selections`?

File: src/Sulu/Bundle/AdminBundle/Resources/js/containers/Link/Link.js (hunk 4 above)
Comment (niklasnatter) [reply src/Sulu/Bundle/AdminBundle/Resources/js/containers/Link/Link.js]: i think this was copied from the `SingleSelection`. probably not a perfect solutions, but it worked okay there 🙂 
https://github.com/sulu/sulu/blob/d7015e35982db332e6dc91b2567876e3c135e139/src/Sulu/Bundle/AdminBundle/Resources/js/containers/SingleSelection/SingleSelection.js#L164-L174

File: src/Sulu/Bundle/AdminBundle/Resources/js/containers/Link/Link.js [hunk 15]
```diff
@@ -39,6 +42,60 @@ class Link extends Component<Props> {
...
+        }
+
+        this.displayProperties = {};
+
+        this.displayPropertiesLoading = true;
+        ResourceRequester.get(options.resourceKey, {
+            id: value.href,
+            locale: this.props.locale,
+        }).then(action((data) => {
+            this.displayProperties = Object.keys(data)
```
Comment (niklasnatter) [inline src/Sulu/Bundle/AdminBundle/Resources/js/containers/Link/Link.js]: saving this as an object is not needed as far as i see. i think it would be easier to understand if we call this `titleParts` (and `titleLoading`). `titleParts` can just be an array of strings

File: src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/fields/Link.js (hunk 1 above)
Comment (wachterjohannes) [reply src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/fields/Link.js]: @alexander-schranz have splitted it to an own PR https://github.com/sulu/sulu/pull/6660

**Review by niklasnatter — APPROVED** [review]
looks good to me 🙂
