### PR TITLE
Make disabled MultiItemSelection scrollable

### LINKED ISSUE #5413: Make entries of disabled media_selection scrollable
| Q | A
| --- | ---
| Sulu Version | 2.1
| Browser Version | Browser name and version

# Actual Behavior

The media list has a max height of `225px`. If there are too many medias selected in a disabled `media_selected`, the media list cannot be scrolled.

# Expected Behavior

Scrolling should work in disabled `media_selections`.

# Steps to Reproduce

~~~xml
<property name="medias" type="media_selection" disabledCondition="true">
    <meta>
        <title>app.medias</title>
    </meta>
</property>
~~~

### PR DESCRIPTION
**Pull request by luca-rath**
| Q | A
| --- | ---
| Bug fix? | yes
| New feature? | no
| BC breaks? | no
| Deprecations? | no
| Fixed tickets | fixes #5413
| Related issues/PRs | #issuenum 
| License | MIT
| Documentation PR | sulu/sulu-docs#prnum

#### What's in this PR?

Make disabled MultiItemSelection scrollable

### CODE REVIEW

**Comment by luca-rath** [comment]
@danrot I'm not sure how I should fix the failing pipeline?

This is the problematic code:
```jsx
<section className={blockClass} onClick={this.handleExpand} role="switch">
```

File: src/Sulu/Bundle/AdminBundle/Resources/js/components/MultiItemSelection/MultiItemSelection.js [hunk 1]
```diff
@@ -21,11 +21,26 @@ type Props<T, U, V> = {|
...
 |};
 
-const ItemWrapper = ({children}: Object) => (
-    <li className={multiItemSelectionStyles.listElement}>
-        {children}
-    </li>
-);
+type ItemWrapperProps = {
+    children: Element<typeof Item>,
+    isDisabled: boolean,
```
Comment (danrot) [inline src/Sulu/Bundle/AdminBundle/Resources/js/components/MultiItemSelection/MultiItemSelection.js:26]: We are usually only using `disabled`.

Comment (danrot) [reply src/Sulu/Bundle/AdminBundle/Resources/js/components/MultiItemSelection/MultiItemSelection.js:26]: Ok, weird that the `SortableElement` does not support that... But it is not that bad, since that component is only used within this file.

File: src/Sulu/Bundle/AdminBundle/Resources/js/components/MultiItemSelection/Header.js [hunk 2]
```diff
@@ -23,6 +24,7 @@ export default class Header<T: string | number, U: string | number> extends Reac
 
     render() {
         const {
+            className,
```
Comment (danrot) [inline src/Sulu/Bundle/AdminBundle/Resources/js/components/MultiItemSelection/Header.js:27]: Why not making this more explicit, and pass a `disabled` prop instead? Then we also would not have the `header` class applied twice in the tests.

Comment (danrot) [reply src/Sulu/Bundle/AdminBundle/Resources/js/components/MultiItemSelection/Header.js:27]: And it would be consistent with the `ItemWrapper` below.

**Review by danrot — CHANGES_REQUESTED** [review]

File: src/Sulu/Bundle/AdminBundle/Resources/js/components/MultiItemSelection/Header.js (hunk 2 above)
Comment (luca-rath) [reply src/Sulu/Bundle/AdminBundle/Resources/js/components/MultiItemSelection/Header.js]: fixed

**Review by danrot — APPROVED** [review]
