### PR TITLE
Fix SmartContent tag filtering to use tag IDs instead of names

### LINKED ISSUE #8701: SmartContent Tags filtering working via names instead of ids
| Q | A
| --- | ---
| Sulu Version | 3.0.4
| PHP Version | 8.5

# Actual Behavior

Currently in Sulu 3.0 the SmartContent uses tag `name` for filtering. In Sulu 2.6 the tag `id` was used. The phpcr migration does not handle this and therefore filtering via tags is broken after migrating existing smart contents.

# Expected Behavior

SmartContent can work with tagIds, therefore it will directly work after the migration without manual steps.

# Possible Solutions

SmartContent should be refactored to work with tagIds instead of names.

The tag_selection must be adjusted to also work with the tagId instead of the tagName:
- add a new option to the tag_selection configuration "createProperty" for tags would be e.g. "name" or "title"
- use the createTag controller endpoint in the frontend to create the new tag, after receiving the ID -> use the listRequest to get the tagNames and render the tag list

### PR DESCRIPTION
**Pull request by Amoifr**
| Q | A
| --- | ---
| Bug fix? | yes
| New feature? | no
| BC breaks? | yes
| Deprecations? | yes 
| Fixed tickets | fixes #8701
| Related issues/PRs | # 
| License | MIT
| Documentation PR | sulu/sulu-docs# 

#### What's in this PR?

The SmartContent tag filter and the `tag_selection` field type were migrated from using tags by name to ID, which restores compatibility with content migrated from Sulu 2.6 and aligns tag handling. Inline tag creation now routes through the `TagController` `POST` endpoint so the `sulu.tags.tags` `add` permission is enforced. The change touches the data mapping, normalization, content resolution, the SmartContent providers, the tag selection field, and the admin frontend store.

#### Why?

Sulu 2.6 stored tag IDs in SmartContent filter configuration, but Sulu 3.0 changed this to tag names. The PHPCR migration from 2.6 does not convert the stored values, so SmartContent blocks with tag filters silently stop working after upgrading.

#### BC breaks

**API surface**

- **`TaxonomyDataMapper` constructor**: first argument changed from `TagFactoryInterface` to `TagRepositoryInterface`. The DI service argument was switched from `sulu_content.tag_factory` to `sulu.repository.tag`.
- **`TaxonomyDataMapper::map()` input**: `excerptTags` now expects `int[]` (was `string[]`).
- **`SmartContentProviderInterface` filter shape**: `$filters['tags']` is now `int[]` (was `string[]`). Custom implementations must rename `tags` → `tagIds` in their `mapFilters()` method.
- **`TaxonomyNormalizer` / `ExcerptTaxonomyResolver` output**: `excerptTags` in API responses and resolved content is now `int[]`. Affects every entity using `TaxonomyTrait` (article, page, snippet, example) and any Twig template or frontend that reads it.
- **`tag_selection` field configuration**: `id_property` is now `id` (was `name`) and `filter_parameter` is now `ids` (was `names`).
- **`TagSelectionPropertyResolver`**: now interprets stored data as `int[]` (was `string[]`).
- **`TagResourceLoader::load()`**: now searches by `id` and returns a map keyed by tag ID (was keyed by name).

#### Deprecations

- `Sulu\Content\Domain\Factory\TagFactoryInterface` and `TagFactoryInterface::create()` → use `TagRepositoryInterface::findBy(['id' => $ids])`.
- `Sulu\Bundle\TagBundle\Tag\TagManagerInterface::findOrCreateByName()` and `TagManager::findOrCreateByName()` → create tags via the `TagController` `POST /admin/api/tags` endpoint so permissions are enforced.

#### To Do

- [ ] Provide an SQL migration script that rewrites stored tag-name values to tag IDs for SmartContent filter configuration, tag_selection and excerptTags properties before release

### CODE REVIEW

File: src/Sulu/Bundle/AdminBundle/Resources/js/containers/SmartContent/FilterOverlay.js [hunk 1]
```diff
@@ -57,9 +57,9 @@ class FilterOverlay extends React.Component<Props> {
         super(props);
 
         this.updateFilterCriteriaDisposer = autorun(() => this.updateFilterCriteria(this.props.smartContentStore));
-        this.tagSelectionStore = new MultiSelectionStore('tags', this.tags || [], undefined, 'names');
+i         this.tagSelectionStore = new MultiSelectionStore('tags', this.tags || [], undefined, 'ids');
```
Comment (Prokyonn) [inline src/Sulu/Bundle/AdminBundle/Resources/js/containers/SmartContent/FilterOverlay.js]: Something weird is going on here :D
```suggestion
        this.tagSelectionStore = new MultiSelectionStore('tags', this.tags || [], undefined, 'ids');
```

Comment (Amoifr) [reply src/Sulu/Bundle/AdminBundle/Resources/js/containers/SmartContent/FilterOverlay.js]: Yes thx

**Comment by Prokyonn** [comment]
I did some rough testing locally and so far I've found that `tag_selection` is broken and also the admin list of the smart content is not properly working with the selected tags, currently always shows an empty list as soon as a tag is selected.

> Note: We're not 100% certain this is a bug — the change to tag names in 3.0 might have been intentional. However, this fix restores compatibility with migrated content.

To be honest, we overlooked, that 2.6 did use tagIds internally, because in most cases the `tageName` is used. The PR goes into the right direction, but there are a lot of edge cases where tags are used that also have to be kept in mind.
Especially as tags can be automatically created via the autocomplete field.


We are also thinking about adjusting the auto creation of tags to be controlled from the FE via separate requests directly to the TagController instead of implicitly creating them via the `findOrCreateByName` method from the TagManager. 

Changing it to `ids` also has the side effect, that now the FE must always fetch the tagNames in a request, otherwise it cannot render the tag list.

**Comment by Amoifr** [comment]
Thanks for the detailed feedback and for taking the time to test this locally! 🙏

I've pushed additional changes to complete the ID-based approach:
- Added `ids` parameter support in `TagController`
- Updated `TagResourceLoader` to search by ID
- Adapted `TagSelectionPropertyResolver` accordingly
- Fixed the related tests

I'm wondering — could this be a stepping stone towards the broader tag workflow refactoring you mentioned? If so, happy to adjust anything to better align with your plans.

Let me know what you think!

**Comment by martinlagler** [comment]
@Amoifr (@Prokyonn ) FYI:
I did Update the tag_selection so it now uses the TagController to add new tags, so also the users permission is checked. I also updated the tests.

**Comment by Amoifr** [comment]
Wow, thanks a lot for taking the time to push this through, @martinlagler! 🙏 Pulled your commits locally.

The TagController route for tag creation (with permission check) is a much cleaner solution than the original `findOrCreateByName` path, and I really appreciate you extending the ID-based approach to all the other SmartContentProviders — that was clearly outside the scope of my initial PR but makes the whole thing way more consistent.

Let me know if there's anything you'd like me to test or verify on my side. Happy to help with whatever's needed before merge! 🚀

**Comment by Amoifr** [comment]
Do I have something pending on my side ?

**Comment by martinlagler** [comment]
@Amoifr If you have some spare time it would be awesome if you could test the changes, other than that there is nothing pending on your side. Thank you :D

**Comment by Amoifr** [comment]
Hey @martinlagler 👋

Finished testing on a fresh Sulu 3.0 skeleton with the PR branch (PHP 8.5, MySQL 8, rebuilt admin bundle from your branch so the JS fix is included).

I seeded a Homepage with 5 child pages tagged via the Excerpt tab, and I can confirm everything works end-to-end ✅

SmartContent tag filter on the Homepage
Filtered by News → 2 matching children returned as expected (Welcome News + Release 3.0), so the empty list regression is gone 🎉

Capture d’écran du 2026-04-14 18-31-32


Filter overlay persistence
Source + tag selection persists correctly after save & reload ✅

Capture d’écran du 2026-04-14 18-31-38


Additional spot checks that also passed

Releases → only Release 3.0 ✅
Events → only Launch Event ✅
Tutorials → only How to Sulu ✅
Creating a brand-new tag via the tag_selection autocomplete now correctly POSTs to /admin/api/tags (confirmed in DevTools → Network), and the tag renders with its label instead of a blank chip ✅

Side note
In case it helps anyone else testing this: the sulu/skeleton ships with a prebuilt public/build/admin/main.*.js, so frontend changes require rebuilding the admin bundle:

cd assets/admin && npm install && npm run build

Without that rebuild on a stock skeleton clone, the old bundle masks the MultiAutoComplete fix ⚠️

Huge thanks for pushing this through and extending the ID-based approach to the other providers 🙌
The codebase feels much more consistent now.

Happy to test additional scenarios if needed 👍

**Comment by Amoifr** [comment]
Quick follow-up focused on the tag_selection autocomplete create flow 👇

On a first pass with the skeleton’s prebuilt admin bundle, typing a new tag name and pressing Enter produced a blank chip in the field, and the tag was never persisted in the database ❌
DevTools showed the raw string being pushed directly into ids=... on subsequent list requests, with no POST /admin/api/tags call being made.

After rebuilding the admin bundle from your branch (so the MultiAutoComplete.js change is actually included in main.*.js), the behavior is now exactly as intended ✅

Typing Experimental + Enter fires POST /admin/api/tags ✅
The chip renders with the correct label (no more ghost entry) ✅
On save & reload, the tag is correctly persisted by its ID ✅

Capture d’écran du 2026-04-14 18-01-50

Small heads-up for anyone testing the PR on a fresh sulu/skeleton clone:
The skeleton ships with a prebuilt public/build/admin/main.*.js, so the frontend portion of the fix only applies after rebuilding the admin bundle:

cd assets/admin && npm install && npm run build

Before rebuilding, the blank-chip symptom above can easily be mistaken for a regression in the PR, while it is actually just the pre-fix behavior of the shipped bundle ⚠️

Thanks again for routing tag creation through the TagController 🙌
Much cleaner overall, and permission checks come for free 🔥

**Comment by Amoifr** [comment]
Quick note on the basic tag_selection read/write path (selecting existing tags, not the create-new flow) — also working as expected on the PR branch ✅

Opened a page, and the Tags field correctly populates from the store with all existing tags available in the dropdown:

Capture d’écran du 2026-04-14 16-53-52

Selected News + Tutorials, saved & published, then reloaded the page — the chips persist with the correct labels, and the underlying templateData.tags is now stored as an array of IDs ([1, 3]) rather than names, matching the new ID-based storage model ✅

Capture d’écran du 2026-04-14 16-54-01

Nothing surprising here, but worth confirming explicitly since this is the path most existing content will go through after upgrade 👍

File: packages/content/src/Application/ContentDataMapper/DataMapper/TaxonomyDataMapper.php [hunk 2]
```diff
@@ -23,7 +23,7 @@
 class TaxonomyDataMapper implements DataMapperInterface
 {
     public function __construct(
-        private TagFactoryInterface $tagFactory,
+        private TagManagerInterface $tagManager,
```
Comment (mamazu) [inline packages/content/src/Application/ContentDataMapper/DataMapper/TaxonomyDataMapper.php]: We want to get away from the manager god-classes. I think using the tag repository would be better.

File: packages/content/src/Domain/Factory/TagFactoryInterface.php [hunk 3]
```diff
@@ -15,12 +15,17 @@
 
 use Sulu\Bundle\TagBundle\Tag\TagInterface;
 
+/**
+ * @deprecated since 3.0, use TagManagerInterface::findByIds() instead.
```
Comment (mamazu) [inline packages/content/src/Domain/Factory/TagFactoryInterface.php]:
```suggestion
 * @deprecated since 3.0, use TagRepositoryInterface::findByIds() instead.
```

Or just TagRepositoryInterface::findBy(['id' =>...])

File: packages/content/src/Application/ContentDataMapper/DataMapper/TaxonomyDataMapper.php (hunk 2 above)
Comment (Amoifr) [reply packages/content/src/Application/ContentDataMapper/DataMapper/TaxonomyDataMapper.php]: Good point, thanks! Switched to `TagRepositoryInterface::findTagsByIds()` in `eb69f27099` — DI wiring, unit tests and the `@deprecated` hint on `TagFactoryInterface` all point to the repository now. One less manager god-class 🙌

File: packages/content/src/Domain/Factory/TagFactoryInterface.php (hunk 3 above)
Comment (Amoifr) [reply packages/content/src/Domain/Factory/TagFactoryInterface.php]: Updated the `@deprecated` hint to point to `TagRepositoryInterface::findTagsByIds()` in `eb69f27099`. Thanks for the suggestion! 🙏

File: src/Sulu/Bundle/TagBundle/Entity/TagRepository.php [hunk 4]
```diff
@@ -50,4 +50,17 @@ public function findTagByName($name)
...
+     * @return TagInterface[]
+     */
+    public function findTagsByIds(array $ids): array
+    {
+        $qb = $this->createQueryBuilder('t')
+            ->where('t.id IN (:ids)')
+            ->setParameter('ids', $ids);
+
+        /** @var array<TagInterface> */
+        return $qb->getQuery()->getResult();
```
Comment (mamazu) [inline src/Sulu/Bundle/TagBundle/Entity/TagRepository.php]: It's the same as

```suggestion
        return $this->findBy(['id' => $ids]);
```

File: packages/content/src/Domain/Factory/TagFactoryInterface.php (hunk 3 above)
Comment (mamazu) [reply packages/content/src/Domain/Factory/TagFactoryInterface.php]: Did you also remove the method from the TagManager? I think you added it as well.

File: src/Sulu/Bundle/TagBundle/Entity/TagRepository.php (hunk 4 above)
Comment (Amoifr) [reply src/Sulu/Bundle/TagBundle/Entity/TagRepository.php]: Shame on me for not spotting that one 😅 Applied in `bfa1ecf0c7` — much cleaner, thanks!

File: packages/content/src/Domain/Factory/TagFactoryInterface.php (hunk 3 above)
Comment (Amoifr) [reply packages/content/src/Domain/Factory/TagFactoryInterface.php]: Good catch, shame on me for leaving it behind 😅 Removed `findByIds()` from both `TagManager` and `TagManagerInterface` in `bfa1ecf0c7` — the only consumer was `TaxonomyDataMapper`, which now goes through the repository directly. Thanks!

**Comment by mamazu** [comment]
I've seen you've done some extensive tests to the UI, the thing that we might be missing though is what about existing systems? How does it work if you have a page that uses the named version and then migrate to your version?

## How to test this:
* Create a page with tags on the raw 3.0 branch
* Apply the changes from the pull request
* See if the side still shows the previously selected tags

If not we also might need a migration for existing content

**Comment by alexander-schranz** [comment]
@mamazu it is planned to provide a SQL upgrade before the release. It already is inconsistent between pages created via migration from 2.6 vs pages created manually thats way we will require a migration.

**Comment by Amoifr** [comment]
@alexander-schranz do I have something to do more on this PR ?

File: packages/article/tests/Functional/Integration/responses/article_get.json [hunk 5]
```diff
@@ -23,8 +23,8 @@
     "excerptCategories": [],
     "excerptSegment": "draft-segment",
     "excerptTags": [
-        "Tag 1",
-        "Tag 2"
+        "@integer@",
```
Comment (Prokyonn) [inline packages/article/tests/Functional/Integration/responses/article_get.json:26]: we should use the exact ID instead of just `integer` to also verify the correct order (this applies to all test files)

File: packages/content/tests/Functional/Integration/responses/example_get.json [hunk 6]
```diff
@@ -22,8 +22,8 @@
     "excerptCategories": [],
     "excerptSegment": null,
     "excerptTags": [
-        "Tag 1",
-        "Tag 2"
+        "@integer@",
```
Comment (Prokyonn) [inline packages/content/tests/Functional/Integration/responses/example_get.json:25]: we should use the exact ID instead of just `integer` to also verify the correct order (applies also to the other page responses)

File: packages/snippet/tests/Functional/Integration/responses/snippet_get.json [hunk 7]
```diff
@@ -9,8 +9,8 @@
     "description": null,
     "excerptCategories": [],
     "excerptTags": [
-        "Tag 1",
-        "Tag 2"
+        "@integer@",
```
Comment (Prokyonn) [inline packages/snippet/tests/Functional/Integration/responses/snippet_get.json:12]: same as for article/page snapshots

File: src/Sulu/Bundle/MediaBundle/Tests/Functional/Controller/SmartContentItemControllerTest.php [hunk 8]
```diff
@@ -214,6 +215,155 @@ public function testGetItemsWithoutLocaleParameterUsesRequestLocale(): void
         $this->assertContains('media-2-en', $titles);
     }
 
+    public function testGetItemsFilteredByTags(): void
+    {
+        $collection = $this->createCollection('Test');
+
+        // Create tags
```
Comment (Prokyonn) [inline src/Sulu/Bundle/MediaBundle/Tests/Functional/Controller/SmartContentItemControllerTest.php]: remove unnecessary and obvious comments like "Create Tags" or "Create media with different tags" / ...

File: src/Sulu/Bundle/TagBundle/Tag/TagRepositoryInterface.php [hunk 9]
```diff
@@ -37,4 +37,13 @@ public function findTagById($id);
...
     public function findTagByName($name);
+
+    /**
+     * Finds the tags with the given IDs.
+     *
+     * @param int[] $ids
+     *
+     * @return TagInterface[]
+     */
+    public function findTagsByIds(array $ids);
```
Comment (Prokyonn) [inline src/Sulu/Bundle/TagBundle/Tag/TagRepositoryInterface.php]: This is a BC break and also not documented in the upgrade.md file.

Should we do the BC break in the interface or just adjust the actual TagRepository implementation and create a bc layer when this method is used? WDYT @wachterjohannes @alexander-schranz

File: UPGRADE-3.x.md [hunk 10]
```diff
@@ -1,5 +1,22 @@
...
+**Impact:** If you have custom `SmartContentProviderInterface` implementations, you must update their `mapFilters()` method to convert the `tags` key (array of integer IDs) into whatever key your `DimensionContentQueryEnhancer` expects (typically `tagIds`):
+
+```php
+if ($filters['tags']) {
+    $filters['tagIds'] = $filters['tags'];
+    unset($filters['tags']);
+}
+```
+
+**Stored content:** Any SmartContent filter configuration that was saved with tag names (as strings) will no longer filter correctly. You need to migrate stored SmartContent data to use tag IDs instead of tag names.
```
Comment (Prokyonn) [inline UPGRADE-3.x.md]: We should also mention, that tag creation is now correctly behind the permission settings

**Review by Prokyonn — CHANGES_REQUESTED** [review]

File: src/Sulu/Bundle/AdminBundle/Resources/js/containers/MultiAutoComplete/MultiAutoComplete.js [hunk 11]
```diff
@@ -47,7 +51,35 @@ class MultiAutoComplete extends React.Component<Props> {
...
+
+            if (newlyTypedItem) {
+                const typedValue = newlyTypedItem[idProperty];
+                const itemsWithoutNew = value.filter((item) => item !== newlyTypedItem);
+
+                const tempItem = {[idProperty]: typedValue, [displayProperty]: typedValue};
+                selectionStore.set([...itemsWithoutNew, tempItem]);
+                this.searchStore.clearSearchResults();
+
+                ResourceRequester.post(selectionStore.resourceKey, {[displayProperty]: typedValue})
```
Comment (Prokyonn) [inline src/Sulu/Bundle/AdminBundle/Resources/js/containers/MultiAutoComplete/MultiAutoComplete.js:67]: I think we can run into raceconditions here, e.g. when a user adds multiple tags quickly, then after the request is done we set the selectionStore to the previously saved state (itemsWithoutNew + createdItem) therefore overwriting tags that would have been already added to the store

File: src/Sulu/Bundle/TagBundle/Entity/TagRepository.php [hunk 12]
```diff
@@ -50,4 +50,12 @@ public function findTagByName($name)
             return null;
         }
     }
+
+    /**
+     * @return TagInterface[]
+     */
+    public function findTagsByIds(array $ids): array
+    {
+        return $this->findBy(['id' => $ids]);
```
Comment (Prokyonn) [inline src/Sulu/Bundle/TagBundle/Entity/TagRepository.php]: This call does not guarantee, that we get back the entities in the same order as we sent them. The order is essential for tag_selections.

So we should reorder them after receiving them back from the DB according to the $ids array

File: src/Sulu/Bundle/TagBundle/Tag/TagRepositoryInterface.php (hunk 9 above)
Comment (mamazu) [reply src/Sulu/Bundle/TagBundle/Tag/TagRepositoryInterface.php]: I mean you could also just use the bare Doctrine Repository and inline the implemenation to where it's used (since this is only one place right now)

Comment (alexander-schranz) [reply src/Sulu/Bundle/TagBundle/Tag/TagRepositoryInterface.php]: yes no need for a new method here `findTagsByIds` here as mention by max the repository interface extends Doctrine = `findBy(['id' => $ids]);` or a similar method.

File: src/Sulu/Bundle/TagBundle/Entity/TagRepository.php (hunk 12 above)
Comment (alexander-schranz) [reply src/Sulu/Bundle/TagBundle/Entity/TagRepository.php]: We should do that logic in the service calling the repository ( resource loader? ). The repo is not responsible for reorder them, and tags API list call the list builder should handdle it.

File: packages/article/tests/Functional/Integration/responses/article_get.json (hunk 5 above)
Comment (Amoifr) [reply packages/article/tests/Functional/Integration/responses/article_get.json:26]: Thanks for the catch! Updated all response snapshots to use exact tag IDs instead of `@integer@` — this way we properly verify the ordering too. Applied across article, content, page and snippet responses 👍

File: packages/content/tests/Functional/Integration/responses/example_get.json (hunk 6 above)
Comment (Amoifr) [reply packages/content/tests/Functional/Integration/responses/example_get.json:25]: Applied across all packages, same as article.

File: packages/snippet/tests/Functional/Integration/responses/snippet_get.json (hunk 7 above)
Comment (Amoifr) [reply packages/snippet/tests/Functional/Integration/responses/snippet_get.json:12]: Done, same treatment applied here.

File: src/Sulu/Bundle/MediaBundle/Tests/Functional/Controller/SmartContentItemControllerTest.php (hunk 8 above)
Comment (Amoifr) [reply src/Sulu/Bundle/MediaBundle/Tests/Functional/Controller/SmartContentItemControllerTest.php]: Good point, cleaned up! The code speaks for itself here 🧹

File: UPGRADE-3.x.md (hunk 10 above)
Comment (Amoifr) [reply UPGRADE-3.x.md]: Added a section about tag creation now being behind permission settings, thanks for flagging this!

File: src/Sulu/Bundle/TagBundle/Tag/TagRepositoryInterface.php (hunk 9 above)
Comment (Amoifr) [reply src/Sulu/Bundle/TagBundle/Tag/TagRepositoryInterface.php]: Makes total sense — I'll drop `findTagsByIds()` from the interface and repository, and use `findBy(['id' => $ids])` directly where needed. Thanks @mamazu @alexander-schranz for the clarification! 🙏

File: src/Sulu/Bundle/TagBundle/Entity/TagRepository.php (hunk 12 above)
Comment (Amoifr) [reply src/Sulu/Bundle/TagBundle/Entity/TagRepository.php]: That makes sense — the repository shouldn't be responsible for reordering. I'll move the ordering logic to the calling service. Thanks for the guidance!

File: src/Sulu/Bundle/AdminBundle/Resources/js/containers/MultiAutoComplete/MultiAutoComplete.js (hunk 11 above)
Comment (Amoifr) [reply src/Sulu/Bundle/AdminBundle/Resources/js/containers/MultiAutoComplete/MultiAutoComplete.js:67]: That's a valid concern — quick successive tag additions could overwrite each other. I'll look into the best approach here (debounce, queue, or optimistic update) and follow up. Thanks for spotting this! 🔍

File: src/Sulu/Bundle/TagBundle/Tag/TagRepositoryInterface.php (hunk 9 above)
Comment (Amoifr) [reply src/Sulu/Bundle/TagBundle/Tag/TagRepositoryInterface.php]: Done! Removed `findTagsByIds()` entirely and inlined `findBy(['id' => $ids])` in `TaxonomyDataMapper` with reordering logic there. Thanks for the suggestion! 🙏

File: src/Sulu/Bundle/TagBundle/Entity/TagRepository.php (hunk 12 above)
Comment (Amoifr) [reply src/Sulu/Bundle/TagBundle/Entity/TagRepository.php]: Good point — moved the reordering logic to `TaxonomyDataMapper`, which is the service calling the repository. The repository now stays clean with just the standard Doctrine `findBy()`. Thanks for the guidance! 👍

**Review by Prokyonn — APPROVED** [review]

**Comment by Prokyonn** [comment]
@Amoifr Thank you!
