### PR TITLE
App veyor (windows) support

### LINKED ISSUE #2071: Enable build testing on AppVeyor
A configuration file should be added in order to enable builds on AppVeyor (automated Windows builds). Such builds make sure that Sulu consistently works on Unix and Windows and that we don't introduce platform-specific regressions.

### PR DESCRIPTION
**Pull request by dantleech**
| Q | A
| --- | ---
| Bug fix? | no
| New feature? | no
| BC breaks? | no
| Deprecations? | no
| Fixed tickets | fixes #2071

#### What's in this PR?

This PR adds support for running continuous integration tests on [appveyor](https://ci.appveyor.com).

#### Why?

Because some people use Windows, apparently.

### CODE REVIEW

File: src/Sulu/Bundle/AdminBundle/Tests/bootstrap.php [hunk 1]
```diff
@@ -14,6 +14,6 @@
     throw new RuntimeException('Install dependencies to run test suite.');
 }
 
-$autoload = require_once $file;
+$autoload = require $file;
```
Comment (dantleech) [inline src/Sulu/Bundle/AdminBundle/Tests/bootstrap.php]: Because PHPUnit includes the autoload file and then composer includes it, only affects us when using `vendor/bin/phpunit`, which we are not - but I think it is a harmless change.

File: src/Sulu/Bundle/ContentBundle/Tests/bootstrap.php [hunk 2]
```diff
@@ -9,11 +9,11 @@
  * with this source code in the file LICENSE.
  */
 
-$file = __DIR__ . '/../vendor/autoload.php';
+$file = realpath(__DIR__ . '/../vendor/autoload.php');
```
Comment (danrot) [inline src/Sulu/Bundle/ContentBundle/Tests/bootstrap.php]: Why is this change only required in this single file, but not in all the others?

File: src/Sulu/Bundle/TestBundle/Resources/dist/sulu.yml [hunk 3]
```diff
@@ -11,6 +11,8 @@ framework:
     profiler:
         enabled: false
 
+sulu_core:
```
Comment (danrot) [inline src/Sulu/Bundle/TestBundle/Resources/dist/sulu.yml]: I guess this is not needed?

**Comment by danrot** [comment]
CHANGELOG missing

File: appveyor.yml [hunk 4]
```diff
@@ -0,0 +1,68 @@
...
+  - ps: echo ("@php c:\tools\php\phpunit.phar %*") | Out-File phpunit.bat -encoding ascii
+
+  # install and start jackrabbit
+  - cd %APPVEYOR_BUILD_FOLDER%
+  - ls 
+  - if not exist jackrabbit-standalone-%JACKRABBIT_VERSION%.jar appveyor DownloadFile http://archive.apache.org/dist/jackrabbit/%JACKRABBIT_VERSION%/jackrabbit-standalone-%JACKRABBIT_VERSION%.jar
+  - ls
+  - ps: Start-Process ("jackrabbit-standalone-" + $env:JACKRABBIT_VERSION + ".jar")
+  # sleep to allow jackrabbit to start - maybe not necessary as we have some time while composer installs the deps.
+  - ps: Start-Sleep -s 5
```
Comment (danrot) [inline appveyor.yml]: Then these 5 seconds won't probably help anyway... Can we remove it? It's only lengthening the build.

Comment (dantleech) [inline appveyor.yml]: reducing to 1

**Comment by dantleech** [comment]
@danrot updated.

File: appveyor.yml [hunk 5]
```diff
@@ -0,0 +1,68 @@
...
+  - ps: echo ("@php c:\tools\php\phpunit.phar %*") | Out-File phpunit.bat -encoding ascii
+
+  # install and start jackrabbit
+  - cd %APPVEYOR_BUILD_FOLDER%
+  - ls 
+  - if not exist jackrabbit-standalone-%JACKRABBIT_VERSION%.jar appveyor DownloadFile http://archive.apache.org/dist/jackrabbit/%JACKRABBIT_VERSION%/jackrabbit-standalone-%JACKRABBIT_VERSION%.jar
+  - ls
+  - ps: Start-Process ("jackrabbit-standalone-" + $env:JACKRABBIT_VERSION + ".jar")
+  # sleep to allow jackrabbit to start - maybe not necessary as we have some time while composer installs the deps.
+  - ps: Start-Sleep -s 1
```
Comment (danrot) [inline appveyor.yml]: So it is really necessary? And not possible to remove at all?

Comment (dantleech) [inline appveyor.yml]: Basically we are saying that as long as composer doesn't install very
quickly and that there are enough tests before Jackrabbit is invoked for
the first time then Jackrabbit *should* be ready. Its hardly a
guarantee - its just incidental that the test process will allow time
for Jackrabbit to start.

Saying that, I will just remove it.
