### PR TITLE
Fix missing Reference in Link Provider

### LINKED ISSUE #7821: References for Link Content Type
# Problem description

Currently no references are written for Link Content Type.

# Proposed solution

The link content type should also write references.

### PR DESCRIPTION
**Pull request by draconivis**
| Q | A
| --- | ---
| Bug fix? | no
| New feature? | yes
| BC breaks? | no
| Deprecations? | no
| Fixed tickets | fixes #7821
| Related issues/PRs | #7821 
| License | MIT

#### What's in this PR?

Add ReferenceStorePool to the Link type and write a reference.

#### Why?

#7821

### CODE REVIEW

File: src/Sulu/Component/Content/Types/Link.php [hunk 1]
```diff
@@ -112,6 +117,17 @@ public function getContentData(PropertyInterface $property): ?string
             $url = \sprintf('%s#%s', $url, $value['anchor']);
         }
 
+        $mediaReferenceStore = $this->getMediaReferenceStore($value['provider']);
```
Comment (Prokyonn) [inline src/Sulu/Component/Content/Types/Link.php]: Rename to `referenceStore` as we do not know exactly for which entity the referenceStore is fetched from the pool. The `value['provider']` defines this.

File: src/Sulu/Component/Content/Types/Link.php [hunk 2]
```diff
@@ -127,4 +143,13 @@ public function importData(
         $property->setValue(\json_decode($value, true));
         $this->write($node, $property, $userId, $webspaceKey, $languageCode, $segmentKey);
     }
+
+    private function getMediaReferenceStore(string $provider): ?ReferenceStoreInterface
```
Comment (Prokyonn) [inline src/Sulu/Component/Content/Types/Link.php]: rename to `getReferenceStore`

**Review by Prokyonn — CHANGES_REQUESTED** [review]

File: src/Sulu/Component/Content/Types/Link.php [hunk 3]
```diff
@@ -25,8 +28,10 @@ class Link extends SimpleContentType
 {
     public const LINK_TYPE_EXTERNAL = 'external';
 
-    public function __construct(private LinkProviderPoolInterface $providerPool)
-    {
+    public function __construct(
+        private LinkProviderPoolInterface $providerPool,
+        private ReferenceStorePoolInterface $referenceStorePool,
```
Comment (alexander-schranz) [inline src/Sulu/Component/Content/Types/Link.php]: the reference pool need to be optional else it would be a bc break.

```suggestion
        private ?ReferenceStorePoolInterface $referenceStorePool = null,
```

we should throw a deprecation message in the constructor.


```php
        if (!$this->referenceStorePool instanceof ReferenceStorePoolInterface) {
            @trigger_deprecation('sulu/sulu', '2.5', 'Initializing "' . __CLASS__ . '" without referenceStorePool is deprecated.');
        }
```

**Review by alexander-schranz — APPROVED** [review]

File: src/Sulu/Component/Content/Types/Link.php [hunk 4]
```diff
@@ -25,8 +28,14 @@ class Link extends SimpleContentType
...
     public const LINK_TYPE_EXTERNAL = 'external';
 
-    public function __construct(private LinkProviderPoolInterface $providerPool)
-    {
+    public function __construct(
+        private LinkProviderPoolInterface $providerPool,
+        private ?ReferenceStorePoolInterface $referenceStorePool = null,
+    ) {
+        if (!$this->referenceStorePool instanceof ReferenceStorePoolInterface) {
+            @trigger_deprecation('sulu/sulu', '2.5', 'Initializing "' . __CLASS__ . '" without referenceStorePool is deprecated.');
```
Comment (Prokyonn) [inline src/Sulu/Component/Content/Types/Link.php]:
```suggestion
            @trigger_deprecation('sulu/sulu', '2.5.27', 'Initializing "' . __CLASS__ . '" without referenceStorePool is deprecated.');
```

**Review by Prokyonn — APPROVED** [review]
