### PR TITLE
Fix missing global block copy reference

### LINKED ISSUE #8120: WebspaceCopyCommand ignores global_blocks
| Q | A
| --- | ---
| Sulu Version | 2.6.11
| PHP Version | PHP 8.3

# Actual Behavior

When running the webspace copy commands, page templates with link types in global_blocks
``` 
<types>
    <type ref="section-type1" />
    <type ref="section-type2" />
</types>
```
are not updated with their new reference after copy command.
 
# Expected Behavior

Links in Block "section-type1" should be updated with their corresponding new reference.

# Possible Solutions

Sadly I have no idea, how to implement it. If you could provide a suggestion, I could implement this.

### PR DESCRIPTION
**Pull request by MarkusHolstein**
#8120

| Q | A
| --- | ---
| Bug fix? | yes
| New feature? | no
| BC breaks? | no
| Deprecations? | no
| Fixed tickets | #8120 
| License | MIT

#### What's in this PR?

Replaces link references during websiteCopyCommand, whcih are configured "below" global block configuration.

#### Why?

Fixes #8120 . This allow to update more link references.

### CODE REVIEW

**Review by alexander-schranz — APPROVED** [review]

File: src/Sulu/Bundle/PageBundle/Command/WebspaceCopyCommand.php [hunk 1]
```diff
@@ -63,7 +64,8 @@ public function __construct(
         private DocumentManagerInterface $documentManager,
         private SessionManagerInterface $sessionManager,
         private DocumentInspector $documentInspector,
-        private HtmlTagExtractor $htmlTagExtractor
+        private HtmlTagExtractor $htmlTagExtractor,
+        private StructureMetadataFactoryInterface $structureMetadataFactory,
```
Comment (alexander-schranz) [inline src/Sulu/Bundle/PageBundle/Command/WebspaceCopyCommand.php:68]: normally we would require a bc layer for new required params, but as I don't think somebody extended this class we are good to go.

**Review by alexander-schranz — APPROVED** [review]

**Comment by alexander-schranz** [comment]
@MarkusHolstein Thank you!
