### PR TITLE
Fix fast pagination of List view

### LINKED ISSUE #4912: Page tree gets cleared after clicking on different pages before first request is finished
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | 2.0.2
| Browser Version | Chrome latest

#### Actual Behavior

The webspace page tree gets cleared completely.

#### Expected Behavior

The page tree shows the contents of the last clicked page.

#### Steps to Reproduce

Go to webspaces, click on any child page of the homepage and then on a different page immediately after the first click.
If your second click is on a page with children, all children except the first one get displayed.

### PR DESCRIPTION
**Pull request by danrot**
| Q | A
| --- | ---
| Bug fix? | yes
| New feature? | no
| BC breaks? | no
| Deprecations? | no
| Fixed tickets | fixes #4912 
| Related issues/PRs | ---
| License | MIT
| Documentation PR | ---

#### What's in this PR?

This PR cancels the request from a list when a new request for the same list has been sent.

#### Why?

Because otherwise it can happen that sooner requests finish later than the ones starting later, causing the wrong page to display. E.g. if you navigate from page 1 to page 10 by clicking the next icon without waiting for the requests to finish, you could e.g. to be shown page 9, although the list shows page 10.

### CODE REVIEW

File: src/Sulu/Bundle/AdminBundle/Resources/js/containers/List/stores/ListStore.js [hunk 1]
```diff
@@ -511,6 +517,11 @@ export default class ListStore {
                 this.initialSelectionIds = undefined;
             }
         })).catch((response) => {
+            if (response.name === 'AbortError') {
```
Comment (nnatter) [inline src/Sulu/Bundle/AdminBundle/Resources/js/containers/List/stores/ListStore.js]: i am a bit hesitant to rely on the `name` here.. isnt there at least a constant somewhere that we could use?

File: src/Sulu/Bundle/AdminBundle/Resources/js/containers/List/stores/ListStore.js [hunk 2]
```diff
@@ -490,11 +491,16 @@ export default class ListStore {
 
         log.info('List loads "' + this.resourceKey + '" data with the following options:', options);
 
-        this.loadingStrategy.load(
+        if (this.pendingRequest instanceof RequestPromise) {
```
Comment (nnatter) [inline src/Sulu/Bundle/AdminBundle/Resources/js/containers/List/stores/ListStore.js]: wouldnt it be more intuitive to check if it is set/not undefined? 🙈

File: src/Sulu/Bundle/AdminBundle/Resources/js/containers/List/stores/ListStore.js (hunk 1 above)
Comment (nnatter) [reply src/Sulu/Bundle/AdminBundle/Resources/js/containers/List/stores/ListStore.js]: also why dont you set `this.pendingRequest` to undefined in this case? :

**Comment by nnatter** [comment]
looks good otherwise. but i need a rebase 🙂

File: src/Sulu/Bundle/AdminBundle/Resources/js/containers/List/stores/ListStore.js (hunk 2 above)
Comment (danrot) [reply src/Sulu/Bundle/AdminBundle/Resources/js/containers/List/stores/ListStore.js]: Actually I thought that it makes more sense this way... I even thought about a `CancelablePromise` or something like that, but the issue is that only requests can be cancelled.

File: src/Sulu/Bundle/AdminBundle/Resources/js/containers/List/stores/ListStore.js (hunk 1 above)
Comment (danrot) [reply src/Sulu/Bundle/AdminBundle/Resources/js/containers/List/stores/ListStore.js]: At least the `name` attribute is safe to use, because it is standardized, as documented in [MDN](https://developer.mozilla.org/en-US/docs/Web/API/AbortController/AbortController) and [Google Developers](https://developers.google.com/web/updates/2017/09/abortable-fetch#reacting_to_an_aborted_fetch).

File: src/Sulu/Bundle/AdminBundle/Resources/js/services/Requester/RequestPromise.js [hunk 3]
```diff
@@ -0,0 +1,28 @@
...
+
+    then(onFulfilled: ?(*) => Promise<*> | *, onRejected: ?(*) => Promise<*> | *): RequestPromise<*> {
+        const requestPromise: RequestPromise<*> = ((super.then(onFulfilled, onRejected): any): RequestPromise<*>);
+        requestPromise.setAbortController(this.abortController);
+
+        return requestPromise;
+    }
+
+    catch(onReject: ?(*) => Promise<*> | *): RequestPromise<*> {
+        // $FlowFixMe
```
[the remark this answers is not in the document]
Comment (danrot) [reply src/Sulu/Bundle/AdminBundle/Resources/js/services/Requester/RequestPromise.js]: Removed the `$FlowFixMe` and set the AbortController. Strictly speaking the latter would probably not be necessary, because you can't cancel something that has already failed... Added it anyway just to be sure, maybe there is some kind of edge case.

File: src/Sulu/Bundle/AdminBundle/Resources/js/containers/List/stores/ListStore.js (hunk 2 above)
Comment (danrot) [reply src/Sulu/Bundle/AdminBundle/Resources/js/containers/List/stores/ListStore.js]: Realized that because of some type changes I don't even need the `instanceof` anymore, therefore I removed it :slightly_smiling_face:

File: src/Sulu/Bundle/AdminBundle/Resources/js/containers/List/stores/ListStore.js (hunk 1 above)
Comment (danrot) [reply src/Sulu/Bundle/AdminBundle/Resources/js/containers/List/stores/ListStore.js]: Regarding setting `this.pendingRequest`. We could do that, but I think it is safer not to. The only place we abort the request is right before we are assigning a new value to `this.pendingRequest` anyway. So assigning another value does not make too much sense, since it will be reassigned immediately. Additionally I am not sure if that could cause some kind of race condition, therefore I think it is safer not to do it.
