### PR TITLE
resource locator generation for pages with unpublished parents

### LINKED ISSUE #2646: ResourcelocatorNotFoundException when generating ResourceLocator below never published page
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | 79df1b3

#### Actual Behavior

When i try to created some tree like structure as draft it is not possible to create children of an unpublished object. The form trys to use the ressource locator and this causes an error (i think it is trying to access the parent ressource which has no published resource locator?):
Response
```
{
    "code": 0,
    "errors": [
        {
            "class": "Sulu\\Component\\Content\\Exception\\ResourceLocatorNotFoundException",
            "code": 0,
            "file": "/var/www/sulu-minimal/vendor/sulu/sulu/src/Sulu/Component/Content/Types/Rlp/Mapper/PhpcrMapper.php",
            "headers": [],
            "line": 124,
            "message": "",
            "statusCode": 500,
            "trace": [
                {
                    "args": [],
                    "class": "",
                    "file": "/var/www/sulu-minimal/vendor/sulu/sulu/src/Sulu/Component/Content/Types/Rlp/Mapper/PhpcrMapper.php",
                    "function": "",
                    "line": 124,
                    "namespace": "",
                    "short_class": "",
                    "type": ""
                },
                {
                    "args": [
                        [
                            "object",
                            "Jackalope\\Node"
                        ],
                        [
                            "string",
                            "myportal"
                        ],
                        [
                            "string",
                            "de"
                        ],
                        [
                            "null"
                        ]
                    ],
                    "class": "Sulu\\Component\\Content\\Types\\Rlp\\Mapper\\PhpcrMapper",
                    "file": "/var/www/sulu-minimal/vendor/sulu/sulu/src/Sulu/Component/Content/Types/Rlp/Strategy/RlpStrategy.php",
                    "function": "loadByContent",
                    "line": 255,
                    "namespace": "Sulu\\Component\\Content\\Types\\Rlp\\Mapper",
                    "short_class": "PhpcrMapper",
                    "type": "->"
                },
                {
                    "args": [
                        [
                            "object",
                            "Sulu\\Bundle\\ContentBundle\\Document\\PageDocument"
                        ]
                    ],
                    "class": "Sulu\\Component\\Content\\Types\\Rlp\\Strategy\\RlpStrategy",
                    "file": "/var/www/sulu-minimal/vendor/sulu/sulu/src/Sulu/Bundle/ContentBundle/Repository/ResourceLocatorRepository.php",
                    "function": "loadByContent",
                    "line": 83,
                    "namespace": "Sulu\\Component\\Content\\Types\\Rlp\\Strategy",
                    "short_class": "RlpStrategy",
                    "type": "->"
                },
                {
                    "args": [
                        [
                            "array",
                            {
                                "title": [
                                    "string",
                                    "sdadada"
                                ]
                            }
                        ],
                        [
                            "string",
                            "f2034982-245a-465a-ae38-2a4693d2289e"
                        ],
                        [
                            "null"
                        ],
                        [
                            "string",
                            "myportal"
                        ],
                        [
                            "string",
                            "de"
                        ],
                        [
                            "string",
                            "frontpage"
                        ]
                    ],
                    "class": "Sulu\\Bundle\\ContentBundle\\Repository\\ResourceLocatorRepository",
                    "file": "/var/www/sulu-minimal/vendor/sulu/sulu/src/Sulu/Bundle/ContentBundle/Controller/NodeResourcelocatorController.php",
                    "function": "generate",
                    "line": 43,
                    "namespace": "Sulu\\Bundle\\ContentBundle\\Repository",
                    "short_class": "ResourceLocatorRepository",
                    "type": "->"
                },
                {
                    "args": [],
                    "class": "Sulu\\Bundle\\ContentBundle\\Controller\\NodeResourcelocatorController",
                    "function": "postGenerateAction",
                    "namespace": "Sulu\\Bundle\\ContentBundle\\Controller",
                    "short_class": "NodeResourcelocatorController",
                    "type": "->"
                },
                {
                    "args": [
                        [
                            "array",
                            [
                                [
                                    "object",
                                    "Sulu\\Bundle\\ContentBundle\\Controller\\NodeResourcelocatorController"
                                ],
                                [
                                    "string",
                                    "postGenerateAction"
                                ]
                            ]
                        ],
                        [
                            "array",
                            []
                        ]
                    ],
                    "class": "",
                    "file": "/var/www/sulu-minimal/web/bootstrap.php.cache",
                    "function": "call_user_func_array",
                    "line": 3235,
                    "namespace": "",
                    "short_class": "",
                    "type": ""
                },
                {
                    "args": [
                        [
                            "object",
                            "Symfony\\Component\\HttpFoundation\\Request"
                        ],
                        [
                            "string",
                            "1"
                        ]
                    ],
                    "class": "Symfony\\Component\\HttpKernel\\HttpKernel",
                    "file": "/var/www/sulu-minimal/web/bootstrap.php.cache",
                    "function": "handleRaw",
                    "line": 3194,
                    "namespace": "Symfony\\Component\\HttpKernel",
                    "short_class": "HttpKernel",
                    "type": "->"
                },
                {
                    "args": [
                        [
                            "object",
                            "Symfony\\Component\\HttpFoundation\\Request"
                        ],
                        [
                            "string",
                            "1"
                        ],
                        [
                            "boolean",
                            true
                        ]
                    ],
                    "class": "Symfony\\Component\\HttpKernel\\HttpKernel",
                    "file": "/var/www/sulu-minimal/web/bootstrap.php.cache",
                    "function": "handle",
                    "line": 3348,
                    "namespace": "Symfony\\Component\\HttpKernel",
                    "short_class": "HttpKernel",
                    "type": "->"
                },
                {
                    "args": [
                        [
                            "object",
                            "Symfony\\Component\\HttpFoundation\\Request"
                        ],
                        [
                            "string",
                            "1"
                        ],
                        [
                            "boolean",
                            true
                        ]
                    ],
                    "class": "Symfony\\Component\\HttpKernel\\DependencyInjection\\ContainerAwareHttpKernel",
                    "file": "/var/www/sulu-minimal/web/bootstrap.php.cache",
                    "function": "handle",
                    "line": 2533,
                    "namespace": "Symfony\\Component\\HttpKernel\\DependencyInjection",
                    "short_class": "ContainerAwareHttpKernel",
                    "type": "->"
                },
                {
                    "args": [
                        [
                            "object",
                            "Symfony\\Component\\HttpFoundation\\Request"
                        ]
                    ],
                    "class": "Symfony\\Component\\HttpKernel\\Kernel",
                    "file": "/var/www/sulu-minimal/web/admin.php",
                    "function": "handle",
                    "line": 40,
                    "namespace": "Symfony\\Component\\HttpKernel",
                    "short_class": "Kernel",
                    "type": "->"
                }
            ]
        }
    ],
    "message": ""
}
```
#### Expected Behavior

It should be possible to create childrens below a draft.

#### Steps to Reproduce

Create an content object (e.g. default) as draft and then try to create some children below this never published object. As soon as you publish it, there is no problem.

### PR DESCRIPTION
**Pull request by nnatter**
| Q | A
| --- | ---
| Bug fix? | yes
| New feature? | no
| BC breaks? | no
| Deprecations? | no
| Fixed tickets | fixes #2646 
| Related issues/PRs | -
| License | MIT
| Documentation PR | -

#### What's in this PR?

This PR fixes resource locator generation for new pages with an unpublished parent page.

The ResourceLocatorRepository uses the first published ancestor in the same locale (or the root document) of the new page for url-generation now.

### CODE REVIEW

**Comment by danrot** [comment]
@nnatter Please add a test (to the `ResourceLocatorRepositoryTest`, and rewrite the tests to be unit tests)

File: src/Sulu/Bundle/ContentBundle/Tests/Unit/Repository/ResourceLocatorRepositoryTest.php [hunk 1]
```diff
@@ -0,0 +1,243 @@
...
+
+        // path related
+        $parentPath = '/parent';
+        $this->rlpStrategy->loadByContent($parent)->willReturn($parentPath);
+
+        $title = 'news-football';
+        $path = $parentPath . '/' . $title;
+        $this->rlpStrategy->generate($title, $parentPath, $webspace, $locale, null)->willReturn($path);
+
+        // method call
```
Comment (danrot) [inline src/Sulu/Bundle/ContentBundle/Tests/Unit/Repository/ResourceLocatorRepositoryTest.php]: Doesn't add any value, please remove.

Comment (danrot) [inline src/Sulu/Bundle/ContentBundle/Tests/Unit/Repository/ResourceLocatorRepositoryTest.php]: Actually almost all comments in this file could be removed... Please only add comments if they add real value. If you create a document and assign it to the variable `$parent` it's obvious that it is a parent document. If you add a comment saying that it's just duplicating information, which might even diverge somewhen in the future.

File: src/Sulu/Bundle/ContentBundle/Tests/Unit/Repository/ResourceLocatorRepositoryTest.php [hunk 2]
```diff
@@ -0,0 +1,243 @@
...
+        $parent = $this->prophesize(BasePageDocument::class);
+        $parent->getPublished()->willReturn(true);
+        $this->documentManager->find($parentUuid, $locale, ['load_ghost_content' => false])->willReturn($parent->reveal());
+
+        // path related
+        $parentPath = '/parent';
+        $this->rlpStrategy->loadByContent($parent)->willReturn($parentPath);
+
+        $title = 'news-football';
+        $path = $parentPath . '/' . $title;
```
Comment (danrot) [inline src/Sulu/Bundle/ContentBundle/Tests/Unit/Repository/ResourceLocatorRepositoryTest.php]: By doing this concatenation you are already duplicating the logic from the system to test in some way. I would just use a simple string in the assertion call instead.

File: src/Sulu/Bundle/ContentBundle/Tests/Functional/Repository/ResourceLocatorRepositoryTest.php [hunk 3]
```diff
@@ -1,127 +0,0 @@
...
-            null,
-            'sulu_io',
-            'en',
-            'overview'
-        );
-
-        $this->assertEquals('/test/test', $result['resourceLocator']);
-    }
-
-    public function testGenerateSlash()
```
Comment (danrot) [inline src/Sulu/Bundle/ContentBundle/Tests/Functional/Repository/ResourceLocatorRepositoryTest.php]: Where is the counterpart for this test?

**Comment by danrot** [comment]
@nnatter You also have to rebase directly before you push, because if there is a conflict the tests won't run...

File: src/Sulu/Bundle/ContentBundle/Tests/Functional/Repository/ResourceLocatorRepositoryTest.php (hunk 3 above)
Comment (nnatter) [inline src/Sulu/Bundle/ContentBundle/Tests/Functional/Repository/ResourceLocatorRepositoryTest.php]: @danrot: This should be in the same equivalence partation as testGenerate(). 
The slash replacement is implemented in the RlpStrategy which is mocked.

File: src/Sulu/Bundle/ContentBundle/Tests/Unit/Repository/ResourceLocatorRepositoryTest.php [hunk 4]
```diff
@@ -0,0 +1,225 @@
...
+            new Property('title', 'title', 'title'),
+        ]);
+        $this->structureManager->getStructure($template)->willReturn($structure->reveal());
+
+        $title = 'news-football';
+        $path = '/news-football';
+        $this->rlpStrategy->generate($title, '/', $webspace, $locale, null)->willReturn($path);
+
+        $result = $this->repository->generate($parts, null, null, $webspace, $locale, $template);
+        $this->assertEquals($result['resourceLocator'], $path);
```
Comment (danrot) [inline src/Sulu/Bundle/ContentBundle/Tests/Unit/Repository/ResourceLocatorRepositoryTest.php]: Actually I meant you shouldn't use the `$path` variable at all, because it is easier to read here, and needs less memory 😉

File: src/Sulu/Bundle/ContentBundle/Tests/Functional/Repository/ResourceLocatorRepositoryTest.php (hunk 3 above)
Comment (danrot) [inline src/Sulu/Bundle/ContentBundle/Tests/Functional/Repository/ResourceLocatorRepositoryTest.php]: Is the slash replacement tested in the `RlpStrategyTest`? If not you should be implemented there, otherwise you can't simply delete this test.

Comment (nnatter) [inline src/Sulu/Bundle/ContentBundle/Tests/Functional/Repository/ResourceLocatorRepositoryTest.php]: Yes, a `testGenerateSlash()` testcase is already present in the `RlpStrategyTest`.

File: src/Sulu/Bundle/ContentBundle/Tests/Unit/Repository/ResourceLocatorRepositoryTest.php (hunk 4 above)
Comment (nnatter) [inline src/Sulu/Bundle/ContentBundle/Tests/Unit/Repository/ResourceLocatorRepositoryTest.php]: @danrot: The $path variable is used as return value of the generate-method of the mocked rlpStrategy **and** in the assertion which checks the result of the method. 
I'm not sure, if it is intuitive to use 2 independent strings here?

Comment (danrot) [inline src/Sulu/Bundle/ContentBundle/Tests/Unit/Repository/ResourceLocatorRepositoryTest.php]: Well, it is not really about intuition here. It could be possible that the variable is modified somewhere in between... But yeah, it's not the case here, forget about it.
