### PR TITLE
Fix smart content params filtering and null property paths

### LINKED ISSUE #8624: Sulu 3.0: smart_content params
# Problem description

Smart Content parameters must be consistent.

Previously, the article provider used the parameters `types` and `structureTypes`.
To avoid confusion, all Smart Content providers should now use consistent parameter names: groups and template (or templateKey).

If a project still has types or structureTypes configured for the article provider, an exception should be thrown during the cache:clear command.

# Proposed solution

Make it concistent.

### PR DESCRIPTION
**Pull request by Prokyonn**
| Q | A
  | --- | ---
  | Bug fix? | yes
  | New feature? | yes
  | BC breaks? | no
  | Deprecations? | yes 
  | Fixed tickets | fixes https://github.com/sulu/sulu/issues/8624
  | Related issues/PRs | #
  | License | MIT
  | Documentation PR | sulu/sulu-docs#

  #### What's in this PR?

  - Fixed smart content providers (Article, Page, Snippet) not applying template XML `params` to query filters — params like `templateKeys` were ignored at runtime
  - Added `templateKeys` param support for filtering smart content by template key (replaces ambiguous `types` param for pages/snippets)
  - Added `groups` param for articles (replaces `types` which was ambiguous between article groups and template keys)
  - Deprecated `types` param (use `groups` for articles, `templateKeys` for pages/snippets) and `structureTypes` param (use `templateKeys`)
  - Added `ValidateSmartContentParamsPass` compiler pass that fails the container build when deprecated param names are found in template XML
  - Consolidated `applyParams` into `mapFilters` in Article, Page and Snippet providers; the internal `types` filter field is no longer emitted — the query layer only sees `templateKeys`
  - Hardcoded XML `<param>` values now intersect with admin-UI selections rather than overwrite them, so template-level filters can only tighten the result set
  - Added `ignoreWebspaces` param support in `WebspaceSmartContentFiltersVisitor` and `MediaSmartContentFiltersVisitor` to allow cross-webspace smart content queries
  - `SmartContentItemController` now normalizes and forwards params to providers
  - Content resolvers (`DimensionContentResolver`, `ExcerptTaxonomyResolver`, `SeoResolver`, `TemplateResolver`) now return `null` for configured property paths that don't exist on the content object, ensuring consistent API response keys

  #### Why?

  Smart content `params` defined in template XML (e.g. `<param name="templateKeys" value="default"/>`) were never passed through to the provider's `findFlatBy`/`findCountBy` methods. This meant template-level filtering by type or template key had no effect — the smart content always returned all items regardless of configured params. The compiler pass ensures developers are guided to the new param names during development rather than encountering silent runtime deprecations. The null-value fix ensures that content resolvers always return all requested property keys, even when the underlying content object doesn't have them.

  #### To Do

  - [ ] Create a documentation PR
  - [x] Add breaking changes to UPGRADE.md

### CODE REVIEW

File: packages/article/src/Infrastructure/Sulu/Content/ArticleSmartContentProvider.php [hunk 1]
```diff
@@ -185,8 +188,9 @@ public function countBy(array $filters, array $params = []): int
      */
     public function findFlatBy(array $filters, array $sortBys, array $params = []): array
     {
-        /** @var ArticleSmartContentFilters $filters */
         $filters = $this->enhanceWithDimensionAttributes($filters);
+        /** @var ArticleSmartContentFilters $filters */
+        $filters = $this->applyParams($filters, $params);
```
Comment (martinlagler) [inline packages/article/src/Infrastructure/Sulu/Content/ArticleSmartContentProvider.php]: I think it would be nice to also check in  `mapFilters()` if there are already `templateKeys` otherwise the `templateKeys` from the params will be overwritten if a group and templateKeys are defined.

File: packages/article/src/Infrastructure/Sulu/Content/ArticleSmartContentProvider.php [hunk 2]
```diff
@@ -263,7 +294,7 @@ protected function mapFilters(array $filters): array
                 }
             }
 
-            $filters['templateKeys'] = $templates;
+            $filters['templateKeys'] = \array_values(\array_unique(\array_merge($filters['templateKeys'] ?? [], $templates)));
```
Comment (martinlagler) [inline packages/article/src/Infrastructure/Sulu/Content/ArticleSmartContentProvider.php]: array_intersect instead of merge

File: packages/content/tests/Application/config/templates/examples/smart-content-tpl-param.xml [hunk 3]
```diff
@@ -0,0 +1,47 @@
...
+            <tag name="sulu.rlp"/>
+        </property>
+
+        <property name="examples_by_template" type="smart_content">
+            <meta>
+                <title lang="en">Examples filtered by template param</title>
+            </meta>
+            <params>
+                <param name="provider" value="examples"/>
+                <param name="template" value="default"/>
```
Comment (martinlagler) [inline packages/content/tests/Application/config/templates/examples/smart-content-tpl-param.xml]: Shouldn't it be `templateKeys` ?

**Comment by martinlagler** [comment]
@Prokyonn  Else it looks good for me.

**Review by wachterjohannes — APPROVED** [review]

**Comment by Prokyonn** [comment]
@Prokyonn TODO upgrade.md entry is missing

File: packages/content/src/Application/ContentResolver/Resolver/DimensionContentResolver.php [hunk 4]
```diff
@@ -35,6 +35,8 @@ public function resolve(DimensionContentInterface $dimensionContent, ?array $pro
         foreach ($properties as $key => $path) {
             if ($this->propertyAccessor->isReadable($dimensionContent, $path)) {
                 $data[$key] = $this->propertyAccessor->getValue($dimensionContent, $path);
+            } else {
+                $data[$key] = null;
```
Comment (alexander-schranz) [inline packages/content/src/Application/ContentResolver/Resolver/DimensionContentResolver.php]: Would prefer ternary or match here instead of a `else`:

```php
            $data[$key] = $this->propertyAccessor->isReadable($dimensionContent, $path)
                ? $this->propertyAccessor->getValue($dimensionContent, $path)
                : null;
```


```php
            $data[$key] = match(true) {
                $this->propertyAccessor->isReadable($dimensionContent, $path) => $this->propertyAccessor->getValue($dimensionContent, $path)
                default => null,
            };
```

File: packages/content/src/Application/ContentResolver/Resolver/ExcerptTaxonomyResolver.php [hunk 5]
```diff
@@ -72,7 +75,7 @@ public function resolve(DimensionContentInterface $dimensionContent, ?array $pro
         $resolvedItems = $this->metadataResolver->resolveItems($formMetadataItems, $data, $locale);
 
         return ContentView::create(
-            $this->normalizeResolvedItems($resolvedItems, $properties),
+            \array_merge($nullProperties, $this->normalizeResolvedItems($resolvedItems, $properties)),
```
Comment (alexander-schranz) [inline packages/content/src/Application/ContentResolver/Resolver/ExcerptTaxonomyResolver.php:78]: what about nesting, any requirement for recursive array replace?

File: packages/content/src/Application/ContentResolver/Resolver/SeoResolver.php [hunk 6]
```diff
@@ -67,7 +70,7 @@ public function resolve(DimensionContentInterface $dimensionContent, ?array $pro
         $resolvedItems = $this->metadataResolver->resolveItems($formMetadataItems, $data, $locale);
 
         return ContentView::create(
-            $this->normalizeResolvedItems($resolvedItems, $properties),
+            \array_merge($nullProperties, $this->normalizeResolvedItems($resolvedItems, $properties)),
```
Comment (alexander-schranz) [inline packages/content/src/Application/ContentResolver/Resolver/SeoResolver.php:73]: same as above is maybe recursive array replace required. here or not?

File: packages/content/src/Application/ContentResolver/Resolver/TemplateResolver.php [hunk 7]
```diff
@@ -69,7 +72,7 @@ public function resolve(DimensionContentInterface $dimensionContent, ?array $pro
         }
 
         return ContentView::create(
-            $this->metadataResolver->resolveItems($formMetadataItems, $data, $locale),
+            \array_merge($nullProperties, $this->metadataResolver->resolveItems($formMetadataItems, $data, $locale)),
```
Comment (alexander-schranz) [inline packages/content/src/Application/ContentResolver/Resolver/TemplateResolver.php:75]: same as above

File: packages/article/src/Infrastructure/Sulu/Content/ArticleSmartContentProvider.php [hunk 8]
```diff
@@ -216,6 +220,33 @@ public function findFlatBy(array $filters, array $sortBys, array $params = []):
...
+     * @return array<string, mixed>
+     */
+    protected function applyParams(array $filters, array $params): array
+    {
+        // Groups — article group identifiers
+        if (empty($filters['types'])) {
+            $groupsParam = $params['groups'] ?? null;
+
+            if (\is_string($groupsParam)) {
+                $filters['types'] = \array_filter(\array_map('trim', \explode(',', $groupsParam)));
```
Comment (alexander-schranz) [inline packages/article/src/Infrastructure/Sulu/Content/ArticleSmartContentProvider.php]: not understand why this is mapped to `types` and not to groups or templateKeys directly.

File: packages/article/src/Infrastructure/Sulu/Content/ArticleSmartContentProvider.php [hunk 9]
```diff
@@ -216,6 +220,33 @@ public function findFlatBy(array $filters, array $sortBys, array $params = []):
...
+    /**
+     * @param array<string, mixed> $filters
+     * @param array<string, mixed> $params
+     *
+     * @return array<string, mixed>
+     */
+    protected function applyParams(array $filters, array $params): array
+    {
+        // Groups — article group identifiers
+        if (empty($filters['types'])) {
```
Comment (alexander-schranz) [inline packages/article/src/Infrastructure/Sulu/Content/ArticleSmartContentProvider.php]: Not understanding this and `empty` should mostly be avoided. Keep in mind <param> filter are strict and website query params should not be allowed to remove that hardcoded filter if this is what check here. But must say I not understanding the logic here.

Need it be array_intersected here also?

File: packages/article/src/Infrastructure/Sulu/Content/ArticleSmartContentProvider.php [hunk 10]
```diff
@@ -216,6 +220,33 @@ public function findFlatBy(array $filters, array $sortBys, array $params = []):
...
+        }
+
+        // Template — direct template keys
+        $templateParam = $params['templateKeys'] ?? $params['template'] ?? $params['templateKey'] ?? null;
+
+        if (\is_string($templateParam)) {
+            $filters['templateKeys'] = \array_filter(\array_map('trim', \explode(',', $templateParam)));
+        }
+
+        return $filters;
```
Comment (alexander-schranz) [inline packages/article/src/Infrastructure/Sulu/Content/ArticleSmartContentProvider.php]: shouldnt the end result be templateKeys and array intersection? Not understand this method in general.

File: packages/article/src/Infrastructure/Sulu/Content/ArticleSmartContentProvider.php [hunk 11]
```diff
@@ -216,6 +220,33 @@ public function findFlatBy(array $filters, array $sortBys, array $params = []):
...
+        if (empty($filters['types'])) {
+            $groupsParam = $params['groups'] ?? null;
+
+            if (\is_string($groupsParam)) {
+                $filters['types'] = \array_filter(\array_map('trim', \explode(',', $groupsParam)));
+            }
+        }
+
+        // Template — direct template keys
+        $templateParam = $params['templateKeys'] ?? $params['template'] ?? $params['templateKey'] ?? null;
```
Comment (alexander-schranz) [inline packages/article/src/Infrastructure/Sulu/Content/ArticleSmartContentProvider.php]: We should only support one single param not mulitple for the same.

File: packages/article/src/Infrastructure/Sulu/Content/ArticleSmartContentProvider.php [hunk 12]
```diff
@@ -265,7 +296,11 @@ protected function mapFilters(array $filters): array
                 }
             }
 
-            $filters['templateKeys'] = $templates;
+            if (!empty($filters['templateKeys'])) {
```
Comment (alexander-schranz) [inline packages/article/src/Infrastructure/Sulu/Content/ArticleSmartContentProvider.php]: avoid `empty` it is unstrict check. if not required if else not even required if you do `$filters['templateKeys'] = \array_values(\array_intersect($filters['templateKeys'] ?? [], $templates));`

File: packages/article/src/Infrastructure/Sulu/Content/ArticleSmartContentProvider.php (hunk 1 above)
Comment (alexander-schranz) [inline packages/article/src/Infrastructure/Sulu/Content/ArticleSmartContentProvider.php]: kind of strange why is applyParams not just part of `mapFilters` method? we split here some logic which feels should be together?

File: src/Sulu/Bundle/AdminBundle/CacheWarmer/SmartContentParamsValidationWarmer.php [hunk 13]
```diff
@@ -0,0 +1,142 @@
...
+namespace Sulu\Bundle\AdminBundle\CacheWarmer;
+
+use Sulu\Bundle\AdminBundle\Metadata\FormMetadata\FieldMetadata;
+use Sulu\Bundle\AdminBundle\Metadata\FormMetadata\ItemMetadata;
+use Sulu\Bundle\AdminBundle\Metadata\FormMetadata\Loader\TemplateXmlLoader;
+use Sulu\Bundle\AdminBundle\Metadata\FormMetadata\SectionMetadata;
+use Symfony\Component\Finder\Finder;
+use Symfony\Component\HttpKernel\CacheWarmer\CacheWarmerInterface;
+
+class SmartContentParamsValidationWarmer implements CacheWarmerInterface
```
Comment (alexander-schranz) [inline src/Sulu/Bundle/AdminBundle/CacheWarmer/SmartContentParamsValidationWarmer.php]: mark as `@internal`

File: src/Sulu/Bundle/AdminBundle/CacheWarmer/SmartContentParamsValidationWarmer.php [hunk 14]
```diff
@@ -0,0 +1,142 @@
...
+/*
+ * This file is part of Sulu.
+ *
+ * (c) Sulu GmbH
+ *
+ * This source file is subject to the MIT license that is bundled
+ * with this source code in the file LICENSE.
+ */
+
+namespace Sulu\Bundle\AdminBundle\CacheWarmer;
```
Comment (alexander-schranz) [inline src/Sulu/Bundle/AdminBundle/CacheWarmer/SmartContentParamsValidationWarmer.php]: does it only handle article bundle? should be part of article bundle.

Old bundles I would see this as part `Sulu/Bundle/AdminBundle/DependencyInjection/CacheWarmer`.

New Bundles more as part of `Sulu\Article\Infrastructure\Symfony\HttpKernel\CacheWarmer`

File: src/Sulu/Bundle/AdminBundle/CacheWarmer/SmartContentParamsValidationWarmer.php (hunk 13 above)
Comment (alexander-schranz) [inline src/Sulu/Bundle/AdminBundle/CacheWarmer/SmartContentParamsValidationWarmer.php]: it not really warms something so more would go with:

`SmartContentParamsValidator`

File: src/Sulu/Bundle/AdminBundle/CacheWarmer/SmartContentParamsValidationWarmer.php [hunk 15]
```diff
@@ -0,0 +1,142 @@
...
+    public function __construct(
+        private TemplateXmlLoader $templateXmlLoader,
+        private array $templateDirectories,
+    ) {
+    }
+
+    public function isOptional(): bool
+    {
+        return false;
+    }
```
Comment (alexander-schranz) [inline src/Sulu/Bundle/AdminBundle/CacheWarmer/SmartContentParamsValidationWarmer.php]: would return true here.

File: src/Sulu/Bundle/AdminBundle/CacheWarmer/SmartContentParamsValidationWarmer.php (hunk 13 above)
Comment (alexander-schranz) [inline src/Sulu/Bundle/AdminBundle/CacheWarmer/SmartContentParamsValidationWarmer.php]: why do this as a Warmer? Not as a compilerpass, would move this to a compilerpass so this this not require to be a service in the container build.

**Review by alexander-schranz — CHANGES_REQUESTED** [review]
did a quick review, not yet 100% understand the whole code:

File: packages/content/src/Application/ContentResolver/Resolver/ExcerptTaxonomyResolver.php (hunk 5 above)
Comment (Prokyonn) [reply packages/content/src/Application/ContentResolver/Resolver/ExcerptTaxonomyResolver.php:78]: I don't think so, when we have the property
`['foo' => 'excerpt.example.test']` and the path doesn't exist, we would just need to write `'foo' => null` and for `['excerpt/nested/foo' => 'excerpt.example.test']` the same would apply `'excerpt/nested/foo' => null`

Although thinking about this, even when excerpt.example.test would be an actual value, it won't work at all, because we do not use PropertyAccessor in the excerpt/seo resolvers, but I think this issue is out of scope of this PR

File: src/Sulu/Bundle/AdminBundle/CacheWarmer/SmartContentParamsValidationWarmer.php (hunk 14 above)
Comment (Prokyonn) [reply src/Sulu/Bundle/AdminBundle/CacheWarmer/SmartContentParamsValidationWarmer.php]: It is about all smart contents, I converted it to a Compilerpass now, that lives in the adminbundle and handles page/snippet/articles, if we split it up, we would need to duplicate most of the code and also read the templates multiple times, not sure if this is really worth it

File: packages/content/src/Application/ContentResolver/Resolver/ExcerptTaxonomyResolver.php (hunk 5 above)
Comment (alexander-schranz) [reply packages/content/src/Application/ContentResolver/Resolver/ExcerptTaxonomyResolver.php:78]: fine then for me.

File: packages/article/src/Infrastructure/Sulu/Content/ArticleSmartContentProvider.php (hunk 10 above)
Comment (Prokyonn) [reply packages/article/src/Infrastructure/Sulu/Content/ArticleSmartContentProvider.php]: fixed it

**Review by alexander-schranz — APPROVED** [review]
