### PR TITLE
fixed localization of sitemaps

### LINKED ISSUE #3163: Wrong SEO Information for hreflang tag
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | 1.4.2

#### Actual Behavior

When using the `SuluWebsiteBundle:Extension.seo.html.twig` file to display meta information for the page, the `<link rel="alternate"...` information is wrong when the page has multiple locales.

There's also printed one `<link rel="alternate"...` tag for the current language + the x-default link.

#### Expected Behavior

That the meta information is correct and no alternate tag for the current locale is defined, except the x-default link.

#### Steps to Reproduce

Use the `seo.html.twig` file:

```twig
{%- embed 'SuluWebsiteBundle:Extension:seo.html.twig' with {
        seo: extension.seo,
        content: content,
        urls: urls|default([]),
        shadowBaseLocale: shadowBaseLocale|default(''),
        defaultLocale: request.defaultLocale|default('')
    } -%}
```

#### Possible Solutions

Instead of

```twig
{%- if urls|length > 1 -%}
    {%- for locale, url in urls -%}
        {%- if defaultLocale == locale -%}
            <link rel="alternate" href="{{ sulu_content_path(url, null, locale) }}" hreflang="x-default"/>
        {%- endif -%}
        <link rel="alternate" href="{{ sulu_content_path(url, null, locale) }}" hreflang="{{ locale }}"/>
    {%- endfor -%}
{%- endif -%}
```

This could be the solution:

```twig
{%- if urls|length > 1 -%}
    {%- for locale, url in urls if locale != app.request.locale -%}
        <link rel="alternate" href="{{ sulu_content_path(url, null, locale) }}" hreflang="{{ locale }}"/>
    {%- endfor -%}
    <link rel="alternate" href="{{ sulu_content_path(urls[defaultLocale], null, defaultLocale) }}" hreflang="x-default"/>
{%- endif -%}
```

### LINKED ISSUE #3187: Missing entries in Sitemap for pages not created in default locale
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | Tested with 1.4.2 and current develop (including #743a78bdb2bf6140703df8f1583a5601daa890bc)

#### Actual Behavior

When creating a page **not** in the default locale, it won't appear in the sitemap.

#### Expected Behavior

The page should appear in the sitemap.

#### Steps to Reproduce

1. Check what you default locale is (in my example `de`)
2. Add another language to the project (in my example `en`)
3. Create and publish a page in `en` (in another locale than the default one)
4. Check the sitemap - the page isn't there.
5. To check: Save the just created page in the default locale and it will appear in the sitemap.

### PR DESCRIPTION
**Pull request by danrot**
| Q | A
| --- | ---
| Bug fix? | yes
| New feature? | no
| BC breaks? | no
| Deprecations? | no
| Fixed tickets | fixes #3187, fixes #3163 
| Related issues/PRs | #2916 
| License | MIT
| Documentation PR | https://github.com/sulu/sulu-docs/pull/346

#### What's in this PR?

This PR adds all localizations as separate URLs to the sitemap, which was changed back in version 1.5.

### CODE REVIEW

**Comment by danrot** [comment]
@wachterjohannes @alexander-schranz Can one of you check if this is working for you?

File: src/Sulu/Bundle/WebsiteBundle/Sitemap/SitemapUrl.php [hunk 1]
```diff
@@ -68,9 +73,10 @@ class SitemapUrl
      * @param string $changefreq
      * @param float $priority
      */
-    public function __construct($loc, \DateTime $lastmod = null, $changefreq = null, $priority = null)
+    public function __construct($loc, $locale, \DateTime $lastmod = null, $changefreq = null, $priority = null)
```
Comment (danrot) [inline src/Sulu/Bundle/WebsiteBundle/Sitemap/SitemapUrl.php]: @chirimoya @wachterjohannes That's the parameter I've been talking about. It should be mandatory, because based on it the URL in the twig template is generated. I could move it to the very end, which would also be a BC break. Except we don't make this parameter mandatory, but I think that's not the way to go.

File: src/Sulu/Bundle/WebsiteBundle/Sitemap/Provider/PagesSitemapProvider.php [hunk 2]
```diff
@@ -30,27 +31,43 @@ class PagesSitemapProvider implements SitemapProviderInterface
...
+        WebspaceManagerInterface $webspaceManager
+    ) {
         $this->contentRepository = $contentRepository;
+        $this->webspaceManager = $webspaceManager;
     }
 
     /**
      * {@inheritdoc}
      */
     public function build($page, $portalKey, $locale)
```
Comment (danrot) [inline src/Sulu/Bundle/WebsiteBundle/Sitemap/Provider/PagesSitemapProvider.php]: The `$locale` parameter here is not used anymore, because the provider has to return the `SitemapUrl`s for all locales. We could still leave it like that, then there would be no BC break in this method, and all existing providers would continue to work (although they would not work correctly, because they should return all locales).

So the question is if we just deprecate this parameter, or remove it completely, so that everybody updating has to touch their code (which would be a good idea anyway, because it's not working as it should - so I am favoring this option, although it is a BC break).

Comment (chirimoya) [inline src/Sulu/Bundle/WebsiteBundle/Sitemap/Provider/PagesSitemapProvider.php]: +1 for BC

File: src/Sulu/Bundle/WebsiteBundle/Sitemap/SitemapUrl.php (hunk 1 above)
Comment (chirimoya) [inline src/Sulu/Bundle/WebsiteBundle/Sitemap/SitemapUrl.php]: ack

File: src/Sulu/Bundle/WebsiteBundle/Resources/views/Sitemap/sitemap.xml.twig [hunk 3]
```diff
@@ -4,37 +4,40 @@
...
+                {% if entry.changefreq %}
+                <changefreq>{{ entry.changefreq }}</changefreq>
+                {% endif %}
+                {% if entry.priority %}
+                <priority>{{ entry.priority }}</priority>
+                {% endif %}
+
+                {% set amount = 0 %}
+                {% set defaultHref = null %}
+                {% if entry.alternateLinks|length > 1 %}
```
Comment (alexander-schranz) [inline src/Sulu/Bundle/WebsiteBundle/Resources/views/Sitemap/sitemap.xml.twig]: I'm not sure about this. I had the problem that I created a `new SitemapUrl()` as locale `en` added an alternative `de` and then it didn't got displayed, because the SitemapUrl need itself also as alternative. Maybe automatically create itself as alternative in the SitemapUrl constructor to avoid this pitfall?

Comment (alexander-schranz) [inline src/Sulu/Bundle/WebsiteBundle/Resources/views/Sitemap/sitemap.xml.twig]: maybe this would avoid to add itself as alternate so an custom provider dont need to handle it:

```twig
{% if entry.alternateLinks|length > 0 %} {# this if can maybe removed then? #}
    {% for alternateLink in entry.alternateLinks if alternateLink.locale != entry.locale %}
        {# ... #}
    {% endfor %}
{% endif %}

{% if amount > 0 %}
    <xhtml:link rel="alternate" hreflang="{{ entry.locale|replace({'_': '-'}) }}" href="{{ location }}"/>
    {% if defaultHref %}
        <xhtml:link rel="alternate" hreflang="x-default" href="{{ defaultHref }}"/>
    {% endif %}
{% endif %}
```

Comment (danrot) [inline src/Sulu/Bundle/WebsiteBundle/Resources/views/Sitemap/sitemap.xml.twig]: Fixed it by automatically adding the alternate link in the constructor of the sitemap url.
