### PR TITLE
Fix missing translations in admin search box dropdown

### LINKED ISSUE #6763: Missing translations in admin search dropdown
| Q | A
| --- | ---
| Sulu Version | 2.5
| PHP Version | 8.1.6

# Actual Behavior

Admin search dropdown is not translated to user locale. 

# Possible Solutions

Pass locale query parameter to URL should solve this issue:

Current url:
/admin/search/indexes?flat=true

Possible solution:
/admin/search/indexes?flat=true&locale=de

### PR DESCRIPTION
**Pull request by cpoint-eu**
| Q | A
| --- | ---
| Bug fix? | yes
| New feature? | no
| BC breaks? | no
| Deprecations? | no
| Fixed tickets | fixes #6763
| Related issues/PRs | -
| License | MIT
| Documentation PR | -

#### What's in this PR?

Transferring index configuration processing logic from the constructor to the getIndexConfiguration() method due to false locale.

#### Why?

Text translations in the admin search box dropdown are not working properly.

### CODE REVIEW

**Comment by alexander-schranz** [comment]
Thx for the pull request. Can you rebase this to 2.4 as there I think the bug also appears and we still provide bugfixes for 2.4.

Also the `getIndexConfiguration($name)` need to be adjusted as it currently will fail when the first method was never called before. See example in the comment: https://github.com/sulu/sulu/issues/6763#issuecomment-1203691844.

**Comment by alexander-schranz** [comment]
@cpoint-eu you can rebase your branch to 2.4 this way:

```
# clone repository
git clone git@github.com:cpoint-eu/sulu.git
cd sulu

# checkout your branch
git fetch origin
git checkout bugfix/missing-admin-search-box-dropdown-translations

# add sulu remote
git remote add sulu git@github.com:sulu/sulu.git
git fetch sulu

# rebase from 2.5 to 2.4
git rebase -i sulu/2.5 --onto sulu/2.4

# force push your changes as we did rewrite the git history
git push origin bugfix/missing-admin-search-box-dropdown-translations --force
```

After that you can change the target branch here to 2.4

**Comment by cpoint-eu** [comment]
Now it should be fixed. Sorry for the confusion with the pull requests, it's a new experience for me. I hope it will be better in the future... Thanks for the instructions

#6769 - This should be closed

File: src/Sulu/Bundle/SearchBundle/Search/Configuration/IndexConfigurationProvider.php [hunk 1]
```diff
@@ -56,6 +71,8 @@ public function getIndexConfigurations()
      */
     public function getIndexConfiguration($name)
     {
+        $this->indexConfigurations = $this->getIndexConfigurations();
+
```
Comment (alexander-schranz) [inline src/Sulu/Bundle/SearchBundle/Search/Configuration/IndexConfigurationProvider.php]: we should use a local variable here:

```php
        $indexConfigurations = $this->getIndexConfigurations();

        if (!\array_key_exists($name, $indexConfigurations)) {
            return;
        }

        return $indexConfigurations[$name];
```

Else the static code analyzer will fail as it thinks $this->indexConfigurations can be null and so will throw a error on array_key_exists.

**Review by alexander-schranz — APPROVED** [review]

**Comment by alexander-schranz** [comment]
@cpoint-eu Thank you!
