### PR TITLE
Accept zero as valid latitude and longitude in Location component

### LINKED ISSUE #5389: when adding a location on a map with a lat or long of 0 you can't save it
| Q | A
| --- | ---
| Sulu Version | 2.1.0
| Browser Version | latest Chrome

# Actual Behavior
You can't save a location on a map when the lat or long is 0.

# Expected Behavior
you should be able to add a location with 0 in one or both of these fields.

# Steps to Reproduce
type a '0' in the lat or location field

# Possible Solutions
the location lat 0 long 0 is also a locations so pick that as default and just allow a 0 in the fields.

### PR DESCRIPTION
**Pull request by nnatter**
| Q | A
| --- | ---
| Bug fix? | yes
| New feature? | no
| BC breaks? | no
| Deprecations? | no
| Fixed tickets | fixes #5389
| License | MIT

#### What's in this PR?

This PR adjusts the overlay of the `Location` component to accept 0 as valid latitude and valid longitude.

### CODE REVIEW

**Comment by alexander-schranz** [comment]
@nnatter looks for me like this should target release/2.0 branch?

**Comment by nnatter** [comment]
you are right 🙂

File: src/Sulu/Bundle/LocationBundle/Resources/js/containers/Location/LocationOverlay.js [hunk 1]
```diff
@@ -179,7 +179,8 @@ class LocationOverlay extends React.Component<Props> {
         } = this.props;
 
         // enable confirm button if all marker properties are set or no property is set in case of a reset
-        const confirmEnabled = (this.markerLat && this.markerLong) || (!this.markerLat && !this.markerLong);
+        const confirmEnabled = (this.markerLat !== null && this.markerLong !== null)
```
Comment (alexander-schranz) [inline src/Sulu/Bundle/LocationBundle/Resources/js/containers/Location/LocationOverlay.js:182]: This seems not be enough if I reopen the overlay the data is not there. So it seems like there is another check change needed where the data is stored.

Comment (nnatter) [reply src/Sulu/Bundle/LocationBundle/Resources/js/containers/Location/LocationOverlay.js:180]: you are right - should hopefully be fixed now 🙂

**Comment by alexander-schranz** [comment]
@nnatter Did work this way as it should 👍
