### PR TITLE
save contact-/account-documents by header save-buton

### LINKED ISSUE #2679: Document can't be assigned to contacts/accounts
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | 6e7816186b82c3b3072f85c04c550dbbaca09efb
| Browser Version | ---

#### Actual Behavior

When you try to add a document to a contact or account it doesn't work. As soon as you click the blue apply button in the overlay, the overlay closes but there is nothing assigned.

#### Expected Behavior

Images or documents should be assigned after clicking the blue apply button.

#### Steps to Reproduce

1. Navigate to a contact
2. Switch to the document tab
3. Click on the plus button of the document list
4. Choose some images and click apply
5. The overlay is gone, but nothing appears in the list.

### PR DESCRIPTION
**Pull request by nnatter**
| Q | A
| --- | ---
| Bug fix? | no
| New feature? | no
| BC breaks? | no
| Deprecations? | no
| Fixed tickets | fixes #2679
| Related issues/PRs | https://github.com/massiveart/husky/pull/700
| License | MIT
| Documentation PR | -

#### What's in this PR?

This PR implements document-saving in contact bundle by header button.
Until now, documents were saved right after adding or removing. With this PR, they can be edited locally and saved by the save-button in the header-toolbar.

To avoid multiple requests when saving, the rest-api got adjusted to replace the whole mediaId collection of a contact/account on PUT.

To simplify the local editing, the datagrid got enhanced with two additional events.

#### Why?

The media selection in the document tab was not working anymore. Also saving by save-button adds consistency.

### CODE REVIEW

File: src/Sulu/Bundle/ContactBundle/Controller/AbstractMediaController.php [hunk 1]
```diff
@@ -137,6 +137,54 @@ protected function removeMediaFromEntity($entityName, $id, $mediaId)
...
+            $view = $this->view(null, 200);
+        } catch (EntityNotFoundException $enfe) {
+            $view = $this->view($enfe->toArray(), 404);
+        } catch (RestException $exc) {
+            $view = $this->view($exc->toArray(), 400);
+        } catch (\Exception $e) {
+            $view = $this->view($e->getMessage(), 400);
+        }
+
+        return $this->handleView($view);
```
Comment (nnatter) [inline src/Sulu/Bundle/ContactBundle/Controller/AbstractMediaController.php]: should we return a list representation of the medias here?

File: src/Sulu/Bundle/ContactBundle/Controller/AccountMediaController.php [hunk 2]
```diff
@@ -49,6 +49,20 @@ public function postAction($id, Request $request)
...
 
     /**
+     * Replaces the medias of the account.
+     *
+     * @param $id
+     * @param \Symfony\Component\HttpFoundation\Request $request
+     *
+     * @return \Symfony\Component\HttpFoundation\Response
+     */
+    public function putAction($id, Request $request)
```
Comment (nnatter) [inline src/Sulu/Bundle/ContactBundle/Controller/AccountMediaController.php]: this leads to the api interface:
GET| /api/accounts/1/medias | content: mediaIds | returns the medias which are assigned to account 1 as list
PUT | /api/accounts/1/medias | content: mediaIds | sets the medias of the account 1 to the mediaIds of the request body
POST | /api/accounts/1/medias | content: mediaId | adds the media with the id of the request body to the account 1
DELETE| /api/accounts/1/medias/2 | content: empty | removes the media with the id 2 from the account 1

File: src/Sulu/Bundle/ContactBundle/Controller/AbstractMediaController.php [hunk 3]
```diff
@@ -137,6 +137,54 @@ protected function removeMediaFromEntity($entityName, $id, $mediaId)
...
+
+            if (!$entity) {
+                throw new EntityNotFoundException($entityName, $id);
+            }
+
+            $mediaEntityName = $this->getParameter('sulu.model.media.class');
+
+            $foundMediaIds = array_map(function ($media) {
+                return $media->getId();
+            }, $medias);
```
Comment (danrot) [inline src/Sulu/Bundle/ContactBundle/Controller/AbstractMediaController.php]: the `function` and `$medias` should go into their own lines

File: src/Sulu/Bundle/ContactBundle/Controller/AccountMediaController.php [hunk 4]
```diff
@@ -49,6 +49,20 @@ public function postAction($id, Request $request)
...
+    {
+        return $this->setMediasOfEntity(
+            $this->getAccountEntityName(), $id, $request->get('mediaIds', []));
```
Comment (danrot) [inline src/Sulu/Bundle/ContactBundle/Controller/AccountMediaController.php]: Closing bracket should go into next line

File: src/Sulu/Bundle/ContactBundle/Controller/AccountMediaController.php (hunk 2 above)
Comment (danrot) [inline src/Sulu/Bundle/ContactBundle/Controller/AccountMediaController.php]: Was this discussed with @chirimoya ?

File: src/Sulu/Bundle/ContactBundle/Resources/public/js/services/account-manager.js [hunk 5]
```diff
@@ -439,6 +439,32 @@ define([
...
 
         /**
+         * Sets medias to an account. Currently associated medias get replaced.
+         * @param mediaIds medias to associate with the contact
+         * @param accountId The account to set the medias to
+         */
+        setDocuments: function(accountId, mediaIds) {
+            var promise = $.Deferred();
+
+            Util.ajax({
```
Comment (danrot) [inline src/Sulu/Bundle/ContactBundle/Resources/public/js/services/account-manager.js]: We decided to simply use `$.ajax`.

File: src/Sulu/Bundle/ContactBundle/Resources/public/js/services/account-manager.js [hunk 6]
```diff
@@ -439,6 +439,32 @@ define([
...
+                url: '/admin/api/accounts/' + accountId + '/medias',
+                data: {mediaIds: mediaIds},
+                type: 'PUT',
+
+                success: function() {
+                    Mediator.emit('sulu.contacts.account.documents.saved', accountId, mediaIds);
+                    Mediator.emit('sulu.labels.success.show', 'contact.accounts.documents-saved');
```
Comment (danrot) [inline src/Sulu/Bundle/ContactBundle/Resources/public/js/services/account-manager.js]: I guess these events are also already emitted in other parts of this manager, right? I am asking because they should actually not be emitted here 😕

File: src/Sulu/Bundle/ContactBundle/Controller/AccountMediaController.php (hunk 2 above)
Comment (nnatter) [inline src/Sulu/Bundle/ContactBundle/Controller/AccountMediaController.php]: @danrot: yes, but we are open for a better solution.

File: src/Sulu/Bundle/ContactBundle/Resources/public/js/services/account-manager.js (hunk 6 above)
Comment (nnatter) [inline src/Sulu/Bundle/ContactBundle/Resources/public/js/services/account-manager.js]: @danrot: Yes. Both, account-manager.js and contact-manager.js, are emitting label events in every essential method.

File: src/Sulu/Bundle/ContactBundle/Controller/AbstractMediaController.php [hunk 7]
```diff
@@ -137,6 +137,57 @@ protected function removeMediaFromEntity($entityName, $id, $mediaId)
     }
 
     /**
+     * Sets the medias which are associated with an entity to the given mediaIds.
+     *
+     * @param string $entityName
+     * @param string $id
+     * @param string $mediaIds
+     *
+     * @return \Symfony\Component\HttpFoundation\Response
```
Comment (danrot) [inline src/Sulu/Bundle/ContactBundle/Controller/AbstractMediaController.php]: Please `use` this class and use the short name here.

File: src/Sulu/Bundle/ContactBundle/Controller/AbstractMediaController.php (hunk 1 above)
Comment (danrot) [inline src/Sulu/Bundle/ContactBundle/Controller/AbstractMediaController.php]: Probably, as explained in https://github.com/massiveart/husky/pull/700#discussion_r73294951

File: src/Sulu/Bundle/ContactBundle/Controller/AccountMediaController.php [hunk 8]
```diff
@@ -49,6 +49,19 @@ public function postAction($id, Request $request)
     }
 
     /**
+     * Replaces the medias of the account.
+     *
+     * @param $id
+     * @param \Symfony\Component\HttpFoundation\Request $request
+     *
+     * @return \Symfony\Component\HttpFoundation\Response
```
Comment (danrot) [inline src/Sulu/Bundle/ContactBundle/Controller/AccountMediaController.php]: Also short names for `@param` and `@return`.

File: src/Sulu/Bundle/ContactBundle/Controller/AccountMediaController.php (hunk 2 above)
Comment (danrot) [inline src/Sulu/Bundle/ContactBundle/Controller/AccountMediaController.php]: I think `PUT` should actually not be used on end points without an ID (http://restcookbook.com/HTTP%20Methods/put-vs-post/).

I think the only way to do this restful with one request is to send the data to `/api/accounts/1` as a `PUT` request with all the contact data. We are e.g. also handling the content like this (if you save the excerpt tab of a page also the entire page is sent).

Comment (danrot) [inline src/Sulu/Bundle/ContactBundle/Controller/AccountMediaController.php]: Or we are implementing the `PATCH` method, completely forgot about that 😃

Comment (danrot) [inline src/Sulu/Bundle/ContactBundle/Controller/AccountMediaController.php]: We decided to use `PATCH`, as described in this article: http://williamdurand.fr/2014/02/14/please-do-not-patch-like-an-idiot/

File: src/Sulu/Bundle/ContactBundle/Resources/translations/sulu/backend.fr.xlf [hunk 9]
```diff
@@ -598,6 +602,10 @@
                 <source>contact.contacts.document-added</source>
                 <target>Document ajouté</target>
             </trans-unit>
+            <trans-unit id="435b1472d76660a3e3z5e2e9335a8d5d" resname="contact.contacts.documents-saved">
+                <source>contact.contacts.documents-saved</source>
+                <target>Documents sauvegardé</target>
+            </trans-unit>
```
Comment (danrot) [inline src/Sulu/Bundle/ContactBundle/Resources/translations/sulu/backend.fr.xlf]: Can you maybe also get the dutch translations?
