### PR TITLE
Fixed remove selected webspace-locale

### LINKED ISSUE #2179: CustomURL fails if language does not exist in webspace anymore
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | 305f73897cd027c4b9a67df65bf6f0fd12aec543

Related to https://github.com/sulu-io/sulu/issues/2160

#### Actual Behavior

If a custom url is generated for a non-existing localizations, the following error appears:

This problem was fixed in #2169, but somehow it still persists. Namely if a custom url exists, and the chosen localization is removed from the webspace later.

#### Expected Behavior

It should at least throw a clear exception, and not a catchable fatal error. In production it should display a 404 page (?)

#### Steps to Reproduce

1. Create a new custom url in any language
2. Remove this language from the webspace
3. Try to access the created custom url

### PR DESCRIPTION
**Pull request by wachterjohannes**
| Q | A
| --- | ---
| Bug fix? | yes
| New feature? | no
| BC breaks? | no
| Deprecations? | no
| Fixed tickets | fixes #2179
| Related issues/PRs | https://github.com/massiveart/husky/pull/626
| License | MIT
| Documentation PR |

#### What's in this PR?

This PR adds an additional check if the localization exists. if not it returns a empty route collection. which last into a 404 error.

#### Why?

If you create a custom-url and remove the target locale from the webspace it throws a 500 error when you browse the custom-url.

### CODE REVIEW

File: src/Sulu/Bundle/CustomUrlBundle/Request/CustomUrlRequestProcessor.php [hunk 1]
```diff
@@ -162,6 +162,14 @@ private function matchCustomUrl($url, PortalInformation $portalInformation, Requ
             $this->environment
         );
 
+        if (0 === count($portalInformations)) {
+            return $this->processPortalInformation(
+                $request,
+                $portalInformation,
+                ['customUrlRoute' => $routeDocument, 'customUrl' => $customUrlDocument]
+            );
+        }
```
Comment (danrot) [inline src/Sulu/Bundle/CustomUrlBundle/Request/CustomUrlRequestProcessor.php]: What is this change doing?

Comment (wachterjohannes) [inline src/Sulu/Bundle/CustomUrlBundle/Request/CustomUrlRequestProcessor.php]: it tells the custom-url route-provider that there is a custom-url for given URL. Then the provider can check if it is valid or not.
