### PR TITLE
Fix sitemap provider tags definition

### LINKED ISSUE #4865: Creating own Sitemap provider breaks admin interface.
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | 2.0.1
| Browser Version | irrelevant

#### Actual Behavior

If is registered own sitemap provider, admin interface fails with:
`Warning: Invalid argument supplied for foreach()`
`In ResolveInstanceofConditionalsPass.php line 121`
Issue is with this line of code
https://github.com/sulu/sulu/blob/d7b430ceaabdc3f221ff795124b01fe6db036912/src/Sulu/Bundle/WebsiteBundle/DependencyInjection/SuluWebsiteExtension.php#L110

#### Expected Behavior

Creating own Sitemap providers does not break admin.

#### Steps to Reproduce

Create new Sitemap Provider via https://docs.sulu.io/en/2.0/cookbook/sitemap-provider.html and try to access admin interface.

#### Possible Solutions

Line of code mentioned above change either to `->setTags(['sulu.sitemap.provider' => []]);` or `->addTag('sulu.sitemap.provider');`

### PR DESCRIPTION
**Pull request by HadGS**
| Q | A
| --- | ---
| Bug fix? | yes
| New feature? | no
| BC breaks? | no
| Deprecations? | no
| Fixed tickets | fixes #4865 
| License | MIT

#### What's in this PR?

Fix sitemap provider tags definition.

#### Why?

Because currently custom sitemap provider breaks admin interface.

### CODE REVIEW

File: src/Sulu/Bundle/WebsiteBundle/DependencyInjection/SuluWebsiteExtension.php [hunk 1]
```diff
@@ -107,7 +107,7 @@ public function load(array $configs, ContainerBuilder $container)
             $config['sitemap']['dump_dir']
         );
         $container->registerForAutoconfiguration(SitemapProviderInterface::class)
-            ->setTags(['sulu.sitemap.provider']);
+            ->setTags(['sulu.sitemap.provider' => []]);
```
Comment (alexander-schranz) [inline src/Sulu/Bundle/WebsiteBundle/DependencyInjection/SuluWebsiteExtension.php]: This shoud be `addTag('sulu.sitemap.provider')`

**Comment by alexander-schranz** [comment]
@HadGS  Thank you did test it and it works for me. Just waiting for the CI to finish it.

**Comment by alexander-schranz** [comment]
@HadGS Thank you will be relased in 2.0.2
