### PR TITLE
Ignore wrong template exception

### LINKED ISSUE #3808: Changing a snippets template leads to an exception when asinged to webspace
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | 1.6.13

#### Actual Behavior

When I create a snipped with a custom template and asinged it to a webspace in the settings > snipped tab everything is fine.
When I change the template of the asinged snipped and the change to the webspace settings > snipped tab nothing appears and the log shows the following error.

`[2018-02-28 10:20:41] request.CRITICAL: Uncaught PHP Exception Sulu\Bundle\SnippetBundle\Snippet\WrongSnippetTypeException: "Wrong snippet type were detected (actual: "navigation_footer_group", expected: "navigation_footer")." at [web-root]/vendor/sulu/sulu/src/Sulu/Bundle/SnippetBundle/Snippet/DefaultSnippetManager.php line 114 {"exception":"[object] (Sulu\\Bundle\\SnippetBundle\\Snippet\\WrongSnippetTypeException(code: 0): Wrong snippet type were detected (actual: \"navigation_footer_group\", expected: \"navigation_footer\"). at [web-root]/vendor/sulu/sulu/src/Sulu/Bundle/SnippetBundle/Snippet/DefaultSnippetManager.php:114)"} []
`

#### Expected Behavior

And error message in the backend and the possibility to correct the template

### PR DESCRIPTION
**Pull request by wachterjohannes**
| Q | A
| --- | ---
| Bug fix? | no
| New feature? | no
| BC breaks? | no
| Deprecations? | no
| Fixed tickets | #3808
| Related issues/PRs | none
| License | MIT
| Documentation PR | none

#### What's in this PR?

This PR fixes #3808

#### Why?

see #3808

#### TODO

- [x] Tests

### CODE REVIEW

File: src/Sulu/Bundle/SnippetBundle/Controller/SnippetAreaController.php [hunk 1]
```diff
@@ -54,11 +55,17 @@ public function cgetAction(Request $request)
...
                 'title' => $area['title'],
+                'defaultUuid' => null,
+                'defaultTitle' => null,
             ];
 
-            $snippet = $defaultSnippetManager->load($webspaceKey, $key, $this->getUser()->getLocale());
-            $areaData['defaultUuid'] = $snippet ? $snippet->getUuid() : null;
-            $areaData['defaultTitle'] = $snippet ? $snippet->getTitle() : null;
+            try {
+                $snippet = $defaultSnippetManager->load($webspaceKey, $key, $this->getUser()->getLocale());
```
Comment (alexander-schranz) [inline src/Sulu/Bundle/SnippetBundle/Controller/SnippetAreaController.php]: @wachterjohannes should we not just avoid the load request if webspaceKey is empty?

Comment (wachterjohannes) [reply src/Sulu/Bundle/SnippetBundle/Controller/SnippetAreaController.php]: the webspace-key is mandatory - the problem is, that the loaded snippet is from the wrong type. I will add in this PR that there is a wrong snippet selected  so that we can show an error message in the javascript part.

Comment (alexander-schranz) [reply src/Sulu/Bundle/SnippetBundle/Controller/SnippetAreaController.php]: Should we not remove it from the default snippet when a template switch was done?

Comment (wachterjohannes) [reply src/Sulu/Bundle/SnippetBundle/Controller/SnippetAreaController.php]: i am not sure - because the information that there is something (invalid) selected is gone forever. @danrot @chirimoya what do you think?

Comment (alexander-schranz) [reply src/Sulu/Bundle/SnippetBundle/Controller/SnippetAreaController.php]: @wachterjohannes ok thinking about it again we should probably show it in the UI under default snippets that there need to be choose a new snippet or?

**Comment by alexander-schranz** [comment]
@wachterjohannes do we also need to catch something in a content type where default snippet is active?

File: src/Sulu/Bundle/SnippetBundle/Controller/SnippetAreaController.php (hunk 1 above)
Comment (danrot) [reply src/Sulu/Bundle/SnippetBundle/Controller/SnippetAreaController.php]: I am not really sure what the ideal solution here is... Maybe warn when deleting the snippet? I think we already do something similar when deleting the snippet.

**Comment by wachterjohannes** [comment]
@chirimoya @danrot i have added the error message

**Comment by wachterjohannes** [comment]
@danrot now this is ready
