### PR TITLE
removed translation import command and refactored translate bundle

### LINKED ISSUE #2569: Override sulu-core translations
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | latest dev/sulu minimal

#### Actual Behavior

I tried to override some translation which is set inside a sulu vendor bundle (here blog bundle).
So inside my own bundle i added the translation and tried to generate the translations. I got this exception:
`

        Successfully imported files from bundles to Sulu Database!

    sulu:translate:export  ({"locale":"de"})

          [InvalidArgumentException]
          navigation.blog, translation-code seems to come up multiple times

        Exception trace:
         () at /var/www/sulu-minimal/vendor/sulu/sulu/src/Sulu/Bundle/TranslateBundle/Translate/Export.php:272
         Sulu\Bundle\TranslateBundle\Translate\Export->execute() at /var/www/sulu-minimal/vendor/sulu/sulu/src/Sulu/Bundle/TranslateBundle/Command/ExportCommand.php:121
         Sulu\Bundle\TranslateBundle\Command\ExportCommand->execute() at /var/www/sulu-minimal/vendor/symfony/symfony/src/Symfony/Component/Console/Command/Command.php:259
         Symfony\Component\Console\Command\Command->run() at /var/www/sulu-minimal/vendor/sulu/sulu/src/Sulu/Bundle/CoreBundle/Build/SuluBuilder.php:71
         Sulu\Bundle\CoreBundle\Build\SuluBuilder->execCommand() at /var/www/sulu-minimal/vendor/sulu/sulu/src/Sulu/Bundle/TranslateBundle/Build/TranslationBuilder.php:42
         Sulu\Bundle\TranslateBundle\Build\TranslationBuilder->build() at /var/www/sulu-minimal/vendor/massive/build-bundle/Command/BuildCommand.php:167
         Massive\Bundle\BuildBundle\Command\BuildCommand->runBuilders() at /var/www/sulu-minimal/vendor/massive/build-bundle/Command/BuildCommand.php:101
         Massive\Bundle\BuildBundle\Command\BuildCommand->execute() at /var/www/sulu-minimal/vendor/symfony/symfony/src/Symfony/Component/Console/Command/Command.php:259
         Symfony\Component\Console\Command\Command->run() at /var/www/sulu-minimal/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:860
         Symfony\Component\Console\Application->doRunCommand() at /var/www/sulu-minimal/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:192
         Symfony\Component\Console\Application->doRun() at /var/www/sulu-minimal/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php:92
         Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at /var/www/sulu-minimal/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:123
         Symfony\Component\Console\Application->run() at /var/www/sulu-minimal/bin/console.php:23
         include() at /var/www/sulu-minimal/bin/adminconsole:7

`

#### Expected Behavior

It should be possible to override sulus default translations.

#### Steps to Reproduce

Override one of the sulu translations inside of your own bundle. Eg. navigation.blog

#### Possible Solutions

Dont throw an exception, maybe output just a warning.

### PR DESCRIPTION
**Pull request by marcelmoosbrugger**
| Q | A
| --- | ---
| Bug fix? | no
| New feature? | no
| Enhancement? | yes
| BC breaks? | no
| Deprecations? | no
| Fixed tickets | fixes #2569
| Related issues/PRs | https://github.com/sulu/sulu-standard/pull/723, https://github.com/sulu/sulu-minimal/pull/8
| License | MIT
| Documentation PR | https://github.com/sulu/sulu-docs/pull/237

#### What's in this PR?

The translation export command got adapted, so that it fetches the translation directly from the translation files via the translator service from symfony (instead of loading the translations from the database). As this change made the import command obsolete, it got removed. Moreover unused parts of the TranslateBundle got removed.

### CODE REVIEW

File: src/Sulu/Bundle/TranslateBundle/Build/TranslationBuilder.php [hunk 1]
```diff
@@ -32,14 +32,11 @@ public function getName()
...
+        return [];
     }
 
     public function build()
     {
-        foreach ($this->locales as $locale) {
-            $this->execCommand('Translations', 'sulu:translate:import', ['locale' => $locale]);
-            $this->execCommand('Translations', 'sulu:translate:export', ['locale' => $locale]);
-        }
+        $this->execCommand('Translations', 'sulu:translate:export');
```
Comment (danrot) [inline src/Sulu/Bundle/TranslateBundle/Build/TranslationBuilder.php]: Didn't we say we introduce a Composer Script Handler for that? So that this file can also be removed?

File: src/Sulu/Bundle/TranslateBundle/Command/ExportCommand.php [hunk 2]
```diff
@@ -76,50 +64,93 @@ protected function configure()
                 'sets the filename of the exported file',
                 'sulu'
             );
+
+        $this->setDescription(
+            'Loads translation messages as defined by the parameters '
+            . 'from the bundles and writes them to a file, which also can be configured '
+            . 'via the parameters. If a locale got specified, only the translation '
+            . 'corresponding to that locale get exported. Otherwise the translation '
+            . 'files get exported for all locales defined in the system.'
```
Comment (danrot) [inline src/Sulu/Bundle/TranslateBundle/Command/ExportCommand.php]: Use [NowDoc](http://php.net/manual/de/language.types.string.php#language.types.string.syntax.nowdoc) for the description.

File: src/Sulu/Bundle/TranslateBundle/Command/ExportCommand.php [hunk 3]
```diff
@@ -76,50 +64,93 @@ protected function configure()
...
+     */
     protected function execute(InputInterface $input, OutputInterface $output)
     {
         $locale = $input->getArgument('locale');
-        $format = $input->getArgument('format');
+        $locales = [];
+        if ($locale) {
+            array_push($locales, $locale);
+        } else {
+            $locales = array_merge($locales, $this->getContainer()->getParameter('sulu_core.translations'));
```
Comment (danrot) [inline src/Sulu/Bundle/TranslateBundle/Command/ExportCommand.php]: No need for `array_merge`, since `$locales` will be empty anyway. Same for the `array_push` above. Maybe instantiate `$locales` as null first, and fill it accordingly in the if?

File: src/Sulu/Bundle/TranslateBundle/Command/ExportCommand.php [hunk 4]
```diff
@@ -76,50 +64,93 @@ protected function configure()
...
+        }
+        foreach ($locales as $l) {
```
Comment (danrot) [inline src/Sulu/Bundle/TranslateBundle/Command/ExportCommand.php]: `$locales as $locale` - we also do not use abbreviations in foreach loops.

File: src/Sulu/Bundle/TranslateBundle/Command/ExportCommand.php [hunk 5]
```diff
@@ -76,50 +64,93 @@ protected function configure()
...
+    }
+
+    /**
+     * Executes the command for a given locale.
+     *
+     * @param InputInterface $input The input of the command
+     * @param OutputInterface $output The output of the command
+     * @param $locale string The locale
+     */
+    protected function executeForLocale(InputInterface $input, OutputInterface $output, $locale)
```
Comment (danrot) [inline src/Sulu/Bundle/TranslateBundle/Command/ExportCommand.php]: Isn't `exportForLocale` the better name? Then it is clearer what this  method is actually doing.

File: src/Sulu/Bundle/TranslateBundle/Command/ExportCommand.php [hunk 6]
```diff
@@ -76,50 +64,93 @@ protected function configure()
...
+    {
+        $formatInput = $input->getArgument('format');
         $backend = $input->getOption('backend');
         $frontend = $input->getOption('frontend');
```
Comment (danrot) [inline src/Sulu/Bundle/TranslateBundle/Command/ExportCommand.php]: Should we keep these two options? /cc @chirimoya

File: src/Sulu/Bundle/TranslateBundle/README.md [hunk 7]
```diff
@@ -8,8 +8,7 @@ The SuluTranslateBundle builds on other sulu-cmf bundles. It provides a solution
 
 ## Features
 
-* Export/Import Translations to json/xlf format
-* Translation editing 
+* Export Translations to json/xlf format
```
Comment (danrot) [inline src/Sulu/Bundle/TranslateBundle/README.md]: Should we keep the README at all? /cc @chirimoya

File: src/Sulu/Bundle/TranslateBundle/Tests/Functional/Translate/ExportTest.php [hunk 8]
```diff
@@ -41,279 +32,88 @@ public static function setUpBeforeClass()
...
-
-        $translation23 = new Translation();
-        $translation23->setCatalogue($catalogue2);
-        $translation23->setCode($code23);
-        $translation23->setValue('Exports are super configurable');
-        $this->em->persist($translation23);
-
-        $this->em->flush();
+        /** @var \Symfony\Component\Console\Output\OutputInterface $output */
+        $output = $this->createMock('Symfony\Component\Console\Output\OutputInterface');
```
Comment (danrot) [inline src/Sulu/Bundle/TranslateBundle/Tests/Functional/Translate/ExportTest.php]: Please use [Prophecy](https://github.com/phpspec/prophecy) for the tests. It's included in PHPUnit.

File: src/Sulu/Bundle/TranslateBundle/Command/ExportCommand.php (hunk 4 above)
Comment (marcelmoosbrugger) [inline src/Sulu/Bundle/TranslateBundle/Command/ExportCommand.php]: The thing is that $locale is already defined

File: src/Sulu/Bundle/TranslateBundle/Translate/Export.php [hunk 9]
```diff
@@ -233,64 +213,84 @@ public function getPath()
...
     /**
-     * @param int $packageId
+     * Executes the export by loading the catalogue and writing messages
+     * from the defined domains to the defined file.
      */
-    public function setPackageId($packageId)
+    public function execute()
     {
-        $this->packageId = $packageId;
+        $messages = [];
```
Comment (danrot) [inline src/Sulu/Bundle/TranslateBundle/Translate/Export.php]: Sry, have overseen this one before... This should actually be also `null`, and in the `if`s below there should be no `array_merge`.

Comment (marcelmoosbrugger) [inline src/Sulu/Bundle/TranslateBundle/Translate/Export.php]: This array_merge is necessary

**Comment by danrot** [comment]
Looks good, waiting for tests.
