### PR TITLE
fixed broken UserManager when used without Security

### LINKED ISSUE #3196: UserManager is broken for non secured website-kernel
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | ---
| Browser Version | ---

#### Actual Behavior

If you us the UserManager in a non secured website-kernel the userRepository is null but will be used in the whole class.

#### Expected Behavior

The UserManager should work without exceptions or throw explicit exception (not supported for example).

### PR DESCRIPTION
**Pull request by danrot**
| Q | A
| --- | ---
| Bug fix? | yes
| New feature? | no
| BC breaks? | no
| Deprecations? | no
| Fixed tickets | fixes #3196 
| Related issues/PRs | ---
| License | MIT
| Documentation PR | ---

#### What's in this PR?

This PR adds all the parameters to the `UserManager` except for the one really being absent when used without Security. Then all the queries should work.

### CODE REVIEW

File: src/Sulu/Bundle/SecurityBundle/DependencyInjection/Compiler/UserManagerCompilerPass.php [hunk 1]
```diff
@@ -23,32 +23,20 @@ class UserManagerCompilerPass implements CompilerPassInterface
...
-                )
-            );
-        }
+        $container->setDefinition(
+            'sulu_security.user_manager',
+            new Definition(
+                'Sulu\Bundle\SecurityBundle\UserManager\UserManager',
+                [
+                    new Reference('doctrine.orm.entity_manager'),
+                    $container->hasDefinition('security.token_storage') ? new Reference('security.encoder_factory') : null,
```
Comment (chirimoya) [inline src/Sulu/Bundle/SecurityBundle/DependencyInjection/Compiler/UserManagerCompilerPass.php]: use `security.encoder_factory`

Comment (danrot) [inline src/Sulu/Bundle/SecurityBundle/DependencyInjection/Compiler/UserManagerCompilerPass.php]: Tried to use `hasDefinition` with the `security.encoder_factory`, but for some reason some tests were failing then. Looks like it is necessary that way.
