### PR TITLE
Store values from image crop as integers

### LINKED ISSUE #5409: FormatOptions entity uses INT to store crop values but could receive FLOATS
| Q | A
| --- | ---
| sulu version | 2.1.0

# Actual Behavior

Sulu supplies FLOATS to the DB and MySQL will auto cast those to INT.

# Expected Behavior

Just save INTs to the DB

# Steps to Reproduce

Use PGSQL and try to save an copped image. It will crash on ->flush().

# Possible Solutions

Postgrsql doesn't auto cast and throws an error.  So somewhere the data should be casted to INT

### PR DESCRIPTION
**Pull request by kfrohwein**
| Q | A
| --- | ---
| Bug fix? | yes
| New feature? | no
| BC breaks? | no
| Deprecations? | no
| Fixed tickets | fixes #5409
| License | MIT

#### What's in this PR?

I added type casts and return types to the FormatOptions Entity Object.
As JS could provide FLOATs this might be a good place to make sure SULU and it's DB is working with INTs in the end.

By doing this I figured that

`$fileVersion->addFormatOptions($formatOptions);`

relies on

`$formatOptions->setFormatKey($formatKey);`

is already called or the array key will be NULL
No clue how this ever could have been able to run but probably the array of format options is never used.

#### Possible BC break
PHPStorm tells me that return self is PHP > 7 and the 1.6 still supports 5.5

#### Why?

JS might provide FLOATS and at least PGSQL will not save the crop then.

### CODE REVIEW

File: src/Sulu/Bundle/MediaBundle/Entity/FormatOptions.php [hunk 1]
```diff
@@ -101,9 +101,9 @@ public function getCropY()
      *
      * @return FormatOptions
      */
-    public function setCropWidth($cropWidth)
+    public function setCropWidth($cropWidth): self
     {
-        $this->cropWidth = $cropWidth;
+        $this->cropWidth = (int) $cropWidth;
```
Comment (alexander-schranz) [inline src/Sulu/Bundle/MediaBundle/Entity/FormatOptions.php:106]: same as above should be rounded `(int) \round(cropWidth)`

File: src/Sulu/Bundle/MediaBundle/Entity/FormatOptions.php [hunk 2]
```diff
@@ -125,9 +125,9 @@ public function getCropWidth()
      *
      * @return FormatOptions
      */
-    public function setCropHeight($cropHeight)
+    public function setCropHeight($cropHeight): self
     {
-        $this->cropHeight = $cropHeight;
+        $this->cropHeight = (int) $cropHeight;
```
Comment (alexander-schranz) [inline src/Sulu/Bundle/MediaBundle/Entity/FormatOptions.php:130]: same as above should be rounded `(int) \round($cropHeight)`

**Comment by kfrohwein** [comment]
@alexander-schranz So what about this PR? Is it okay now?

File: src/Sulu/Bundle/MediaBundle/Media/FormatOptions/FormatOptionsManager.php [hunk 3]
```diff
@@ -121,8 +121,8 @@ public function save($mediaId, $formatKey, array $data)
         if (!isset($formatOptions)) {
             $formatOptions = new FormatOptions();
             $formatOptions->setFileVersion($fileVersion);
-            $fileVersion->addFormatOptions($formatOptions);
             $formatOptions->setFormatKey($formatKey);
+            $fileVersion->addFormatOptions($formatOptions);
```
Comment (alexander-schranz) [inline src/Sulu/Bundle/MediaBundle/Media/FormatOptions/FormatOptionsManager.php:125]: This change is not necessary as adding can be done before it. In PHP a object is based by reference and not a copy so you can edit it.

Comment (alexander-schranz) [reply src/Sulu/Bundle/MediaBundle/Media/FormatOptions/FormatOptionsManager.php:125]: Ah I see what you mean, ignore my comment :)

**Comment by danrot** [comment]
Just added the changelog line, will merge once the tests are green.

**Comment by alexander-schranz** [comment]
@kfrohwein Thank you!
