### PR TITLE
Fix page permissions when there is no array

### LINKED ISSUE #6482: Can't copy workspace if the pages within don't have document-level permissions set
| Q | A
| --- | ---
| Sulu Version | 2.3
| PHP Version | 8.0.15
| DB Version | Ver 15.1 Distrib 10.4.20-MariaDB
| Browser Version | Microsoft Edge 98.0.1108.43

# Actual Behavior

Upon executing the `sulu:webspaces:copy` command, the following exception is thrown:
```
Sulu\Bundle\PageBundle\Document\BasePageDocument::setPermissions(): Argument #1 ($permissions) must be of type array, null given, called in /var/www/vendor/sulu/sulu/src/Sulu/Bundle/PageBundle/Command/WebspaceCopyCommand.php on line 322
```

# Expected Behavior

The `sulu:webspaces:copy` command to execute succesfully without any exceptions.

# Steps to Reproduce

For now, investigation has resulted in the following hypothesis:
* This only occurs when the webspace has any page without set permissions.

# Possible Solutions

See the following slack thread for discussion about this bug:
https://sulu-io.slack.com/archives/C0430GGCV/p1644162170094529

As suggested, initializing the `$permissions` property in `PageBundle\Document\BasePageDocument` with an empty array should solve this issue.

### PR DESCRIPTION
**Pull request by alexander-schranz**
| Q | A
| --- | ---
| Bug fix? |  yes
| New feature? |  no
| BC breaks? | no 
| Deprecations? | no yes 
| Fixed tickets | fixes #6482 
| Related issues/PRs | # 
| License | MIT
| Documentation PR | sulu/sulu-docs# 

#### What's in this PR?

Fix page permissions when there is no array

#### Why?

There was a report here #6482 and also in the slack channel that this happens. That permission is null instead of an array. This change will initialize the BasePageDocument permissions always with an array to avoid that problem and will in restore avoid problem when permissions are there already null as it would be to hard to create a migration there.

### CODE REVIEW

File: src/Sulu/Bundle/PageBundle/Document/BasePageDocument.php [hunk 1]
```diff
@@ -240,7 +240,7 @@ class BasePageDocument implements
      *
      * @var array
      */
-    protected $permissions;
+    protected $permissions = [];
```
Comment (alexander-schranz) [inline src/Sulu/Bundle/PageBundle/Document/BasePageDocument.php:243]: this make sure that also when no `setPermissions` is called the permissions are as defined an array and not null.

File: src/Sulu/Bundle/PageBundle/Trash/PageTrashItemHandler.php [hunk 2]
```diff
@@ -183,7 +183,7 @@ public function restore(TrashItemInterface $trashItem, array $restoreFormData =
             $localizedPage->setStructureType($localeData['structureType']);
             $localizedPage->getStructure()->bind($localeData['structureData']);
             $localizedPage->setExtensionsData($localeData['extensionsData']);
-            $localizedPage->setPermissions($localeData['permissions']);
+            $localizedPage->setPermissions($localeData['permissions'] ?: []);
```
Comment (alexander-schranz) [inline src/Sulu/Bundle/PageBundle/Trash/PageTrashItemHandler.php:186]: this will fix restore for elements which were stored with permissions = null. We currently have no way to reproduce how it happens but it seems like old sulu which did upgrade are sometimes running into this case as it was reported by two different sulu users.

**Review by chirimoya — APPROVED** [review]

File: src/Sulu/Bundle/PageBundle/Tests/Functional/Controller/PageControllerTest.php [hunk 3]
```diff
@@ -69,6 +69,7 @@ class PageControllerTest extends SuluTestCase
     public function setUp(): void
     {
         $this->client = $this->createAuthenticatedClient();
+        $this->client->disableReboot(); // see https://github.com/symfony/symfony/issues/45580
```
Comment (alexander-schranz) [inline src/Sulu/Bundle/PageBundle/Tests/Functional/Controller/PageControllerTest.php:72]: this change is unrelated to the change in this PR. as the test already fails on 2.4 branch: https://github.com/sulu/sulu/commit/9561f75d81d89c8ced7733578525977457e63d2f

Comment (alexander-schranz) [reply src/Sulu/Bundle/PageBundle/Tests/Functional/Controller/PageControllerTest.php:72]: we already needed to add some `disableReboot` on 2.3 branch to fix this kind of issues.

File: src/Sulu/Bundle/TestBundle/Testing/TestUserProvider.php [hunk 4]
```diff
@@ -160,4 +161,9 @@ public function supportsClass($class)
     {
         return $this->userProvider->supportsClass($class);
     }
+
+    public function reset(): void
+    {
+        $this->user = null;
+    }
```
Comment (alexander-schranz) [inline src/Sulu/Bundle/TestBundle/Testing/TestUserProvider.php:168]: Symfony now resets the kernel between requests. As this means the entity manager unit of work is being resetd we also need to reset the user here that it is loaded again into Unit of work next time it is requested.
