### PR TITLE
Fixed domain switching in sulu-content path

### LINKED ISSUE #2266: BC break in twig `sulu_content_path` method.
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | 1.2.0-RC4

#### Actual Behavior

Calling `{{ sulu_contrent_path('/path/to') }}` will return the fullly qualified URL: http://foobar.com/de/path/to` previously it returned only the `/de/path/to`.

#### Expected Behavior

It should maintain the previous behavior, or we would introduce a BC break in a minor version upgrade.

#### Possible Solutions

- ?

### PR DESCRIPTION
**Pull request by wachterjohannes**
| Q | A
| --- | ---
| Bug fix? | yes
| New feature? | no
| BC breaks? | no
| Deprecations? | no
| Fixed tickets | fixes #2266
| Related issues/PRs | none
| License | MIT
| Documentation PR | none

#### What's in this PR?

This PR fixes the `sulu_content_path` twig function.

#### Why?

After changing the behavior and always returning the full-qualified-domain the domain and scheme switches if the url is not the main of the portal or the scheme was not passed to the function.

### CODE REVIEW

File: src/Sulu/Bundle/WebsiteBundle/Twig/Content/ContentPathTwigExtension.php [hunk 1]
```diff
@@ -66,24 +66,30 @@ public function getFunctions()
     /**
      * {@inheritdoc}
      */
-    public function getContentPath($url, $webspaceKey = null, $locale = null, $domain = null, $scheme = 'http')
+    public function getContentPath($url, $webspaceKey = null, $locale = null, $domain = null, $scheme = null)
```
Comment (wachterjohannes) [inline src/Sulu/Bundle/WebsiteBundle/Twig/Content/ContentPathTwigExtension.php]: the scheme will now be replaced by current if not passed
