### PR TITLE
Reset SingleSelection to null if the selected item was deleted

### LINKED ISSUE #4808: Can't edit single_page_selection after deleting selected page
| Q | A
| --- | ---
| Bug? | unsure
| New Feature? | no
| Sulu Version | 2.0.0-RC2

@alexander-schranz asked me to create this issue.

#### Actual Behavior

After Upgrading from 1.6.x to 2.0.0-RC2 (in multiple steps) a content element of type single_page_selection can't be edited in the admin section (screenshot attached).  

Bildschirmfoto 2019-10-09 um 08 47 30

Chrome dev tools show the following error message:

```Entity with the type "" and the id "384061b3-d76b-42fa-9618-168251d3507c" not found.```

#### Expected Behavior

There should be a way to a) delete the selection if the destination page isn't available/doesn't exist anymore or b) the user should be able to select another page. 

#### Steps to Reproduce

Not 100% sure since the sulu instance was upgraded in multiple steps following the develop branch and all beta releases. So far I wasn't able to reproduce this in any other instance, but I created a backup of the whole system to do further testing.

#### Possible Solutions

Rebuilding the admin js using npm or running `sulu:content:resource-locator:maintain` did not solve this.

### PR DESCRIPTION
**Pull request by danrot**
| Q | A
| --- | ---
| Bug fix? | yes
| New feature? | no
| BC breaks? | no
| Deprecations? | no
| Fixed tickets | fixes #4808
| Related issues/PRs | ---
| License | MIT
| Documentation PR | ---

#### What's in this PR?

This PR removes the current selection in a `SingleSelection` if the selected item does not exist anymore.

### CODE REVIEW

File: src/Sulu/Bundle/AdminBundle/Resources/js/containers/SingleSelection/SingleSelection.js [hunk 1]
```diff
@@ -45,7 +45,9 @@ class SingleSelection extends React.Component<Props> {
 
         this.singleSelectionStore = new SingleSelectionStore(resourceKey, value, locale, detailOptions);
         this.changeDisposer = reaction(
-            () => (this.singleSelectionStore.item ? this.singleSelectionStore.item.id : undefined),
+            () => !this.singleSelectionStore.item
```
Comment (nnatter) [inline src/Sulu/Bundle/AdminBundle/Resources/js/containers/SingleSelection/SingleSelection.js]: this change doesnt do anything right? 🤔

Comment (nnatter) [reply src/Sulu/Bundle/AdminBundle/Resources/js/containers/SingleSelection/SingleSelection.js]: okay i understand. not sure if it a good idea to implicitly rely on the difference between `undefined` and `null`. i guess this will lead to confusion in the future 🙈
