### PR TITLE
Fixed detect localization in admin

### LINKED ISSUE #3250: SuluRouteBundle takes always the default-locale.
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | 1.4.x

#### Actual Behavior
If we are using SuluRouteBundle in a Project with multiple locale and add a route for de and en the route-bundle always use translations from default-language.

#### Expected Behavior
Generate routes with the correct translations.

#### Steps to Reproduce

- `route_schema: /{translator.trans('router_event_prefix')}/{object.getTitle()}`
- generate a route in `en` and `de`
- now you have the similar routes for de and en.

#### Possible Solutions
- For `sulu:route:update`-command add a locale parameter.

### PR DESCRIPTION
**Pull request by wachterjohannes**
| Q | A
| --- | ---
| Bug fix? | yes
| New feature? | no
| BC breaks? | no
| Deprecations? | no
| Fixed tickets | fixes #3250
| Related issues/PRs | none
| License | MIT
| Documentation PR | none

#### What's in this PR?

This PR fixes the detection of localization in the backend if no webspace is given.

#### Why?

The route-manager uses the `RequestAnalyzerTranslator` to translate the routes. Currently if no webspace is given not locale will be set on the translator.

Additionally the command `sulu:route:update` get a new argument locale - which enables it to generate locale specific routes.

#### TODO

- [x] update route command locale

### CODE REVIEW

**Comment by wachterjohannes** [comment]
@dominikmatt ping

File: src/Sulu/Bundle/RouteBundle/Command/UpdateRouteCommand.php [hunk 1]
```diff
@@ -32,6 +32,7 @@ protected function configure()
     {
         $this->setName('sulu:route:update')
             ->addArgument('entity', InputArgument::REQUIRED)
+            ->addArgument('locale', InputArgument::REQUIRED)
```
Comment (danrot) [inline src/Sulu/Bundle/RouteBundle/Command/UpdateRouteCommand.php]: Why is it required? Shouldn't it be possible to update all routes with omitting the locale?

File: src/Sulu/Component/Webspace/Tests/Unit/Analyzer/Attributes/AdminRequestProcessorTest.php [hunk 2]
```diff
@@ -47,12 +47,13 @@ public function testProcess(array $expected = [], $webspaceKey = null, $locale =
         $request->get('locale', $language)->willReturn($locale ?: $language);
         $request->get('language')->willReturn($language);
 
-        $localization = $this->prophesize(Localization::class);
-
         $webspace = $this->prophesize(Webspace::class);
         $webspace->getKey()->willReturn($webspaceKey);
+
+        $localization = null;
         if ($locale || $language) {
```
Comment (danrot) [inline src/Sulu/Component/Webspace/Tests/Unit/Analyzer/Attributes/AdminRequestProcessorTest.php]: I would move that `||` part out if the if in a separate variable, so that you don't have to do `$locale ?: $language` twice in the block afterwards.

File: src/Sulu/Component/Webspace/Analyzer/Attributes/PortalInformationRequestProcessor.php [hunk 3]
```diff
@@ -55,6 +55,10 @@ public function process(Request $request, RequestAttributes $requestAttributes)
         }
 
         $attributes['localization'] = $portalInformation->getLocalization();
+        if ($portalInformation->getLocalization()) {
```
Comment (danrot) [inline src/Sulu/Component/Webspace/Analyzer/Attributes/PortalInformationRequestProcessor.php]: I would use `$attributes['localization']`, because we can save another function call that way.

File: src/Sulu/Component/Webspace/Analyzer/Attributes/PortalInformationRequestProcessor.php [hunk 4]
```diff
@@ -55,6 +55,10 @@ public function process(Request $request, RequestAttributes $requestAttributes)
...
+            $attributes['locale'] = $portalInformation->getLocalization()->getLocale();
```
Comment (danrot) [inline src/Sulu/Component/Webspace/Analyzer/Attributes/PortalInformationRequestProcessor.php]: `$attributes['localization']->getLocale()`

And I think it's not that cool to have a `locale` and a `localization` attribute here, but I guess it is necessary to keep BC, right?

File: src/Sulu/Bundle/RouteBundle/Command/UpdateRouteCommand.php (hunk 1 above)
Comment (wachterjohannes) [inline src/Sulu/Bundle/RouteBundle/Command/UpdateRouteCommand.php]: the problem is that at this place we have no idea which locales should be present here.

File: src/Sulu/Component/Webspace/Analyzer/Attributes/PortalInformationRequestProcessor.php (hunk 4 above)
Comment (wachterjohannes) [inline src/Sulu/Component/Webspace/Analyzer/Attributes/PortalInformationRequestProcessor.php]: right (:

File: src/Sulu/Bundle/RouteBundle/Command/UpdateRouteCommand.php (hunk 1 above)
Comment (danrot) [inline src/Sulu/Bundle/RouteBundle/Command/UpdateRouteCommand.php]: The localizations have to be configured somewhere, shouldn't they? Can't we just use the `LocalizationProvider`?

Comment (wachterjohannes) [inline src/Sulu/Bundle/RouteBundle/Command/UpdateRouteCommand.php]: but it could be that a component restricts the locales to a specific ones (by the manager for example).
