### PR TITLE
ignore ghost page parent when generating resource locator

### LINKED ISSUE #2433: Resource Locator cannot be generated when parent page is ghost
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | Specific version or SHA of a commit
| Browser Version | Browser name and version

#### Actual Behavior

When there is a structure similar the following:

image

And somebody wants to add a child page under `English` the URL generation in that page fails. The Response you get after filling in a title looks like that:

```
{"code":0,"message":"","errors":[{"message":"","code":0,"trace":[{"namespace":"","short_class":"","class":"","type":"","function":"","file":"\/Users\/daniel\/Development\/massiveart\/sulu-test\/vendor\/sulu\/sulu\/src\/Sulu\/Component\/Content\/Types\/Rlp\/Mapper\/PhpcrMapper.php","line":124,"args":[]},{"namespace":"Sulu\\Component\\Content\\Types\\Rlp\\Mapper","short_class":"PhpcrMapper","class":"Sulu\\Component\\Content\\Types\\Rlp\\Mapper\\PhpcrMapper","type":"->","function":"loadByContent","file":"\/Users\/daniel\/Development\/massiveart\/sulu-test\/vendor\/sulu\/sulu\/src\/Sulu\/Component\/Content\/Types\/Rlp\/Mapper\/PhpcrMapper.php","line":185,"args":[["object","Jackalope\\Node"],["string","sulu_io"],["string","de"],["null"]]},{"namespace":"Sulu\\Component\\Content\\Types\\Rlp\\Mapper","short_class":"PhpcrMapper","class":"Sulu\\Component\\Content\\Types\\Rlp\\Mapper\\PhpcrMapper","type":"->","function":"loadByContentUuid","file":"\/Users\/daniel\/Development\/massiveart\/sulu-test\/vendor\/sulu\/sulu\/src\/Sulu\/Component\/Content\/Types\/Rlp\/Strategy\/RlpStrategy.php","line":259,"args":[["string","557f92ab-385f-4245-a79a-d4738cdb2812"],["string","sulu_io"],["string","de"],["null"]]},{"namespace":"Sulu\\Component\\Content\\Types\\Rlp\\Strategy","short_class":"RlpStrategy","class":"Sulu\\Component\\Content\\Types\\Rlp\\Strategy\\RlpStrategy","type":"->","function":"loadByContentUuid","file":"\/Users\/daniel\/Development\/massiveart\/sulu-test\/vendor\/sulu\/sulu\/src\/Sulu\/Bundle\/ContentBundle\/Repository\/ResourceLocatorRepository.php","line":72,"args":[["string","557f92ab-385f-4245-a79a-d4738cdb2812"],["string","sulu_io"],["string","de"],["null"]]},{"namespace":"Sulu\\Bundle\\ContentBundle\\Repository","short_class":"ResourceLocatorRepository","class":"Sulu\\Bundle\\ContentBundle\\Repository\\ResourceLocatorRepository","type":"->","function":"generate","file":"\/Users\/daniel\/Development\/massiveart\/sulu-test\/vendor\/sulu\/sulu\/src\/Sulu\/Bundle\/ContentBundle\/Controller\/NodeResourcelocatorController.php","line":57,"args":[["array",{"title":["string","Asdf"]}],["string","557f92ab-385f-4245-a79a-d4738cdb2812"],["null"],["string","sulu_io"],["string","de"],["string","default"]]},{"namespace":"Sulu\\Bundle\\ContentBundle\\Controller","short_class":"NodeResourcelocatorController","class":"Sulu\\Bundle\\ContentBundle\\Controller\\NodeResourcelocatorController","type":"->","function":"postGenerateAction","args":[]},{"namespace":"","short_class":"","class":"","type":"","function":"call_user_func_array","file":"\/Users\/daniel\/Development\/massiveart\/sulu-test\/app\/bootstrap.php.cache","line":3206,"args":[["array",[["object","Sulu\\Bundle\\ContentBundle\\Controller\\NodeResourcelocatorController"],["string","postGenerateAction"]]],["array",[]]]},{"namespace":"Symfony\\Component\\HttpKernel","short_class":"HttpKernel","class":"Symfony\\Component\\HttpKernel\\HttpKernel","type":"->","function":"handleRaw","file":"\/Users\/daniel\/Development\/massiveart\/sulu-test\/app\/bootstrap.php.cache","line":3168,"args":[["object","Symfony\\Component\\HttpFoundation\\Request"],["string","1"]]},{"namespace":"Symfony\\Component\\HttpKernel","short_class":"HttpKernel","class":"Symfony\\Component\\HttpKernel\\HttpKernel","type":"->","function":"handle","file":"\/Users\/daniel\/Development\/massiveart\/sulu-test\/app\/bootstrap.php.cache","line":3319,"args":[["object","Symfony\\Component\\HttpFoundation\\Request"],["string","1"],["boolean",true]]},{"namespace":"Symfony\\Component\\HttpKernel\\DependencyInjection","short_class":"ContainerAwareHttpKernel","class":"Symfony\\Component\\HttpKernel\\DependencyInjection\\ContainerAwareHttpKernel","type":"->","function":"handle","file":"\/Users\/daniel\/Development\/massiveart\/sulu-test\/app\/bootstrap.php.cache","line":2509,"args":[["object","Symfony\\Component\\HttpFoundation\\Request"],["string","1"],["boolean",true]]},{"namespace":"Symfony\\Component\\HttpKernel","short_class":"Kernel","class":"Symfony\\Component\\HttpKernel\\Kernel","type":"->","function":"handle","file":"\/Users\/daniel\/Development\/massiveart\/sulu-test\/web\/admin.php","line":54,"args":[["object","Symfony\\Component\\HttpFoundation\\Request"]]}],"class":"Sulu\\Component\\Content\\Exception\\ResourceLocatorNotFoundException","statusCode":500,"headers":[],"file":"\/Users\/daniel\/Development\/massiveart\/sulu-test\/vendor\/sulu\/sulu\/src\/Sulu\/Component\/Content\/Types\/Rlp\/Mapper\/PhpcrMapper.php","line":124}]}
```
#### Expected Behavior

The URL should be generated with the part of the `English` page. So the result should be `test/<your-new-url>`.

#### Steps to Reproduce

1. Create a page
2. Switch the language so that the new page is a ghost
3. Add a child to the ghost page
4. Enter a title
5. No URL is generated and the sent request fails

### PR DESCRIPTION
**Pull request by nnatter**
| Q | A
| --- | ---
| Bug fix? | yes
| New feature? | no
| BC breaks? | no
| Deprecations? | no
| Fixed tickets | fixes #2433
| Related issues/PRs | -
| License | MIT
| Documentation PR | -

#### What's in this PR?

This PR fixes the bug which occured when generating resource locator paths for new pages with a ghost-page parent (See #2433).
The misbehaviour is fixed by using the first ancestor of the new page which is not a ghost-page for path generation.

### CODE REVIEW

File: src/Sulu/Bundle/ContentBundle/Repository/ResourceLocatorRepository.php [hunk 1]
```diff
@@ -155,4 +174,20 @@ private function implodeRlpParts(StructureInterface $structure, array $parts, $s
...
     }
+
+    /**
+     * Returns the first ancestor-or-self of the given document which is not a ghost-document.
+     * If all ancestor documents are ghost-documents, the root of the documents is returned.
+     *
+     * @param object    $document
+     * @return object
+     */
+    private function getNonGhostAncestor($document)
```
Comment (nnatter) [inline src/Sulu/Bundle/ContentBundle/Repository/ResourceLocatorRepository.php]: i am not sure, if this ist the right class for this method.

File: src/Sulu/Bundle/ContentBundle/Repository/ResourceLocatorRepository.php [hunk 2]
```diff
@@ -155,4 +174,22 @@ private function implodeRlpParts(StructureInterface $structure, array $parts, $s
...
+     * If all ancestor documents are ghost-documents, the root of the documents is returned.
+     *
+     * @param object    $document
+     *
+     * @return object
+     */
+    private function getNonGhostAncestor($document)
+    {
+        while ($this->documentInspector->getLocalizationState($document) === LocalizationState::GHOST &&
+        $document instanceof ParentBehavior) {
```
Comment (danrot) [inline src/Sulu/Bundle/ContentBundle/Repository/ResourceLocatorRepository.php]: Please indent correctly:

```php
while ($this->documentInspector->getLocalizationState($document) === LocalizationState::GHOST
    && $document instanceof ParentBehavior
) {
    // ...
}
```

The `&&` should be in front, because it is important to know how the two statements are connected.

File: src/Sulu/Bundle/ContentBundle/Repository/ResourceLocatorRepository.php [hunk 3]
```diff
@@ -155,4 +174,23 @@ private function implodeRlpParts(StructureInterface $structure, array $parts, $s
...
+
+    /**
+     * Returns the first ancestor-or-self of the given document which is not a ghost-document.
+     * If all ancestor documents are ghost-documents, the root document is returned.
+     *
+     * @param object    $document
+     *
+     * @return object
+     */
+    private function getNonGhostAncestor($document)
```
Comment (nnatter) [inline src/Sulu/Bundle/ContentBundle/Repository/ResourceLocatorRepository.php]: i am not sure, if this is the right class for this method.

**Comment by danrot** [comment]
Looks good, just waiting for the tests.
