### PR TITLE
fixed maintain command for resource locator

### LINKED ISSUE #2818: Command sulu:content:resource-locator:maintain not working
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | 1.3

#### Actual Behavior

When calling `bin/adminconsole sulu:content:resource-locator:maintain` an exception is thrown:
```
 [Symfony\Component\Debug\Exception\FatalThrowableError]
  Type error: Argument 1 passed to Sulu\Component\Content\Types\Rlp\Strategy\RlpStrategy::loadByContent() must implement interface Sulu\Component\Content\Document\B
  ehavior\ResourceSegmentBehavior, instance of Jackalope\Node given, called in vendor/sulu/sulu/src/Sulu/Bundle/ContentBundle/Command/Maintai
  nResourceLocatorCommand.php on line 134
```

#### Steps to Reproduce

Just run `bin/adminconsole sulu:content:resource-locator:maintain`

### PR DESCRIPTION
**Pull request by danrot**
| Q | A
| --- | ---
| Bug fix? | yes
| New feature? | no
| BC breaks? | no
| Deprecations? | no
| Fixed tickets | fixes #2818
| Related issues/PRs | none
| License | MIT
| Documentation PR | none

#### What's in this PR?

This PR fixes the command for maintaining the resource locator. It only fixes them in the live workspace, because on the draft workspace it might contain data that has been edited by the content manager.

### CODE REVIEW

File: src/Sulu/Bundle/ContentBundle/Command/MaintainResourceLocatorCommand.php [hunk 1]
```diff
@@ -65,93 +110,84 @@ private function upgradeLocale(Webspace $webspace, Localization $localization, O
...
-        /** @var SessionManagerInterface $sessionManager */
-        $sessionManager = $this->getContainer()->get('sulu.phpcr.session');
-        $session = $sessionManager->getSession();
-        $node = $session->getNodeByIdentifier($page->getUuid());
+        $locale = $localization->getLocale();
 
-        /** @var RlpStrategyInterface $strategy */
-        $strategy = $this->getContainer()->get('sulu.content.rlp.strategy.tree');
+        $localizedTemplatePropertyName = $this->propertyEncoder->localizedSystemName('template', $locale);
+        if (!$node->hasProperty($localizedTemplatePropertyName)) {
```
Comment (danrot) [inline src/Sulu/Bundle/ContentBundle/Command/MaintainResourceLocatorCommand.php]: @chirimoya I have to check for the template, because if there is no template I don't know the URL field at all.

**Comment by chirimoya** [comment]
ACK
