### PR TITLE
Display error bar when media upload fails in MediaOverview

### LINKED ISSUE #5540: Error handling frontend of media library
# Problem description

I’ve extended the `MediaManager.php `. When i throw a:
```
throw new MediaException('Blocked file type', MediaException::EXCEPTION_CODE_BLOCKED_FILE_TYPE);
```
In the `save()` function, no error is triggered in the CMS.

It just glitches and the user has no clue what happened.

# Proposed solution

Ability to display a red error bar in the media library after throwing an error from a controller.
Underneath answer by @nnatter 

> it looks like there is no error handling at all implemented in the frontend at the moment. at least, we need to adjust the MediaUploadStore, the MultiMediaDropzone, the MediaCollection and the MediaOverview

### PR DESCRIPTION
**Pull request by nnatter**
| Q | A
| --- | ---
| Bug fix? | no
| New feature? | no
| BC breaks? | no
| Deprecations? | no
| Fixed tickets | fixes #5540
| License | MIT

#### What's in this PR?

This PR adjusts the `MediaOverview` view to display an error bar when the upload of a file fails. To do this, the `MediaUploadStore`, `MultiMediaDropzone` and `MediaCollection` were adjusted to support the handling of upload errors.

#### Why?

Because there is no feedback to the user if an error happens at the moment. See #5540.

### CODE REVIEW

**Review by danrot — CHANGES_REQUESTED** [review]

File: src/Sulu/Bundle/MediaBundle/Resources/js/stores/MediaUploadStore/MediaUploadStore.js [hunk 1]
```diff
@@ -173,7 +173,13 @@ export default class MediaUploadStore {
 
             xhr.open('POST', url);
 
-            xhr.onload = (event: any) => resolve(JSON.parse(event.target.response));
+            xhr.onload = (event: any) => {
+                if (event.target.status >= 200 && event.target.status <= 299) {
```
[the remark this answers is not in the document]
Comment (nnatter) [reply src/Sulu/Bundle/MediaBundle/Resources/js/stores/MediaUploadStore/MediaUploadStore.js:177]: unfortunately not: https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest
but this behaviour matches the behaviour of the `Response` object that is returned when using `fetch`: https://developer.mozilla.org/en-US/docs/Web/API/Response/ok

File: src/Sulu/Bundle/MediaBundle/Resources/translations/admin.de.json [hunk 2]
```diff
@@ -43,6 +43,7 @@
     "sulu_media.formats": "Formate",
     "sulu_media.all_collections": "Alle Kollektionen",
     "sulu_media.move_media": "Medien verschieben",
+    "sulu_admin.upload_server_error": "Beim Upload einer Datei ist ein Fehler aufgetreten.",
```
[the remark this answers is not in the document]
Comment (nnatter) [reply src/Sulu/Bundle/MediaBundle/Resources/translations/admin.de.json:46]: the error message shows up a single time because the `MultiMediaDropzone` catches the error via `Promise.all(uploadPromises)`

File: src/Sulu/Bundle/MediaBundle/Resources/js/containers/MediaCollection/MediaCollection.js [hunk 3]
```diff
@@ -62,6 +63,17 @@ class MediaCollection extends React.Component<Props> {
...
 
+    @action handleUploadError = (error: any) => {
+        const {mediaListStore, onUploadError} = this.props;
+
+        if (onUploadError) {
+            onUploadError(error);
+        }
+
+        mediaListStore.reset();
+        mediaListStore.reload();
```
[the remark this answers is not in the document]
Comment (nnatter) [reply src/Sulu/Bundle/MediaBundle/Resources/js/containers/MediaCollection/MediaCollection.js:74]: i thought that this is useful because some images might have been uploaded successfully. but dont have a strong opinion on the behaviour

File: src/Sulu/Bundle/MediaBundle/Resources/js/containers/MultiMediaDropzone/MultiMediaDropzone.js [hunk 4]
```diff
@@ -80,12 +84,18 @@ class MultiMediaDropzone extends React.Component<Props> {
...
+            onUpload(...media);
 
             setTimeout(() => {
-                this.props.onClose();
+                onClose();
                 this.destroyMediaUploadStores();
             }, 1000);
+        }).catch((e) => {
+            setTimeout(() => {
+                onClose();
```
[the remark this answers is not in the document]
Comment (nnatter) [reply src/Sulu/Bundle/MediaBundle/Resources/js/containers/MultiMediaDropzone/MultiMediaDropzone.js:95]: when not closing the popover, the "upload items" will not be removed therefore still be present if the popover is closed and opened a second time. but you are right about the error message too, it is not very visible while the popover is openend

File: src/Sulu/Bundle/MediaBundle/Resources/js/containers/MediaCollection/MediaCollection.js [hunk 5]
```diff
@@ -21,6 +21,7 @@ type Props = {|
     mediaListStore: ListStore,
     onCollectionNavigate: (collectionId: ?string | number) => void,
     onMediaNavigate?: (mediaId: string | number) => void,
+    onUploadError?: (error: any) => void,
```
[the remark this answers is not in the document]
Comment (nnatter) [reply src/Sulu/Bundle/MediaBundle/Resources/js/containers/MediaCollection/MediaCollection.js:24]: Changed this to string 🙂 

We are passing `event.target.response` to the callback in the `MediaUploadStore`: https://github.com/sulu/sulu/blob/master/src/Sulu/Bundle/MediaBundle/Resources/js/stores/MediaUploadStore/MediaUploadStore.js#L181

Looks like this is a string, if we do not set any `responseType`: https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/response

**Comment by nnatter** [comment]
I know the UX of this is not perfect, but I think it is already **a lot better** than just dont inform the user about the error at all like it is done now.
If somebody has a better idea in terms of UX, I am obviously happy to have a look at it 🙂  @sulu/core-team

File: src/Sulu/Bundle/MediaBundle/Resources/js/containers/MediaCollection/MediaCollection.js (hunk 3 above)
[the remark this answers is not in the document]
Comment (danrot) [reply src/Sulu/Bundle/MediaBundle/Resources/js/containers/MediaCollection/MediaCollection.js:74]: Okay, and that's the same behavior as when all images are successfully uploaded, right? Then it makes sense to me :+1:

File: src/Sulu/Bundle/MediaBundle/Resources/js/containers/MultiMediaDropzone/MultiMediaDropzone.js (hunk 4 above)
[the remark this answers is not in the document]
Comment (danrot) [reply src/Sulu/Bundle/MediaBundle/Resources/js/containers/MultiMediaDropzone/MultiMediaDropzone.js:95]: I would say if it would just have been about the uploaded items it would have to be solved in a different way, but since the error message should be visible it's probably better this way anyway.

File: src/Sulu/Bundle/MediaBundle/Resources/js/stores/MediaUploadStore/MediaUploadStore.js (hunk 1 above)
[the remark this answers is not in the document]
Comment (danrot) [reply src/Sulu/Bundle/MediaBundle/Resources/js/stores/MediaUploadStore/MediaUploadStore.js:177]: Okay, it's fine then.

File: src/Sulu/Bundle/MediaBundle/Resources/translations/admin.de.json (hunk 2 above)
[the remark this answers is not in the document]
Comment (danrot) [reply src/Sulu/Bundle/MediaBundle/Resources/translations/admin.de.json:46]: Should we maybe phrase it a little bit different then? Maybe "Beim Upload mancher Dateien ist ein Fehler augetreten."? Or maybe even better: "Nicht alle Dateien wurden erfolgreich hochgeladen.".

Would be a tiny change, but explains the error a bit better IMO.

File: src/Sulu/Bundle/MediaBundle/Resources/js/containers/MultiMediaDropzone/tests/MultiMediaDropzone.test.js [hunk 6]
```diff
@@ -20,9 +20,15 @@ jest.mock('sulu-admin-bundle/utils', () => ({
 }));
 
 jest.mock('../../../stores/MediaUploadStore', () => jest.fn(function() {
-    this.create = jest.fn().mockReturnValue(Promise.resolve({
-        id: 123,
-    }));
+    this.create = jest.fn((_, file) => {
```
Comment (danrot) [inline src/Sulu/Bundle/MediaBundle/Resources/js/containers/MultiMediaDropzone/tests/MultiMediaDropzone.test.js:23]: Can't we put that into the test we do this for? This way it is hard to tell which tests need that, and it gets messier the bigger this file gets.

File: src/Sulu/Bundle/MediaBundle/Resources/js/stores/MediaUploadStore/tests/MediaUploadStore.test.js [hunk 7]
```diff
@@ -51,6 +51,78 @@ test('Calling the "update" method should make a "POST" request to the media upda
...
+    const fileData = new File([''], 'fileName');
+
+    const updatePromise = mediaUploadStore.update(fileData);
+
+    window.XMLHttpRequest.mock.instances[0].onload({target: {status: 400, response: 'invalid-format'}});
+
+    return expect(updatePromise).rejects.toEqual('invalid-format');
+});
+
+test('Promise returned by "update" method should be resolved if request is not successful', () => {
```
Comment (danrot) [inline src/Sulu/Bundle/MediaBundle/Resources/js/stores/MediaUploadStore/tests/MediaUploadStore.test.js:102]: "should be rejected", right?

**Review by danrot — CHANGES_REQUESTED** [review]

File: src/Sulu/Bundle/MediaBundle/Resources/js/containers/MultiMediaDropzone/tests/MultiMediaDropzone.test.js (hunk 6 above)
Comment (nnatter) [reply src/Sulu/Bundle/MediaBundle/Resources/js/containers/MultiMediaDropzone/tests/MultiMediaDropzone.test.js:23]: I am not sure how to do that unfortunately 😕 
The store is created inside of the `handleDrop` method of the component and the `MediaUploadStore.create` method is called in the next statement. Is there a way to mock this inside of the testcase?

https://github.com/sulu/sulu/blob/master/src/Sulu/Bundle/MediaBundle/Resources/js/containers/MultiMediaDropzone/MultiMediaDropzone.js#L75-L76

File: src/Sulu/Bundle/MediaBundle/Resources/js/stores/MediaUploadStore/tests/MediaUploadStore.test.js (hunk 7 above)
Comment (nnatter) [reply src/Sulu/Bundle/MediaBundle/Resources/js/stores/MediaUploadStore/tests/MediaUploadStore.test.js]: yes 👍

File: src/Sulu/Bundle/MediaBundle/Resources/translations/admin.en.json [hunk 8]
```diff
@@ -43,7 +43,7 @@
     "sulu_media.formats": "Formats",
     "sulu_media.all_collections": "All collections",
     "sulu_media.move_media": "Move media",
-    "sulu_admin.upload_server_error": "There was an error when uploading a file to the server.",
+    "sulu_media.upload_server_error": "There was an error while uploading one or multiple file to the server.",
```
Comment (danrot) [inline src/Sulu/Bundle/MediaBundle/Resources/translations/admin.en.json:46]: "one or multiple files"

File: src/Sulu/Bundle/MediaBundle/Resources/js/containers/MultiMediaDropzone/tests/MultiMediaDropzone.test.js (hunk 6 above)
Comment (danrot) [reply src/Sulu/Bundle/MediaBundle/Resources/js/containers/MultiMediaDropzone/tests/MultiMediaDropzone.test.js:23]: The `MediaUploadStore` has already been imported above, so you should be able to change the return value of the mocked function in the test itself somehow like this (not tested):

```javascript
MediaUploadStore.mock.instances[index].create.mockReturnValue(...);
```

**Review by danrot — CHANGES_REQUESTED** [review]

File: src/Sulu/Bundle/MediaBundle/Resources/js/containers/MultiMediaDropzone/tests/MultiMediaDropzone.test.js (hunk 6 above)
Comment (nnatter) [reply src/Sulu/Bundle/MediaBundle/Resources/js/containers/MultiMediaDropzone/tests/MultiMediaDropzone.test.js:23]: unfortunately calling `console.log(MediaUploadStore.mock.instances);` before the `onDrop` call logs an empty array (`[]`) 🙈

Comment (danrot) [reply src/Sulu/Bundle/MediaBundle/Resources/js/containers/MultiMediaDropzone/tests/MultiMediaDropzone.test.js:23]: Then the only other way I see around this, is to replace the entire constructor mock... But yeah, that might be a bit cumbersome too... Let's merge it like this, and hope it never makes any problems :see_no_evil:

File: src/Sulu/Bundle/MediaBundle/Resources/js/containers/MultiMediaDropzone/MultiMediaDropzone.js [hunk 9]
```diff
@@ -80,12 +84,18 @@ class MultiMediaDropzone extends React.Component<Props> {
         });
 
         return Promise.all(uploadPromises).then((...media) => {
```
Comment (danrot) [inline src/Sulu/Bundle/MediaBundle/Resources/js/containers/MultiMediaDropzone/MultiMediaDropzone.js:86]: This seems to behave a a bit strange, because this promise already seems to be resolved when the first request fails... I guess that could lead to some inconsistent state after reloading the view, because some uploads might still finish afterwards. Shouldn't we maybe use something like [`Promise.allSettled`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/allSettled) instead?

**Review by danrot — CHANGES_REQUESTED** [review]

File: src/Sulu/Bundle/MediaBundle/Resources/js/containers/MultiMediaDropzone/MultiMediaDropzone.js (hunk 9 above)
Comment (nnatter) [reply src/Sulu/Bundle/MediaBundle/Resources/js/containers/MultiMediaDropzone/MultiMediaDropzone.js:86]: yes, that would be better 🙂 
what should we pass to the `onUploadError` in that case? the first error or all errors?

Comment (danrot) [reply src/Sulu/Bundle/MediaBundle/Resources/js/containers/MultiMediaDropzone/MultiMediaDropzone.js:86]: All errors would probably make more sense, wouldn't it? But I guess it doesn't make a huge difference anyway, since the handling will not have a look at every single error, right?

Comment (nnatter) [reply src/Sulu/Bundle/MediaBundle/Resources/js/containers/MultiMediaDropzone/MultiMediaDropzone.js:86]: no in this case it will not, but maybe we will reuse the component somewhere and i am not sure what i would expect then 🙂
another possibility would be calling the callback for each error that happens? 🤔

Comment (danrot) [reply src/Sulu/Bundle/MediaBundle/Resources/js/containers/MultiMediaDropzone/MultiMediaDropzone.js:86]: Personally I would have expected all the errors at once... But that's subjective I guess. The advantage of that would be that it would be easier to handle in the calling component. If the callback is called every single time you would probably have to keep an array of values in the calling component, making that one more complicated than it needs to be.

Comment (nnatter) [reply src/Sulu/Bundle/MediaBundle/Resources/js/containers/MultiMediaDropzone/MultiMediaDropzone.js:86]: alright, going to use an array of errors then 🙂 just saw that this is also consistent with the argument `onUpload` callback

**Review by danrot — APPROVED** [review]
Will merge as soon as all the builds are green.
