### PR TITLE
made switching to copied languages possible

### LINKED ISSUE #2413: Change to copied language
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | eab4980aebde53e9e67461920f7a258961eb0676

#### Actual Behavior

When a language is copied with the following dialog, the system doesn't recognize that a new language version of the page exists:
image

That means when switching to the freshly copied language this overlay appears (which is wrong):
image

#### Expected Behavior

The second overlay should not appear anymore, because the content exists now.

#### Steps to Reproduce

1. Create a new page
2. Save it with some content
3. Choose `Edit -> Copy language` in the toolbar
4. Choose a language to copy to
5. Switch to the language you have just copied the content
6. You are seeing the overlay asking if an empty page should be created, or the content should be copied

### PR DESCRIPTION
**Pull request by marcelmoosbrugger**
| Q | A
| --- | ---
| Bug fix? | yes
| New feature? | no
| BC breaks? | no
| Deprecations? | no
| Fixed tickets | fixes #2413
| Related issues/PRs | none
| License | MIT
| Documentation PR | none

#### What's in this PR?

In the ContentBundle I added the copied languages to the concrete languages of the page. Moreover when switching to a non-concrete language in the language changer and then canceling the overlay the language changer gets now reset, which it didn't do before.

### CODE REVIEW

File: src/Sulu/Bundle/AdminBundle/Resources/public/js/components/header/main.js [hunk 1]
```diff
@@ -641,11 +652,19 @@ define([], function() {
...
          */
         languageChanged: function(item) {
-            this.sandbox.dom.html(this.$find(constants.languageChangerTitleSelector), item.title);
+            this.setLanguageChanger(item.title);
             this.sandbox.emit(LANGUAGE_CHANGED.call(this), item);
         },
 
         /**
+         * Changes the html of the language changer to a given string
+         * @param newLanguage {String} the string to show in the language changer
```
Comment (danrot) [inline src/Sulu/Bundle/AdminBundle/Resources/public/js/components/header/main.js]: `{String} newLanguage ...`
