### PR TITLE
Fix security check for snippet references tab

### LINKED ISSUE #7519: ParentViewNotFoundException for activities when the user has no snippet permissions.
| Q | A
| --- | ---
| Sulu Version | 2.6.3 
| PHP Version |  8.3.9 
| DB Version | 8.0.32
| Browser Version | Chrome 126

# Actual Behavior

When a user has permissions to see activities, but not the permissions to edit snippets, an error occurs on the `/admin/config` endpoint:

> ParentViewNotFoundException
> The route “sulu_snippet.edit_form” was defined as the parent of “sulu_snippet.edit_form.insights”, but the route “sulu_snippet.edit_form” does not exist

# Expected Behavior

No error should occur, the insights options should just not show for that user.

# Steps to Reproduce

In the admin (`/admin/#/roles`), edit the roles of a group. Add activities permissions, 
image
and revoke global snippet (edit) permissions.
image

# Possible Solutions

A possible solution will be provided in a PR.

### PR DESCRIPTION
**Pull request by jaapromijn**
| Q | A
| --- | ---
| Bug fix? | yes
| New feature? | no
| BC breaks? | no
| Deprecations? | no 
| Fixed tickets | fixes #7519
| Related issues/PRs | #7519
| License | MIT
| Documentation PR | 

#### What's in this PR?

When adding the insights items for snippets, check for the required permissions.

#### Why?

When a user has permissions to see activities, but not the permissions to edit snippets, an error occurs on the /admin/config endpoint:

ParentViewNotFoundException
The route “sulu_snippet.edit_form” was defined as the parent of “sulu_snippet.edit_form.insights”, but the route “sulu_snippet.edit_form” does not exist

### CODE REVIEW

File: src/Sulu/Bundle/SnippetBundle/Admin/SnippetAdmin.php [hunk 1]
```diff
@@ -226,26 +226,28 @@ public function configureViews(ViewCollection $viewCollection): void
...
-                    ->createResourceTabViewBuilder($insightsResourceTabViewName, '/insights')
-                    ->setResourceKey(SnippetDocument::RESOURCE_KEY)
-                    ->setTabOrder(6144)
-                    ->setTabTitle('sulu_admin.insights')
-                    ->setTitleProperty('')
-                    ->setParent(SnippetAdmin::EDIT_FORM_VIEW)
-            );
-
-            if ($this->activityViewBuilderFactory->hasActivityListPermission()) {
+            if ($this->securityChecker->hasPermission(static::SECURITY_CONTEXT, PermissionTypes::EDIT)) {
```
Comment (alexander-schranz) [inline src/Sulu/Bundle/SnippetBundle/Admin/SnippetAdmin.php]: this can directly be added to line `226` if statement as `if ( (current) && (this))` so no additional nesting if is required to show this detail tabs. As even the reference tab should not be shown if not having this permissions.

**Comment by alexander-schranz** [comment]
@jaapromijn thank you!
