### PR TITLE
Fixed default snippets for public workspace

### LINKED ISSUE #2739: Default Snippets settings wont be copied to live workspace
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | 1.3-RC2
| Browser Version | ---

#### Actual Behavior

The default snippet-settings wont be copied to live-workspace.

#### Expected Behavior

They should be copied immediately to live workspace.

### PR DESCRIPTION
**Pull request by danrot**
| Q | A
| --- | ---
| Bug fix? | yes
| New feature? | no
| BC breaks? | no
| Deprecations? | no
| Fixed tickets | fixes #2739
| Related issues/PRs | none
| License | MIT
| Documentation PR | none

#### What's in this PR?

This PR introduces a new `SessionManager`, which will set the property of a node for the default and live workspace. This `SessionManager` will then be used for the `SettingsManager`, which writes the current default snippets on the webspace node.

#### Why?

Because currently the default snippets are only saved in the default workspace, hence have no impact on the live website.

### CODE REVIEW

File: src/Sulu/Component/Webspace/Settings/SettingsManager.php [hunk 1]
```diff
@@ -23,10 +24,17 @@ class SettingsManager implements SettingsManagerInterface
      * @var SessionManagerInterface
      */
     private $sessionManager;
+    /**
+     * @var DeprecatedSessionManagerInterface
+     */
+    private $deprecatedSessionManager;
```
Comment (danrot) [inline src/Sulu/Component/Webspace/Settings/SettingsManager.php]: I don't have a better alias for this class 😕

File: src/Sulu/Component/Webspace/Settings/SettingsManager.php [hunk 2]
```diff
@@ -41,9 +49,13 @@ public function save($webspaceKey, $key, $data)
             $value = json_encode($data);
         }
 
-        $this->sessionManager->getWebspaceNode($webspaceKey)->setProperty($propertyName, $value);
+        $this->sessionManager->setNodeProperty(
+            $this->deprecatedSessionManager->getWebspacePath($webspaceKey),
```
Comment (danrot) [inline src/Sulu/Component/Webspace/Settings/SettingsManager.php]: Actually these calls should be considered deprecated, there is an issue for that: https://github.com/sulu/sulu/issues/2772

File: src/Sulu/Component/PHPCR/SessionManager/SessionManagerInterface.php [hunk 3]
```diff
@@ -34,6 +36,8 @@ public function getSession();
      * @param string $segment
      *
      * @return NodeInterface
+     *
+     * @deprecated Do not use anymore, because the node is always returned from the same session.
```
Comment (chirimoya) [inline src/Sulu/Component/PHPCR/SessionManager/SessionManagerInterface.php]: Deprecation notice isn't really clear. What do you mean with "same session"?

File: src/Sulu/Component/Webspace/Settings/SettingsManager.php (hunk 1 above)
Comment (chirimoya) [inline src/Sulu/Component/Webspace/Settings/SettingsManager.php]: ACK

File: src/Sulu/Component/PHPCR/SessionManager/SessionManagerInterface.php (hunk 3 above)
Comment (danrot) [inline src/Sulu/Component/PHPCR/SessionManager/SessionManagerInterface.php]: What do you suggest? `from the default session, although multiple sessions can exist`?

Comment (chirimoya) [inline src/Sulu/Component/PHPCR/SessionManager/SessionManagerInterface.php]: ACK

**Comment by chirimoya** [comment]
ACK

File: src/Sulu/Component/Webspace/Settings/SettingsManager.php [hunk 4]
```diff
@@ -23,10 +24,17 @@ class SettingsManager implements SettingsManagerInterface
      * @var SessionManagerInterface
      */
     private $sessionManager;
```
Comment (chirimoya) [inline src/Sulu/Component/Webspace/Settings/SettingsManager.php]: missing space

**Comment by chirimoya** [comment]
else ACK, waiting for tests.
