### PR TITLE
Fix smart content pagination

### LINKED ISSUE #8225: Pagination Issue in Article Grid
Hey there! I'm developing a website on Sulu 3.0-dev, i'm encountering a pagination problem in the articles grid. I have set "max_per_page" to 12, and there are 14 articles in total, so two pages should be generated. However, on page 1, the "hasNextPage" value is "null". Despite this, I can access and view page 2 correctly via the link. Where might the issue lie?
I've referred to this section of the documentation: https://docs.sulu.io/en/2.6/reference/content-types/smart_content.html#return-value 

Image

this is the <property> config of my file in news.xml

```
<property name="articles" type="smart_content" visibleCondition="'ROLE_SULU_ADMIN' in __user.roles">
            <params>
                <param name="provider" value="articles"/>
                <param name="category_root" value="articoli"/>

                <param name="max_per_page" value="12"/>

                <param name="properties" type="collection">
                    <param name="date" value="object.workflowPublished" />
                    <param name="title" value="title"/>
                    <param name="url" value="url"/>
                    <param name="description_intro" value="description_intro"/>
                    <param name="image_intro" value="image_intro"/>
                    <param name="categories" value="excerpt.categories"/>
                    <param name="locale" value="__locale"/>
<!--                    <param name="workflowPublished" value="workflowPublished"/>-->
                </param>
            </params>
        </property>
```

### PR DESCRIPTION
**Pull request by Prokyonn**
| Q | A
| --- | ---
| Bug fix? | yes
| New feature? | no
| BC breaks? | no
| Deprecations? | no
| Fixed tickets | fixes #8225 
| License | MIT

#### What's in this PR?

Fixes mixed up limit/maxPerPage logic.

#### Why?

Pagination does not work correctly.

### CODE REVIEW

File: packages/content/src/Application/SmartResolver/Resolver/SmartContentSmartResolver.php [hunk 1]
```diff
@@ -67,11 +69,18 @@ public function resolve(SmartResolvable $resolvable, ?string $locale = null): Co
...
         }
+
+        if (null !== $maxPerPage && $maxPerPage <= 0) {
+            throw new \InvalidArgumentException('The "maxPerPage" parameter must be a positive integer.');
+        }
+
         $smartContentProvider = $this->smartContentProviders->get($provider);
 
         $params = ['value' => $value, ...$parameters];
         $result = $smartContentProvider->findFlatBy($filters, $sortBys, $params);
```
Comment (alexander-schranz) [inline packages/content/src/Application/SmartResolver/Resolver/SmartContentSmartResolver.php:108]: I would not give `max_per_page` to the provider. Just `limit` and `offset`, the provider should not need to take care of pagination and limit vs max_per_page.

We could handle that already here correct:

```php
// # Convert page, limit, maxPerPage to limit and offset:

$filters = [
    'page' => 2,
    'limit' => 100,
    'maxPerPage' => 10,
];

$page = $filters['page'] ?? 1;
$limit = $filters['limit'] ?? null;
$maxPerPage = $filters['maxPerPage'] ?? null;
unset($filters['maxPerPage']);
unset($filters['page']);

$filters['offset'] = $maxPerPage ? (($page - 1) * $maxPerPage) :0;
$filters['limit'] = $maxPerPage ?? $limit;

$countByFilters = $filters;
unset($countByFilters['offset']));
unset($countByFilters['limit']));

$countByFilters['limit'] = $limit; // not required but avoids count all if limit is defined
```

**Review by alexander-schranz — APPROVED** [review]
