### PR TITLE
Added extension-guesser to fix wrong extensions on download

### LINKED ISSUE #3719: Uploading a media with incorrect extension throws error in MediaStreamController
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | 1.6.12

#### Actual Behavior

When you upload a media which contains a `.` in its filename but no extension the MediaStreamController pathcleanup will fail for example:

`fitness-seasons.agency--C-&-C--Rodach,-Johannes.jpg`

#### Expected Behavior

We should use the ExtensionGuesser from Symfony to get extension from the mimetype instead of using the pathinfo function.

#### Steps to Reproduce

1. Upload a file without a extension with the following name `fitness-seasons.agency--C-&-C--Rodach,-Johannes.jpg`

#### Possible Solutions

Use ExtensionGuesser from symfony to get the correct extension by mimetype instead of pathinfo.

### PR DESCRIPTION
**Pull request by wachterjohannes**
| Q | A
| --- | ---
| Bug fix? | yes
| New feature? | no
| BC breaks? | no
| Deprecations? | no
| Fixed tickets | fixes #3719 
| Related issues/PRs | none
| License | MIT
| Documentation PR | none

#### What's in this PR?

This PR fixes an error in download when the filename contains a wrong extension.

### CODE REVIEW

File: src/Sulu/Bundle/MediaBundle/Tests/Functional/Controller/MediaStreamControllerTest.php [hunk 1]
```diff
@@ -11,10 +11,60 @@
...
+        $media = $this->createMedia($filePath, 'File without Extension');
+        $client = $this->createAuthenticatedClient();
+        $client->request('GET', $media->getUrl());
+        $response = $client->getResponse();
+        $this->assertHttpStatusCode(200, $response);
+    }
+
+    public function testDownloadWithDotInName()
+    {
+        $filePath = $this->createMediaFile('fitness-seasons.agency--C-&-C--Rodach,-Johannes.jpg');
```
Comment (alexander-schranz) [inline src/Sulu/Bundle/MediaBundle/Tests/Functional/Controller/MediaStreamControllerTest.php]: add test case with this name but without `.jpg` extension.
