### PR TITLE
Bugfix: Set all/none button in settings/ user role

### LINKED ISSUE #2629: "Select all"/"Select none" in matrix not working properly
| Q | A |
| --- | --- |
| Bug? | yes |
| New Feature? | no |
| Sulu Version | 1.2.7 |
| Browser Version | all |
#### Actual Behavior

When editing an existing role with all items in the matrix selected and I deselect one item, the label on the right still says "Select none". However when i click the "Select none" label all items get selected.

Moreover the white "Select all" button does not toggle. When all items are selected it is useless.
#### Expected Behavior

The labels on the right of the matrix should change correctly from "Select none" to "Select all" when at first all items of the row are selected but one item got deselected.

The overall "Select all" button should either toggle between "Select all" and "Select none" or be disabled if all items are selected.
#### Steps to Reproduce

Navigate to the edit section of a role and change it according to the steps defined in "Actual behavior".

### PR DESCRIPTION
**Pull request by ReneZumtobel**
| Q | A |
| --- | --- |
| Bug fix? | yes |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Fixed tickets | fixes #2629 |
| Related issues/PRs | https://github.com/massiveart/husky/pull/717 |
| License | MIT |
| Documentation PR | sulu/sulu-docs#prnum |
#### What's in this PR?

Fixes bug with add all/ remove all permissions.

### CODE REVIEW

File: src/Sulu/Bundle/SecurityBundle/Resources/public/js/components/roles/edit/details/main.js [hunk 1]
```diff
@@ -48,8 +48,18 @@ define([
         },
 
         bindDOMEvents: function() {
-            this.sandbox.dom.on('#select-all', 'click', function() {
-                this.sandbox.emit('husky.matrix.set-all');
+            this.sandbox.dom.on('#change-all', 'click', function() {
+                if(!!$('#change-all').hasClass('set-all')) {
```
Comment (danrot) [inline src/Sulu/Bundle/SecurityBundle/Resources/public/js/components/roles/edit/details/main.js]: Classes should be used for styling. Keep this knowledge inside the component instead of moving it to the DOM (like `this.saved`).

File: web/admin/translations/sulu.nl.json [hunk 2]
```diff
@@ -0,0 +1 @@
+[]
```
Comment (danrot) [inline web/admin/translations/sulu.nl.json]: Why are these files here?

File: src/Sulu/Bundle/SecurityBundle/Resources/public/js/components/roles/edit/details/main.js [hunk 3]
```diff
@@ -18,7 +18,8 @@ define([
         permissionData,
         matrixContainerSelector = '#matrix-container',
         matrixSelector = '#matrix',
-        formSelector = '#role-form';
+        formSelector = '#role-form',
+        setSelectAll = false;
```
Comment (danrot) [inline src/Sulu/Bundle/SecurityBundle/Resources/public/js/components/roles/edit/details/main.js]: Why `set`? Doesn't make any sense to me. How about `allSelected` or `noneSelected`, depending on what you want to do.

File: src/Sulu/Bundle/SecurityBundle/Resources/public/js/components/roles/edit/details/main.js [hunk 4]
```diff
@@ -48,8 +49,16 @@ define([
...
+            this.sandbox.dom.on('#change-all', 'click', function() {
+                if(setSelectAll) {
+                    this.sandbox.emit('husky.matrix.set-all');
+                    setSelectAll = false;
+                    $('#change-all').html(this.sandbox.translate('security.roles.none'));
+                } else if(!setSelectAll) {
+                    this.sandbox.emit('husky.matrix.unset-all');
+                    setSelectAll = true;
+                    $('#change-all').html(this.sandbox.translate('security.roles.all'));
+                }
```
Comment (danrot) [inline src/Sulu/Bundle/SecurityBundle/Resources/public/js/components/roles/edit/details/main.js]: Extract into own method.

File: src/Sulu/Bundle/SecurityBundle/Resources/public/js/components/roles/edit/details/main.js [hunk 5]
```diff
@@ -172,6 +181,16 @@ define([
                 // unset god status as soon as one permission is removed
                 this.sandbox.dom.attr('#god', {checked: false});
             }
+
+            var oneActivated = $('#matrix').find('.is-active');
```
Comment (danrot) [inline src/Sulu/Bundle/SecurityBundle/Resources/public/js/components/roles/edit/details/main.js]: `activatedButtons`?

File: src/Sulu/Bundle/SecurityBundle/Resources/views/Template/role.form.html.twig [hunk 6]
```diff
@@ -50,8 +50,8 @@
     <div class="grid-row">
         <h2 class="divider"><%= translate('security.roles.permissions') %></h2>
 
-        <div id="select-all" class="btn fit m-bottom-20">
-            <%= translate('security.roles.all') %>
+        <div id="change-all" class="btn fit m-bottom-20 set-none">
```
Comment (danrot) [inline src/Sulu/Bundle/SecurityBundle/Resources/views/Template/role.form.html.twig]: `set-none` should not be necessary anymore, right?

**Comment by ReneZumtobel** [comment]
@danrot I implemented all your comments to this and the related husky PR.

File: src/Sulu/Bundle/SecurityBundle/Resources/public/js/components/roles/edit/details/main.js [hunk 7]
```diff
@@ -18,7 +18,8 @@ define([
         permissionData,
         matrixContainerSelector = '#matrix-container',
         matrixSelector = '#matrix',
-        formSelector = '#role-form';
+        formSelector = '#role-form',
+        noneSelected = false;
```
Comment (danrot) [inline src/Sulu/Bundle/SecurityBundle/Resources/public/js/components/roles/edit/details/main.js]: Would invert the logic and call it `allSelected`

Comment (danrot) [inline src/Sulu/Bundle/SecurityBundle/Resources/public/js/components/roles/edit/details/main.js]: Basically the same reasons as in https://github.com/massiveart/husky/pull/717#discussion_r87024937

File: src/Sulu/Bundle/SecurityBundle/Resources/public/js/components/roles/edit/details/main.js [hunk 8]
```diff
@@ -172,6 +171,16 @@ define([
                 // unset god status as soon as one permission is removed
                 this.sandbox.dom.attr('#god', {checked: false});
             }
+
+            var activatedButtons = $('#matrix').find('.is-active');
```
Comment (danrot) [inline src/Sulu/Bundle/SecurityBundle/Resources/public/js/components/roles/edit/details/main.js]: Can the var statement be moved to the beginning of this function?

File: src/Sulu/Bundle/SecurityBundle/Resources/public/js/components/roles/edit/details/main.js [hunk 9]
```diff
@@ -226,6 +235,18 @@ define([
             this.sandbox.start(this.$el);
         },
 
+        selectAllOrNone: function () {
+            if(noneSelected) {
```
Comment (danrot) [inline src/Sulu/Bundle/SecurityBundle/Resources/public/js/components/roles/edit/details/main.js]: Should be `!!noneSelected`. Actually, when thinking of it, wouldn't `someSelected` be the better name?

File: src/Sulu/Bundle/SecurityBundle/Resources/public/js/components/roles/edit/details/main.js [hunk 10]
```diff
@@ -226,6 +235,18 @@ define([
             this.sandbox.start(this.$el);
         },
 
+        selectAllOrNone: function () {
+            if(someSelected) {
```
Comment (danrot) [inline src/Sulu/Bundle/SecurityBundle/Resources/public/js/components/roles/edit/details/main.js]: `!!someSelected`
