### PR TITLE
Fixed sulu_content_load throwing exception when reference was deleted

### LINKED ISSUE #3050: fixed uncatchable exception when use sulu_content_load twig extension
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | Specific version or SHA of a commit
| Browser Version | Browser name and version

What's in this PR?

Please check https://github.com/sulu/sulu/pull/2969, its kind a like the same issue but now its for sulu_content_load

When a page is deleted but the reference is still in a snippet, we are getting a exception. It would be nice the get null instead so we can check in Twig

Why?

You are not able to catch exceptions in twig.

Example Usage

{{  sulu_content_load(block.button_link).content.url }}

### PR DESCRIPTION
**Pull request by rogamoore**
Fixed sulu_content_load throwing exception when reference was deleted

| Q | A
| --- | ---
| Bug fix? | yes
| New feature? | no
| BC breaks? | no
| Deprecations? | no
| Fixed tickets | fixes #3050 
| License | MIT

#### What's in this PR?

This fixes #3050. When sulu_content_load is used with a non-existing guid, it just returns null instead of throwing an exception (which is not catchable and breaks the page)

#### Why?

You are not able to catch exceptions in twig. This breaks the page when a referenced node is deleted.

#### Example Usage

~~~twig
{% set content = sulu_content_load(null) %}
{# content is now null #}

{% set content = sulu_content_load('not-existing-guid') %}
{# content is now null #}

~~~

#### ---
Would be nice if this could be also released in the 1.4.x branch as we have existing installations and no resources to upgrade them to 1.6.x at the moment.

### TODO

- [x] Tests need a helping hand

### CODE REVIEW

File: src/Sulu/Bundle/WebsiteBundle/Twig/Content/ContentTwigExtension.php [hunk 1]
```diff
@@ -73,13 +74,21 @@ public function getFunctions()
...
+            $contentStructure = $this->contentMapper->load(
+                $uuid,
+                $this->requestAnalyzer->getWebspace()->getKey(),
+                $this->requestAnalyzer->getCurrentLocalization()->getLocale()
+            );
 
-        return $this->structureResolver->resolve($contentStructure);
+            return $this->structureResolver->resolve($contentStructure);
+        } catch (DocumentNotFoundException $e) {
+            return;
```
Comment (danrot) [inline src/Sulu/Bundle/WebsiteBundle/Twig/Content/ContentTwigExtension.php]: We've talked about that today, and we thought it might make sense to throw some kind of `TwigException` here, or however that is called. The ones that twig throws in develop mode, and catches in production (because twig is running in strict mode). In the best case Twig would even write the error to the log. If all these assumptions are true, I would go for this way 😃

Comment (wachterjohannes) [inline src/Sulu/Bundle/WebsiteBundle/Twig/Content/ContentTwigExtension.php]: could you add some logging features here? like:

```php
$this->logger->error((string) $e);
```

File: src/Sulu/Bundle/WebsiteBundle/Tests/Unit/Sulu/Bundle/WebsiteBundle/Twig/ContentTwigExtensionTest.php [hunk 2]
```diff
@@ -169,6 +169,30 @@ public function testLoad()
         $this->assertEquals(['title' => []], $result['view']);
     }
 
+    public function testLoadNull()
+    {
+        $extension = new ContentTwigExtension(
```
Comment (wachterjohannes) [inline src/Sulu/Bundle/WebsiteBundle/Tests/Unit/Sulu/Bundle/WebsiteBundle/Twig/ContentTwigExtensionTest.php]: add following line here:

```php
         $this
             ->contentMapper
             ->load(Argument::cetera())
             ->shouldNotBeCalled();
```

File: src/Sulu/Bundle/WebsiteBundle/Tests/Unit/Sulu/Bundle/WebsiteBundle/Twig/ContentTwigExtensionTest.php [hunk 3]
```diff
@@ -169,6 +169,30 @@ public function testLoad()
...
+            $this->sessionManager->reveal(),
+            $this->requestAnalyzer->reveal()
+        );
+
+        $this->assertNull($extension->load(null));
+    }
+
+    public function testLoadNotExistingDocument()
+    {
+        $extension = new ContentTwigExtension(
```
Comment (wachterjohannes) [inline src/Sulu/Bundle/WebsiteBundle/Tests/Unit/Sulu/Bundle/WebsiteBundle/Twig/ContentTwigExtensionTest.php]: add following line before here:

```php
         $this
             ->contentMapper
             ->load(Argument::cetera())
             ->willThrow($this->prophesize(DocumentNotFoundException::class)->reveal());
```

File: src/Sulu/Bundle/WebsiteBundle/Twig/Content/ContentTwigExtension.php (hunk 1 above)
Comment (rogamoore) [reply src/Sulu/Bundle/WebsiteBundle/Twig/Content/ContentTwigExtension.php]: Hm, I'm not sure which exception you mean. :) Currently it is already being catched by Twig and converted to a Twig_Runtime exception. On production this will show a HTTP 500 Error.

image

**Comment by rogamoore** [comment]
@wachterjohannes Done! Thanks for the support :)
