### PR TITLE
Fixed sulu-content-path for webspaces with different domains for locales

### LINKED ISSUE #2358: Language Chooser form urls
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | 1.2.0
| Browser Version | All Browsers

#### Actual Behavior

If i loop through the urls array on a template, i get a key (en) and a value (/overview), but if i use different urls like http://mygermanurl.com/overview and http://myenglishurl.com/overview the function sulu_content_path() gives the wrong url back or false because url http://mygermanurl.com/overview doesnt exist.

#### Expected Behavior

If i use sulu_content_path with a language variable like sulu_content_path('/overview', 'en') i should also get the right baseUrl for this language.

#### Steps to Reproduce

Install a webspace with more than 1 language and use different urls and not 1 with location placeholder.

### PR DESCRIPTION
**Pull request by wachterjohannes**
| Q | A
| --- | ---
| Bug fix? | yes
| New feature? | no
| BC breaks? | no
| Deprecations? | no
| Fixed tickets | fixes #2358
| Related issues/PRs | none
| License | MIT
| Documentation PR | non

#### What's in this PR?

This PR introduces a fallback if a url for for current host does not exists.

If you pass no domain to `sulu_content_path('/test', 'sulu_io', 'en')` but the the domain of `en` is a different one than the current one.

#### Why?

Explained in the linked issue.

### CODE REVIEW

File: src/Sulu/Bundle/WebsiteBundle/Twig/Content/ContentPathTwigExtension.php [hunk 1]
```diff
@@ -66,41 +58,55 @@ public function getFunctions()
...
-        $domain = $domain ?: $this->requestAnalyzer->getAttribute('host');
         $scheme = $scheme ?: $this->requestAnalyzer->getAttribute('scheme');
         $locale = $locale ?: $this->requestAnalyzer->getCurrentLocalization()->getLocale();
 
         if ($webspaceKey !== null) {
-            if (!$this->webspaceManager->findWebspaceByKey($webspaceKey)->hasDomain($domain, $this->environment)) {
+            if (null !== $domain
+                && !$this->webspaceManager->findWebspaceByKey($webspaceKey)->hasDomain($domain, $this->environment)
+            ) {
                 $domain = null;
```
Comment (danrot) [inline src/Sulu/Bundle/WebsiteBundle/Twig/Content/ContentPathTwigExtension.php]: Isn't that some kind of hiding bugs from the developer? Wouldn't throwing an exception here be more appropriate? This way the developer might just wonder why the domain parameter is ignored.

File: src/Sulu/Bundle/WebsiteBundle/Twig/Content/ContentPathTwigExtension.php [hunk 2]
```diff
@@ -66,41 +58,55 @@ public function getFunctions()
...
+                    $this->environment,
+                    $locale,
+                    $webspaceKey,
+                    null,
+                    $scheme
+                );
+            }
+
+            return $url;
+        } elseif (strpos($route, '/') === 0) {
```
Comment (danrot) [inline src/Sulu/Bundle/WebsiteBundle/Twig/Content/ContentPathTwigExtension.php]: Is this if really necessary? Due to your changes this seems to be exactly the same call to `findUrlByResourceLocator` as in https://github.com/sulu/sulu/pull/2363/files#diff-896fde80dda7a566a31bc99704eaab23R77

Comment (wachterjohannes) [inline src/Sulu/Bundle/WebsiteBundle/Twig/Content/ContentPathTwigExtension.php]: merged with other `findUrlByResourceLocator`

File: src/Sulu/Bundle/WebsiteBundle/Twig/Content/ContentPathTwigExtension.php (hunk 1 above)
Comment (wachterjohannes) [inline src/Sulu/Bundle/WebsiteBundle/Twig/Content/ContentPathTwigExtension.php]: this check is wrong now (: before the domain was set to host if nothing was passed. i have corrected this check now and check that the host is in the webspace.

**Comment by wachterjohannes** [comment]
@danrot this is fixed now

File: src/Sulu/Bundle/WebsiteBundle/Twig/Content/ContentPathTwigExtension.php [hunk 3]
```diff
@@ -66,41 +58,41 @@ public function getFunctions()
     /**
      * {@inheritdoc}
      */
-    public function getContentPath($url, $webspaceKey = null, $locale = null, $domain = null, $scheme = null)
+    public function getContentPath($route, $webspaceKey = null, $locale = null, $domain = null, $scheme = null)
     {
-        if (!$this->requestAnalyzer) {
-            return $url;
+        if (!$this->requestAnalyzer || strpos($route, '/') !== 0) {
```
Comment (danrot) [inline src/Sulu/Bundle/WebsiteBundle/Twig/Content/ContentPathTwigExtension.php]: Please add a comment why `strpos` is needed here.

Comment (wachterjohannes) [inline src/Sulu/Bundle/WebsiteBundle/Twig/Content/ContentPathTwigExtension.php]: fixed and also added a testcase that this cannot be forgotten in the future.
