### PR TITLE
Prevent doubleclick of item while ordering column list

### LINKED ISSUE #5838: Double-clicking sorting-number inputs navigates to the edit view
| Q | A
| --- | ---
| Sulu Version | 2.2.4
| Browser Version | Multiple browsers
# Actual Behavior

When you go to a sorting view in a webspace and double-click one of the number fields, you get redirected to the page, instead of selecting the value inside the input field (the default behaviour of input fields).

# Expected Behavior

Just select the value inside the input.

# Steps to Reproduce

1. https://sulu.rocks/admin/#/webspaces/demo
2. Webspaces
3. Click 'order'
image
4. Double click one of the inputs
image

### PR DESCRIPTION
**Pull request by luca-rath**
| Q | A
| --- | ---
| Bug fix? | yes
| New feature? | no
| BC breaks? | no
| Deprecations? | no
| Fixed tickets | fixes #5838
| Related issues/PRs | -
| License | MIT
| Documentation PR | -

#### What's in this PR?

Prevent doubleclick of item while ordering column list

### CODE REVIEW

**Review by niklasnatter — APPROVED** [review]

File: src/Sulu/Bundle/AdminBundle/Resources/js/components/ColumnList/Item.js [hunk 1]
```diff
@@ -60,7 +60,11 @@ class Item extends React.Component<Props> {
     };
 
     handleDoubleClick = () => {
-        const {onDoubleClick, id} = this.props;
+        const {onDoubleClick, id, showOrderField} = this.props;
+
+        if (showOrderField) {
```
Comment (niklasnatter) [inline src/Sulu/Bundle/AdminBundle/Resources/js/components/ColumnList/Item.js:65]: would be nice to display a normal mouse icon if this is active

**Review by niklasnatter — CHANGES_REQUESTED** [review]

**Review by niklasnatter — APPROVED** [review]
