### PR TITLE
Videos can now be uploaded without ffmpeg

### LINKED ISSUE #2422: Uploading video file doesn't work
| Q | A |
| --- | --- |
| Bug? | yes |
| New Feature? | no |
| Sulu Version | 1.2.2 |
| Browser Version | all |
#### Actual Behavior

If I uploaded a video file and ffmpeg/ffprobe is missing on the server, I got a misunderstood error. The error said that the file size of 1.8MB is to big. 
#### Expected Behavior

Uploading of a video file should work properly. But it will not generate a preview image of the video.
There could be a notice, which explains that a server extension is missing or something like that and that's the reason why it couldn't generate a preview image.
#### Steps to Reproduce

Upload a video file (e.g. *.m4v) in Sulu.

### PR DESCRIPTION
**Pull request by ReneZumtobel**
| Q | A |
| --- | --- |
| Bug fix? | Yes |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Fixed tickets | fixes #2422 |
| Related issues/PRs | #issuenum |
| License | MIT |
| Documentation PR | sulu/sulu-docs#prnum |
#### What's in this PR?

Fixes bug which disabled video upload without ffmpeg.

### CODE REVIEW

**Comment by ReneZumtobel** [comment]
@danrot

File: src/Sulu/Bundle/MediaBundle/Tests/Unit/Media/Manager/MediaManagerTest.php [hunk 1]
```diff
@@ -298,6 +299,11 @@ public function testSaveWrongVersionType()
         $this->mediaManager->save($uploadedFile->reveal(), ['id' => 1], 42);
     }
 
+    public function testVideoUploadWithoutFFmpeg()
+    {
+        $this->ffprobe->format(Argument::any())->willThrow(ExecutableNotFoundException::class);
```
Comment (danrot) [inline src/Sulu/Bundle/MediaBundle/Tests/Unit/Media/Manager/MediaManagerTest.php]: This way you haven't really tested anything. You just said how the `format` method should behave. You still need a call on the `MediaManager`.
