### PR TITLE
fixed deindexing of documents for both workspaces

### LINKED ISSUE #2779: Removing a document does not remove it from the draft index
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | Specific version or SHA of a commit
| Browser Version | Browser name and version

#### Actual Behavior

When a document is deleted, it is only removed from the search index for the website, but not from the drafting one which is used in the backend.

#### Expected Behavior

The document should be removed from both search indexes.

#### Steps to Reproduce

1. Create a new page
2. See that it is found in both search (the one on the website and the one in the backend)
3. Delete the new page
4. The page is not found on the website search anymore, but still on the search in the backend

### PR DESCRIPTION
**Pull request by danrot**
| Q | A
| --- | ---
| Bug fix? | yes
| New feature? | no
| BC breaks? | no
| Deprecations? | no
| Fixed tickets | fixes #2779
| Related issues/PRs | none
| License | MIT
| Documentation PR | none

#### What's in this PR?

This PR sets the workflowstage to both possible values before deindexing them. This is necessary because the document is only removed from one of both indexes otherwise.

### CODE REVIEW

File: src/Sulu/Bundle/ContentBundle/Search/EventSubscriber/StructureSubscriber.php [hunk 1]
```diff
@@ -128,7 +128,19 @@ public function deindexRemovedDocument(RemoveEvent $event)
             return;
         }
 
-        $this->searchManager->deindex($document);
+        if (!$document instanceof WorkflowStageBehavior) {
+            $this->searchManager->deindex($document);
+        } else {
+            $workflowStage = $document->getWorkflowStage();
+
+            $document->setWorkflowStage(WorkflowStage::TEST);
```
Comment (chirimoya) [inline src/Sulu/Bundle/ContentBundle/Search/EventSubscriber/StructureSubscriber.php]: maybe loop over "all" workflow stages instead?

Comment (danrot) [inline src/Sulu/Bundle/ContentBundle/Search/EventSubscriber/StructureSubscriber.php]: How? Would you fake that somehow like this:

```php
foreach ([WorkflowStage::TEST, WorkflowStage::PUBLISHED] as $state) { ... }
```

Comment (chirimoya) [inline src/Sulu/Bundle/ContentBundle/Search/EventSubscriber/StructureSubscriber.php]:
```php
foreach (WorkflowStage::$stages as $state) { ... }
```
What do you think?
